### ISSUE TITLE
Gradient texture

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#1]
**Describe the bug**
Hi, the gradient texture Op don't apply the changes in the color editor selected

**To Reproduce**
1. Clicking the color the editor appears
2. Selecting the color works well
3. But the change is not working in the selected color

**Expected behavior**
The edited color is changed in the selected one

**Desktop (please complete the following information):**
I use Chrome in PC

**Additional context**
Thank you!

**Comment by tastez** [comment]
can confirm this on Edge - Gradient editor allows adding of new random colors and saving the gradient, but manually adjusting colors will not apply changes. 

**Xtra Comment**
If not mistaken, gradients can have alpha values as well, however the editor and color picker don't allow it at the moment.

**Comment by steam0r** [comment]
not sure how to reproduce this, chrome on pc:

![gradient](https://user-images.githubusercontent.com/151271/107765765-ae009c00-6d32-11eb-9ba7-af7fedc382ce.gif)

**Comment by tastez** [comment]
![gradient_edge](https://user-images.githubusercontent.com/78642112/107849838-1ec0ba80-6dfe-11eb-96b2-826d6e10e2a6.gif)
this is how it worked in Edge until yesterdays update! now everything seems good!

**Comment by n4hui** [comment]
I have another issue... it works again in Chrome, thank you! But when i save the result and open again the proyect, the colors are inverted :/

**Comment by steam0r** [comment]
@n4hui can you verify this on live (cables.gl) again after todays release? thanks!

**Comment by n4hui** [comment]
hi, yep unfortunately the issue continues in the new release :/

**Comment by steam0r** [comment]
i also cannot reproduce the inversion of colors, do you maybe have a simple example patch that i can test this on?

**Comment by n4hui** [comment]
Hi! I tried again and now it works well, thank you very much, the only detail is that now the web code of the colors is not available.
![Screenshot 2021-02-18 115145](https://user-images.githubusercontent.com/65823796/108399436-b861e080-71df-11eb-9f04-5a74201b3f5d.png)

**Comment by steam0r** [comment]
have put this in the cables backlog, will keep you updated. thanks for reporting!

**Comment by steam0r** [comment]
we replaced the colorpicker on dev, that fixes this

**Comment by n4hui** [comment]
thank you!

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
