### ISSUE TITLE
MeshInstancer and Picker

### ISSUE THREAD

**Issue by cristianvogel** [cables-gl/cables_docs#100]
**Describe the bug**
 the Ops.Gl.Shader.Picker and Ops.Gl.Shader.PickingMaterial don't really detect  the replicated Meshes.  The picker seems to detect the first instance, but none of the others. 

**To Reproduce**
Here is an example
https://cables.gl/p/61cdc07afbcaa454bbf629d4?s=OtxT6Fya1XWMoZfv

**Expected behavior**
EXpect to pick all instances

**Desktop (please complete the following information):**
Chrome, MacOS

**Comment by pandrr** [comment]
there is no picking happening in that patch

**Comment by pandrr** [comment]
updated the picker shader to work with mesh instancing.
but only possible that the whole instance array is pickable for now
