### ISSUE TITLE
MpPose (on Dev) very poor Performance on iDevices 

### ISSUE THREAD

**Issue by strangerattractor** [cables-gl/cables_docs#101]
**Describe the bug**
As soon as MpPose gets a Webcam HTMLElement input, the framerate on iDevices for the entire Patch drops to around 5-7 fps.
(tested on iPad Pro and iPhone SE)
Also, the FPS on my Laptop with RTX 2070 drops significantly when HTMLElement is connected. 

**To Reproduce**
1. Create new patch
2. add MainLoop, Performance, TriggerOnce
3. Use either newWebcamTexture or WebcamTexture and trigger it as necessary
4. Add MpPose
5. Open patch per RemoteViewer on iDevice
6. Observe FrameRate Drop as soon as MpPose gets connected. 

**Expected behavior**
Better Performance or use of Normale WebcamTexture (not HTML ELEMENT) in order to be able to reduce input Framerate or input Resultion into MpPose OP 

**Desktop (please complete the following information):**
 - Windows 10/11, OSX
 - Browser chrome 

**Smartphone (please complete the following information):**
 - Device: iOS 14.6 (iPhone) 14.7.1 (iPad Pro)
- Browser Chrome

**Comment by pandrr** [comment]
so did you try the options i put in for you ?

**Comment by pandrr** [comment]
also this is an external library that is slow in this case, no chance of optimizing for us

**Comment by strangerattractor** [comment]
> so did you try the options i put in for you ?

@pandrr 
yep, I tried all of them them. Switching Model Complexity to 0gives a tiny bit more performance but not enough, unfortunately.

Question: 
The PoseDetection OP also makes patches run slow if I don't add a triggerlimiter before the render trigger. 
May that be an option here too? Or is the system too closed?

**Comment by steam0r** [comment]
closing this, as we do not really have any means of improvig performance for these external libraries, sorry...
