### ISSUE TITLE
DeviceVibrate Op unresponsive on Android Pixel 6

### ISSUE THREAD

**Issue by sebastianpetrovski** [cables-gl/cables_docs#103]
**Describe the bug**
The DeviceVibrate Op stopped working on my Pixel 6 - it was working a month or 2 ago. No other devices on hand to test with.

**To Reproduce**
Here's a patch focused on just the issue.
https://cables.gl/p/61d3faf1c8b1e02afa0fdf76?s=DNOZTAHDWFi1EHzL

**Expected behavior**
50ms vibration on each touch start

**Screenshots**
![image](https://user-images.githubusercontent.com/74696962/148025510-f01f8005-7108-4157-9af1-536343c7c375.png)

**Desktop**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 96.0.4664.110

**Smartphone**
 - Device: Pixel 6
 - OS: Android 12 (5 December Security Update, 1 November Google Play System Update, Build SQ1D.211205.016.A4)
 - Browser: Chrome
 - Version: 96.0.04664.104

**Additional context**
While browsing others' cables patches yesterday the Motion Sensor patches were not working on my pixel 6 either. I vaguely remember reading somewhere about permissions conflicts affecting useability of V1 and V2 of the MotionSensor Op.

https://cables.gl/op/Ops.Devices.Mobile.MotionSensor_v2

![image](https://user-images.githubusercontent.com/74696962/148027161-7f2a56c5-71f5-401f-8528-741798b0e5f7.png)

**Comment by pandrr** [comment]
https://caniuse.com/?search=vibrate

feature is not supported in iframes anymore, this is what we have to do on cables.gl

so it will still work in exported patches IF your browser supports it (vibrate does not work on ios)

**Comment by sebastianpetrovski** [comment]
Thanks for getting back to me so quickly and for the explanation.

**Comment by sebastianpetrovski** [comment]
Quick update: Vibrate in iframe on Chrome is working again.

I left the vibrate part of the patch in, just in case it became allowed again and it seems like it did, just today.

The version of Chrome on my device changed, OS is the same. Specifications below.

- Device: Pixel 6
- OS: Android 12 (5 December Security Update, 1 November Google Play System Update, Build SQ1D.211205.016.A4)
- Browser: Chrome
- Version: 97.0.4692.70

**Comment by pandrr** [comment]
thanks for letting us know.

we tested it and it even worked in an iframe.

its basically out of our control...
