### ISSUE TITLE
A Null Op (Like in TouchDesigner/Houdini)

### ISSUE THREAD

**Issue by franckaubry** [cables-gl/cables_docs#104]
A null op (Like in TouchDesigner/Houdini)

While experimenting in patches, a lot of connecting and unconnecting is happening between the ops. Sometimes you create a chain but then try out something a little different in a another chain. For this reason it is very useful to have a Null op that works like the end of any op chain. It is also a very useful visually as it can be used as the end/wrap-up of an operation. This is common practice in TD/Houdini.
This op should work with any kind of data as input and adapt it's output based on what is connected to it.

Documentation from TouchDesigner/Houdini:
[https://docs.derivative.ca/Null_CHOP](url)
[https://www.sidefx.com/docs/houdini/nodes/sop/null.html](url)

**Comment by pandrr** [comment]
there are:

https://local.cables.local/op/Ops.Value.Number
https://local.cables.local/op/Ops.String.String_v2

something like that ?

**Comment by franckaubry** [comment]
These are good for these two particular data types, but what if you are dealing with arrays, geo, shaders or what not. It would be tremendously helpful to have that "chameleon" node that just adapts to whatever it receives or at least like in TD, where there is a Null op per data type.
I guess the "Set..." family of nodes kinda gets close to this if only they had an output that mirrored the input (could be an optional bool button to activate/deactivate that mirror output?)

I believe this video explains the benefit of the null workflow that avoid a great amount of reconnecting while patching:
[https://www.youtube.com/watch?v=u6hb-31gd1Q](url)

**Comment by pandrr** [comment]
currently this is not possible because of typesafe concepts of cables

but i dont really see the need, in cables its just one click to move lots of connections, not like in td in the video where you need 5 clicks to move multiple connections

- you can also use the sequence ops (SequenceNumbers, SequenceStrings, etc. )
- or the value.number ops
