### ISSUE TITLE
Tone.js lib is not importing?

### ISSUE THREAD

**Issue by cristianvogel** [cables-gl/cables_docs#105]
**Describe the bug**

**To Reproduce**
1. Carefully follow the guide at https://cables.gl/docs/5_writing_ops/webaudio/webaudio
2. Instantiate a brand new tone OP into an empty patch
3. Make sure the tone.js seems to be added to the op
4. Add those lines as it says in the guide

```
CABLES.WEBAUDIO.createAudioContext();
Tone.setContext(window.audioContext);
// now you can use all Web Audio nodes / tone.js functions
```
6. Save and reload
7. Can't add the new op start again at 1

**Expected behavior**
I expect to be able to use Tone functions

**Screenshots**

**Desktop (please complete the following information):**
 - MacOS
 - Chrome

**Additional context**

**Comment by pandrr** [comment]
![Screenshot 2022-01-05 at 08 56 45](https://user-images.githubusercontent.com/98792/148181080-34fa3821-890f-4ec3-8d3a-db4aa932d21c.png)

did you add the lib ?

works for me

please provide an example patch

**Comment by cristianvogel** [comment]
Yes, unless the import process is somehow malfunctioning for me. 

Here is a video of following the docs from my side
https://drive.google.com/file/d/1cJyvTGC9Fil00aUW5nvvrhdJEF3TdpIy/view?usp=sharing

I also have done it where I can see tone.js is attached in the library pane to the Op but it still throws the error

**Comment by cristianvogel** [comment]
I can't provide an example patch, because it doesn't get that far. Once the Op throws the error, the editor doesn't let me insert an instance of it

**Comment by pandrr** [comment]
which error, you did not provide an error message

**Comment by cristianvogel** [comment]
Tone is not defined 

At the end of the video...

**Comment by pandrr** [comment]
before you add the code, please make sure it has the lib listed there:

![Screenshot 2022-01-05 at 10 29 52](https://user-images.githubusercontent.com/98792/148194344-52d7ec71-626f-488a-84f4-7e9dedb50e55.png)

**Comment by pandrr** [comment]
we will also try a new tonejs version if its easily usable in cables

**Comment by cristianvogel** [comment]
I know its tedious , but please do watch this 60s video. 
https://drive.google.com/file/d/1SIAOsCtGhtLskCGCK6z5B2t7IGuqIX44/view?usp=sharing
I am not doing anything apart from what your docs ask me to do. 
Of course I am checking that the Lib is there.

**Comment by pandrr** [comment]
i watched it, we will work on improving, i just gave you a tip how it will work

**Comment by cristianvogel** [comment]
Danke. Is there anything I can do on the User side, to allow me to work with Tone op dev again, because I need it for an app project I started in Cable?

**Comment by pandrr** [comment]
`Of course I am checking that the Lib is there.` - in the video you are not

**Comment by pandrr** [comment]
ok i saw this now on a different machine. cables is loading tonejs but then its removing itself or something. 
cant fix this. maybe related to old version of tonejs

**Comment by steam0r** [comment]
there was a bug in the moduleloader of tonejs, fixed it on dev and live, kept tonejs version. please let us know if this solves your issue. thanks!

**Comment by cristianvogel** [comment]
yes, it seems fine now - thankyou!
