### ISSUE TITLE
Modal disappears on Android Pixel 6

### ISSUE THREAD

**Issue by sebastianpetrovski** [cables-gl/cables_docs#111]
**Describe the bug**
Modal disappears on trigger touch release on Pixel 6 in Chrome.

**To Reproduce**
tap the beach img and you'll see the modal displays for a split second and then dissapears. Tap and hold the beach img for a second and the modal will stay until you lift your finger from the trigger. Tap and hold for 2 seconds or more and the Modal will stay up, but it seems due to highlighting the close button.

Link to patch focused on issue: https://cables.gl/p/61d714aca4fab91b07d513b3?s=x9Davayq13CXb4Nl

**Expected behavior**
tap beach img > modal visible until user taps exit button or empty area on screen

**Screenshots**

https://user-images.githubusercontent.com/74696962/148422760-ded7cb0a-7e39-4019-ad43-327af20f6fc8.mp4

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version 96.0.4664.110

**Smartphone:**
 - Device: Pixel 6
 - OS: Android 12 (5 December Security Update, 1 November Google Play System Update, Build SQ1D.211205.016.A4)
 - Browser: Chrome
 - Version: 96.0.04664.104

**Additional context**
Tapping modal works as expected on iPad Pro 12.9inch (model # A1584) iOS 14.8.1 (18H107) in Chrome 96.0.4664.94 and in Safari.

**Comment by steam0r** [comment]
hey,

thanks for reporting this, i fixed this on dev:

 https://dev.cables.gl/p/61d714aca4fab91b07d513b3?s=x9Davayq13CXb4Nl

please let me know if this works in all your usecases now. thanks!

best,
stephan/steam

**Comment by sebastianpetrovski** [comment]
Hi Stephan,

Thanks! Yes it works in all usecases now!

That dark mode on the dev site looks 👌 btw

Best,

Sebastian
