### ISSUE TITLE
Collision Op?

### ISSUE THREAD

**Issue by deanvilgel** [cables-gl/cables_docs#113]
I know there is a Physics Op and Raycast Op to check Collision, Or transforming WASD Camera by displacement Color of geometry, but still this is too restrictive. If Castray can affect not only bounding box but also ordinary geometry, or Collision Op that directly affect Camera, Possibility for webgame or Metaverse creation will genuinely increased. 

Wish someday I could see Cables as main tool for Metaverse gen (:

**Comment by dudumaluf** [comment]
Hey ! Atm we dont have a way to set a bounding box so it has the same shape of a geometry.
but we have this op which creates a spherical or cubic bounding box around a geometry https://cables.gl/op/Ops.Physics.Body.PhysicsGeometryBody

Maybe take a look on these patches also, they might help. 
https://cables.gl/p/axJlQU
https://cables.gl/p/E13GaE

**Comment by deanvilgel** [comment]
Is there way to use Complicated mesh as collision? Examples that I saw were using bounding boxed cubes or spheres as collisions. 

Is there a way to make a Hill without directly editing Y value?

**Comment by dudumaluf** [comment]
> Is there way to use Complicated mesh as collision? Examples that I saw were using bounding boxed cubes or spheres as collisions.

We only have Box and Sphere as "Colliders" atm.

> 
> Is there a way to make a Hill without directly editing Y value?

About the hill question, with collisions ? not that I know.

**Comment by pandrr** [comment]
#83

**Comment by deanvilgel** [comment]
Cool! So this is already on a to do list (: thx for the hard work.

**Comment by pandrr** [comment]
we are switching the physics system to bullet/ammo.js soon, it will have more options for collision, and there will be a collision op, if you want an early peek, contact me
