### ISSUE TITLE
Wierd offset while exporting from RenderImage - [RenderImage is RenderAnim with countFrame value set to -1]

### ISSUE THREAD

**Issue by jaalibandar** [cables-gl/cables_docs#117]
**Describe the bug**
There seems to be a slight issue with the RenderAnim op - I needed an op to render images in fixed resolution - while the RenderAnim op kindof works it seems like too long a wait time to render images - so I just cloned the op and changed the countFrame value to '-1' - it kindof works perfectly except a tiny glitch 
- after the image is downloaded the patch seems to be off centred / displaced wierdly 
here is the test patch to demonstrate the issue https://cables.gl/edit/CuTYnV

**To Reproduce**
1. Go to this link https://cables.gl/p/CuTYnV (test patch)
2. Click anywhere in the patch
3. Press 's' on the keyboard 
4. Download or Cancel 
5. You can see the rectangle has shifted 
6. Resize the canvas/wiggle your browser - and everything becomes alright

**Expected behavior**
Step 5 shouldnt happen / not always possible to resize the canvas when using this op / the canvas shouldnt displace/resize while rendering out an image

**Screenshots**
![image](https://user-images.githubusercontent.com/86233755/149502074-bae9ed3c-2c38-473a-8b25-a3ac61dafcb3.png)
![image](https://user-images.githubusercontent.com/86233755/149502109-3525407e-34a7-424b-85d8-9650c053fc8f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Version 97.0.4692.71 (Official Build) (64-bit)

**Additional context** 
Video reproducing the above issue
https://user-images.githubusercontent.com/86233755/149502348-4b594fa4-18bc-4c6c-b32b-f0a275089e43.mp4

**Comment by steam0r** [comment]
hey,

sorry, we can't fix bugs in ops that you cloned and changed. but maybe this is what you are looking for?

https://cables.gl/op/Ops.Gl.SaveScreenShot_v2

best,
steam

**Comment by jaalibandar** [comment]
I updated the test patch to use the RenderAnim op - it has the same bug - I tried the Savescreenshot op as well earlier however it doesnt quite work as well ... attaching two references to show you the difference 

 the one on the left is with savescreenshot and the one on the right is with RenderAnim 
![image](https://user-images.githubusercontent.com/86233755/149570424-82c3c8e7-8c01-40ab-a74b-ca767e007bcd.png)
 
 I also tried to use the forcecanvassize op in combination with savescreenshot but it is basically resizes the entire patch render to a very high resolution which is pretty unnecessary and really makes everything slow - whereas renderanim actually works pretty nicely except for that small displacement thingy at the end which is resolved as soon as I wiggle the browser around like how you disconnect ops

**Comment by tastez** [comment]
@jaalibandar for your use case its best to use DownloadTexture of a higher res canvas in the background - the way renderanim works is not well suited for ytour use case since it is slow and uses the entire canvas to resize, it's best for set and forget workflow to render a bunch of images slowly.

With DownloadTexture op you can fire off screenshots in the right resolution after feeding it a texture with dimensions you need. We can take a look at it in a meetup if you need help but a tutorial would be nice, i'll think about it.

**Comment by steam0r** [comment]
hey, we created a small youtube tutorial on how to use DownloadTexture: https://www.youtube.com/watch?v=YFvVsEPirRc&t=1s
