### ISSUE TITLE
I can't upload my new profile picture in the cables site

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#12]
**Describe the bug**
Hi! I can't upload my new profile picture in the cables site, i tried several times jpg and png formats. It happends nothing after the upload message.

Windows 10
Chrome

**Comment by steam0r** [comment]
have put this in the cables backlog, will keep you updated. thanks for reporting!

**Comment by pandrr** [comment]
thanks, it's now fixed on dev

**Comment by n4hui** [comment]
thank you!

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
