### ISSUE TITLE
My profile page in cables don't apply video effects in my feature patch

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#13]
Hi! My profile page in cables don't apply video effects from my feature patch.

I can see the 3D stuff, but the video effects are not applied...

Windows 10
Chrome

https://cables.gl/user/n4hui

**Comment by dudumaluf** [comment]
Hi !
I think this is related to the canvas size. If i resize the window then I see some effects on top of the mesh.
Maybe check if some of the effects are beeing influenced by the texture size / resolution.

**Comment by n4hui** [comment]
> Hi !
> I think this is related to the canvas size. If i resize the window then I see some effects on top of the mesh.
> Maybe check if some of the effects are beeing influenced by the texture size / resolution.

Thank you very much, i'll check it!
