### ISSUE TITLE
Google Cardboard VR Support or similar

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#14]
Hi, i unfortunately see the cables vr support is currently unavailable, so i guess if it would be possible to have the google cardboard support in cables? Or other alternative? :)

**Comment by steam0r** [comment]
try this: https://cables.gl/docs/faq/vr_in_cables/vr_in_cables

**Comment by n4hui** [comment]
> try this: https://cables.gl/docs/faq/vr_in_cables/vr_in_cables

Ok
