### ISSUE TITLE
MediaRecorder, only renders MKV files

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#149]
Hi! Working with the MediaRecorder, after the last cables update, i change the mimetype of media to render, but always is making an mkv video after the recording stops... 

I am using the last version on Chrome on Windows11

thank you for your support in advance!

**Comment by steam0r** [comment]
hey,

it tries to find suitable codecs for your browser. is this on live after the update? can you provide a screenshot of what is being offered in the dropdown for selecting mimetypes? thanks!

best,
stephan

**Comment by steam0r** [comment]
hey,

there seems to be a bug where chrome ignores the wanted mimetype...can you check this in other browsers? 

https://stackoverflow.com/questions/64233494/mediarecorder-does-not-produce-a-valid-webm-file

sorry...

best,
stephan

**Comment by n4hui** [comment]
Yep, in firefox works fine 👌

**Comment by steam0r** [comment]
selecting this in chrome, gives me a webm:

![Bildschirmfoto 2022-02-14 um 16 04 17](https://user-images.githubusercontent.com/151271/153889208-5cd83fa8-7b69-4a5c-9666-d865d1d46cf6.png)

**Comment by n4hui** [comment]
It works to me too, i'll use that code in the case of chrome then 👍
