### ISSUE TITLE
GL UI - Tab key doesn't open the OP selection menu

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#15]
Hello,
Regular UI works by tapping on the Escape and Tab key.

Tab key is disabled on GL UI. (Tab key is the standard key for most node-based visual programming software).

**Comment by steam0r** [comment]
have put this in the cables backlog, will keep you updated. thanks for reporting!

**Comment by pandrr** [comment]
fixed on dev!

**Comment by steam0r** [comment]
this has been fixed on dev and will be in the next release
