### ISSUE TITLE
Op comments disappear behind areas

### ISSUE THREAD

**Issue by tob-har** [cables-gl/cables_docs#151]
**Describe the bug**
Comment texts of Ops disappear (behind?) area.

**To Reproduce**
1. Create an Op
2. Put comment in the Ops comment field
3. Create Area around that op
4. Now the comment text disappears, as long as the area covers the Op.

**Desktop (please complete the following information):**
 - OS: 10.14.6 MacOS
 - Browser Brave
 - Version [Version 1.35.100 Chromium: 98.0.4758.87 (Offizieller Build) (x86_64)](https://brave.com/latest/)

**Comment by steam0r** [comment]
screenshot for reference :)

![Bildschirmfoto 2022-02-18 um 11 53 32](https://user-images.githubusercontent.com/151271/154669429-8ff9cfcf-437d-4bf0-a725-db7f647281f2.png)

**Comment by pandrr** [comment]
thanks, fixed on dev.cables.gl
