### ISSUE TITLE
GltfTransformNode breaks

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#152]
I think the OP is old and access properties that don't exist in the mesh anymore.

l. 53
```
 vec3.set(origTrans, node._node.translation[0], node._node.translation[1], node._node.translation[2]);
```
It seems that now the Gltf node has the model matrix directly in its properties.

**Comment by pandrr** [comment]
thanks, fixed on dev.cables.gl !

**Comment by steam0r** [comment]
this went to cables.gl with the last release, thanks for reporting
