### ISSUE TITLE
GltfTexture Filter Bug...

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#153]
Hi! I was trying the Gltf Texture Op but there is a bug... 

I'm using a grass texture so i need to use the midmap filter to avoid noise.
I share to you an example patch, it contains this comment:

The filter selected is midmap, but it looks like nearest...
If i change it manually to midmap it works but is back again 
to nearest reloading the patch :/

https://cables.gl/p/620c0990cef9e411244c5b63?s=PxvvoSiwr5KLGzJg 

I use the latest version of Chrome on Windows11

**Comment by pandrr** [comment]
fixed! thx

**Comment by n4hui** [comment]
Hi! Thank you!

**Comment by steam0r** [comment]
this went to cables.gl with the last release, thanks for reporting
