### ISSUE TITLE
Can't write a decimal point when a value is changed to "Set animated" 

### ISSUE THREAD

**Issue by dino5711** [cables-gl/cables_docs#16]
**Describe the bug**
Can't write a decimal point when a value is changed to "Set animated" 

**To Reproduce**
1. Go to Value and change it to "set animated"
2. Type any number with a decimal point.
3. You can insert it by moving in between the numbers

**Expected behavior**
Being able to set values with decimal numbers

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 90

**Comment by steam0r** [comment]
have put this in the cables backlog, will keep you updated. thanks for reporting!

**Comment by pandrr** [comment]
thanks for reporting, fixed on dev now

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
