### ISSUE TITLE
Add User pseudo / name of the person when getting an invitation to collaborate

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#17]
When you get an email invitation you can't see who is inviting you. It would be nice to know who it is.

![Screenshot 2021-04-15 180519](https://user-images.githubusercontent.com/1793640/114901645-4c81aa00-9e15-11eb-8702-cc7336e3f770.png)

Cheers

**Comment by steam0r** [comment]
yeah, makes sense, moved it to the backlog, thank you!

**Comment by steam0r** [comment]
this is "fixed" on dev now

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
