### ISSUE TITLE
Mediapipe op links lead to 404 pages

### ISSUE THREAD

**Issue by positlabs** [cables-gl/cables_docs#176]
**Describe the bug**
Mediapipe op links lead to 404 pages

**To Reproduce**
Visit https://cables.gl/search?s=mediapipe&w=ops and click the op links. 

**Expected behavior**
Links should lead to op docs page 

**Screenshots**
<img width="1110" alt="Screen Shot 2022-02-24 at 4 31 54 PM" src="https://user-images.githubusercontent.com/1918844/155611142-4cb0d30c-855f-47e8-9879-ebd85ad1612f.png">
<img width="456" alt="Screen Shot 2022-02-24 at 4 31 59 PM" src="https://user-images.githubusercontent.com/1918844/155611209-33ab3d36-72e3-4aa9-9ac2-9ff06adc040b.png">

**Desktop (please complete the following information):**
 - Device: Macbook 
 - OS: OSX
 - Browser Chrome

**Comment by pandrr** [comment]
thanks, they should not be visible on cables.gl they are "dev" ops, still in development. feel free to try them on dev.cables.gl

**Comment by positlabs** [comment]
Very cool! I gave it a shot but I'm getting an error from the lib. https://github.com/google/mediapipe/issues/2346

Should I submit issues related to dev patches or would that be better off in the discussions/discord?
