### ISSUE TITLE
PickingMaterial Op limit of selected object

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#18]
Hi! As you can see in this example the picking material have a limit of selected objects, the top ones don't work, can you please increase this limit, in the discord meetup, you said the reason is because the color channel, so if this is the double, to me will be enuff :)

https://cables.gl/p/6078ab2dcd7972318133d930?s=7wJALJ0leIvt1K5y

Desktop/Chrome/Android

**Comment by steam0r** [comment]
thanks for reporting, have put this into the backlog and we will keep you updated

**Comment by n4hui** [comment]
thank you!

**Comment by steam0r** [comment]
this is now updated/fixed on dev, if there still is something wrong, please let us know. thanks!

**Comment by n4hui** [comment]
I works very good, my projet is done, thank you very much!

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
