### ISSUE TITLE
Media Recorder patch downloads empty file on page load

### ISSUE THREAD

**Issue by positlabs** [cables-gl/cables_docs#180]
**Describe the bug**
I get an empty webm file when the page loads. Somehow that is the correct file format, but when I use the toggle to record, it gives me an mkv.

**To Reproduce**
1. See the patch at https://cables.gl/p/621bb7041d37e1b50229c52e?s=QBIniDatKWepsTna
2. Notice file downloads on page load
3. Try using the toggle or press spacebar to create a recording.
4. Notice incorrect mkv format. 

**Expected behavior**
No initial download, and correct file type when I do make a recording. 

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 98.0.4758.109 

**Additional context**
As far as the initial download issue, it only happens when I connect the recorder patch input to a sidebar toggle, so I'm guessing the issue is probably there and not in the media recorder.

**Comment by pandrr** [comment]
hi,

please this problem is fixed on dev.cables.gl

please try it over there

**Comment by positlabs** [comment]
I connected a new instance of the media recorder patch, but the page won't reload after I did that, so I can't test it. 

<img width="1108" alt="Screen Shot 2022-02-28 at 3 59 47 PM" src="https://user-images.githubusercontent.com/1918844/156057807-d52f830e-cdee-46ce-aeb8-c900df2ee5fb.png">

Looks like some json is malformatted. 

<img width="689" alt="Screen Shot 2022-02-28 at 4 03 19 PM" src="https://user-images.githubusercontent.com/1918844/156058315-7a218f5b-f6bb-4ff3-8740-fe7a1fc76784.png">

**Comment by positlabs** [comment]
I did some more testing with that reduced test case and the issue is solved there after replacing with a new patch, so I'll close this out.
