### ISSUE TITLE
ParseArray bug when separator is whitespace

### ISSUE THREAD

**Issue by krisj** [cables-gl/cables_docs#19]
**Describe the bug**

I am observing this when the separator is set to whitespace

- ParseArray "trim" parameter seems to be not functioning.
- ParseArray always trims the end of the input string but not for the ConcatMulti as input
- ParseArray always seems to be adding an additional element at the start of the array

demo patch:
https://cables.gl/p/609144b9df54647a3f1c084a?s=dWrDsmPVV3oeP91k

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Brave
 - Version: latest stable

**Comment by steam0r** [comment]
this is fixed on dev

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
