### ISSUE TITLE
Cables documentation website has wrong background for code / wrong text color

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#193]
It's difficult to read. Basic text should be white I think or background white.

![image](https://user-images.githubusercontent.com/1793640/157656727-277e47e0-1c51-49ad-a64e-5e0590b3a3a8.png)

**Comment by steam0r** [comment]
updated on dev, have a look ;)

**Comment by steam0r** [comment]
this went to cables.gl with the last release, thanks for reporting
