### ISSUE TITLE
New AudioBufferPlayer (v2) breaks music when with TimeLineUI

### ISSUE THREAD

**Issue by dino5711** [cables-gl/cables_docs#2]
The new AudioBufferPlayer (v2) doesn't continue playing the music when using rewind via TimeLineUI (TimeLineControls).
You have to press pause before pressing rewind else the music stops/breaks. Also when scrapping through the TimeLine manually. 
![image](https://user-images.githubusercontent.com/51714036/107554037-ad062800-6bd5-11eb-8996-6c6fd302baed.png)

**Comment by steam0r** [comment]
have put this in the cables backlog, will keep you updated

**Comment by steam0r** [comment]
this has been fixed on dev and will be in the next release

**Comment by steam0r** [comment]
this now is available on "live"
