### ISSUE TITLE
ArrayShiftString

### ISSUE THREAD

**Issue by krisj** [cables-gl/cables_docs#20]
similar to ArrayPushString adding an element to the end of the array, The ArrayShiftString would add an element to the start of the string instead.

**Comment by steam0r** [comment]
that would be "unshift", right? 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/unshift

"shift" would remove the element

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/shift

**Comment by krisj** [comment]
@steam0r yes, sorry, my bad, but you are correct - that is what I meant ArrayShift/Unshift OPs would be nice:)

**Comment by steam0r** [comment]
this is available on dev now

**Comment by steam0r** [comment]
made it's way to live
