### ISSUE TITLE
Bricked project

### ISSUE THREAD

**Issue by positlabs** [cables-gl/cables_docs#201]
**Describe the bug**
I can't load this project any more due to a script error. Looks like misformatted json.

**To Reproduce**
1. Load https://cables.gl/edit/doOMXY
2. See error modal and console errors

**Expected behavior**
I hope that projects would load even if there is an error. 

**Screenshots**
![Screen Shot 2022-03-15 at 10 22 06 AM](https://user-images.githubusercontent.com/1918844/158399561-e3c735c4-3520-4f36-811e-b36e0623f107.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome 99.0.4844.51

**Additional context**
I don't really need any support on this project since I rebuilt it, but I wanted to flag the problem since it could be an issue for others.

**Comment by steam0r** [comment]
quickfix for this problem is to go back to an older version of the patch via patch-settings on the website, in your case that would be https://cables.gl/patch/doOMXY/settings#t=versions

**Comment by positlabs** [comment]
Nice! I didn't know how to get to those settings outside of the editor. I was mainly getting back to the project from the "my patches" quick nav. Might be nice to have a cog icon in that layout.

**Comment by steam0r** [comment]
i caught this error on dev, you patch opens again there. i am pretty sure it has to do with the customop being connected to the sidebar, will investigate. for now i guess your op does not initialize the values set on the ports before...maybe helps to recover the patch though...sorry...

**Comment by steam0r** [comment]
hey, the problem is about putting a video-file on the outport of the op. 

since it seems that the user should upload/select that file anyhow, you should be using 

https://dev.cables.local/op/Ops.Sidebar.LocalFileToDataUrl

i think this is what you want, right?

![Bildschirmfoto 2022-03-16 um 10 43 25](https://user-images.githubusercontent.com/151271/158561854-e86c81bd-8992-4b64-af99-ca53949f77e1.png)

**Comment by positlabs** [comment]
Yes exactly - that is the approach I took on the more recent version and it works nicely. 

I confirmed the error catching works so I can open the project again. Thanks for looking into it!
