### ISSUE TITLE
MeshInstancerFromTexture - Add UV TexCoordinates port

### ISSUE THREAD

**Issue by steam0r** [cables-gl/cables_docs#206]
### Discussed in https://github.com/cables-gl/cables_docs/discussions/197

<div type='discussions-op-text'>

<sup>Originally posted by **franckaubry** March 14, 2022</sup>
The MeshInstancer op has a UV coordinate port so that one f.ex. can use a sprite sheet to create a random cloud of textures.
Please add a similar utility/port to the MeshInstancerFromTexture op.

![image](https://user-images.githubusercontent.com/97125854/158183722-835ef30d-b984-44fa-a3ca-3d0f0a78358b.png)
</div>

**Comment by pandrr** [comment]
done!

**Comment by steam0r** [comment]
this made it's way to cables.gl with the recent release, thanks for reporting!
