### ISSUE TITLE
PerlinAreaDeform with calc normals

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables_docs#208]
### Discussed in https://github.com/cables-gl/cables_docs/discussions/205

<div type='discussions-op-text'>

<sup>Originally posted by **ikekou** March 18, 2022</sup>
Hello. This is my first post here.

Now, I have a question. It is about PerlinAreaDeform OP.

I have placed a Sphere and deformed it with PerlinAreaDeform. I am placing one light.

When I turn on Calc Normals, the direction that the light is hitting is reversed. If I had to guess, I would say that maybe the Normals are reversed? I don't know.

I want the light to shine from the right direction. Please let me know if you have any solutions.

https://cables.gl/p/6I7ZYX

<img width="1200" alt="Screen_Shot_2022-02-16_at_16 24 59" src="https://user-images.githubusercontent.com/458137/158909606-b9a44674-5112-435e-aa6e-f22709ebe94c.png">

<img width="1198" alt="Screen_Shot_2022-02-16_at_16 25 11" src="https://user-images.githubusercontent.com/458137/158909616-81e25b24-d7b6-4c47-879d-8e2d568d31ff.png">

</div>

**Comment by pandrr** [comment]
thanks,

fixed on dev.cables.gl: there is not a toggle to flip normals, because of some inconsistencies with material ops, you can now easily flip them

**Comment by steam0r** [comment]
this went to cables.gl with the last release, thanks for reporting
