### ISSUE TITLE
Points Material doesn't take the Alpha value set in PointcloudFromArray 

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#21]
The original shader only took a vec3 for color and ignored the alpha value.

Here is an updated shader that works as expected.

https://cables.gl/edit/JouYVv

**Comment by steam0r** [comment]
this is done on dev, right? i think i merged your code. has anything changed?

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
