### ISSUE TITLE
Fog_v3 view example link is broken

### ISSUE THREAD

**Issue by basscadet** [cables-gl/cables_docs#213]
**Describe the bug**
The view example of Fog_v3 is broken and points to a 404 error page.

**To Reproduce**
1. Add a Ops.Gl.TextureEffects.Fog_v3 instance
2. Click on 'view_example'
3. See error

**Expected behavior**
An example of https://cables.gl/view/L6GbDe should open.

**Comment by steam0r** [comment]
this should be properly linked now, thanks for the hint!
