### ISSUE TITLE
Attachment file naming conventions

### ISSUE THREAD

**Issue by positlabs** [cables-gl/cables_docs#214]
**Describe the bug**
Attachments don't work if the file names include dashes or other characters that don't work as json keys

**To Reproduce**
1. Create a new user op
2. Create an attachment that uses a "-" in the file name
3. IDE says there is an error, suggests reloading
4. Patch is gone and uneditable

**Expected behavior**
Attachment names shouldn't break the patch when using unsupported json key strings

**Screenshots**
<img width="600" alt="Screen Shot 2022-03-30 at 3 54 18 PM" src="https://user-images.githubusercontent.com/1918844/160919848-56882b72-f647-457b-b256-17e4b2af9427.png">
<img width="861" alt="Screen Shot 2022-03-30 at 4 00 15 PM" src="https://user-images.githubusercontent.com/1918844/160920750-baf541ad-8968-4d31-87b3-5b266fdbb110.png">

**Desktop (please complete the following information):**
 - OSX, Chrome latest

**Additional context**
A simple solution would be to surround the json keys in quotes. If the naming conventions need to be in JS variable format, then the attachment inputs should probably be validated or sanitized.

In general I've had this issues with making user ops before. It will bug out because of some typo or something, then it becomes unrecoverable as far as I can tell. Is there a workaround for this?

**Comment by positlabs** [comment]
Oh, this bug is much worse than I though. I get this error even in a new project, and I can't access any of my user ops any more.

<img width="492" alt="Screen Shot 2022-03-30 at 4 26 46 PM" src="https://user-images.githubusercontent.com/1918844/160924936-25d88322-ae3f-487f-9be1-c52e15186231.png">

https://cables.gl/p/6244bd63369187b4187db23f?s=awQ1ExTClTLZjSbS

**Comment by pandrr** [comment]
fixed

**Comment by positlabs** [comment]
Confirmed, thanks!
