### ISSUE TITLE
Experimental GL View - op flies off screen or doesn't move

### ISSUE THREAD

**Issue by tastez** [cables-gl/cables_docs#22]
**Describe the bug**
dragging an op and letting go of the mouse button can sometimes lead to it fly away the next time you move it, or not moving at all, or moving in a weird offset from the mouse pointer (as captured in  attached gif).

**To Reproduce**
1. create 2 ops
2. click and drag one op and let go of the mouse over the other op
3. try to move the second or the first op
4. Sometimes one of the ops wont move when dragging, or fly away.

**Expected behavior**
release ops over other elements without bug

**Screenshots**
![gl_drag](https://user-images.githubusercontent.com/78642112/119117572-a59eb800-ba29-11eb-8b2a-55edc9ecc411.gif)

![gl_drag_nice](https://user-images.githubusercontent.com/78642112/119118764-d6cbb800-ba2a-11eb-99bd-5c253d4c6bfe.gif)

**Desktop (please complete the following information):**
 - OS:  Microsoft Windows 10 Pro , Version 10.0.19041 Build 19041
 - Browser:  Microsoft Edge
 - Version: Version 90.0.818.62 (Official build) (64-bit)

**Comment by pandrr** [comment]
oh wow thank you for explaining how to reproduce

**Comment by pandrr** [comment]
first one is fixed, second one i really can't repdoduce. please test again on dev

**Comment by tastez** [comment]
currently testing and suspecting that snap to grid is affecting the picking/dragging.
![nosnap](https://user-images.githubusercontent.com/78642112/121875828-2ee39a80-cd09-11eb-936a-4042c68e360d.gif)
no exact way to reproduce yet, but this seems related so far

**Comment by tastez** [comment]
i've been able to reproduce it consistently in Chrome now - it seems to be the center of the editor canvas and the OP snap alignment to the center middle line.
Hope the gif explains it better - 
![flying](https://user-images.githubusercontent.com/78642112/122186782-ac84e300-ce8e-11eb-9cde-f4310021f05c.gif)

**Comment by pandrr** [comment]
fixed yay

**Comment by tastez** [comment]
sweet! thank you
