### ISSUE TITLE
Drag Mouse out of Inspector - Inspector looses focus

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#223]
Drag Mouse out of Inspector - Inspector looses focus
happens not only in text field but also dragging values  

**To Reproduce**

![selectTextBug](https://user-images.githubusercontent.com/1138673/162910544-84b630ee-ae78-44dd-8f2d-7feecf32e680.gif)

**Comment by pandrr** [comment]
thx, fixed on dev.cables.gl

**Comment by steam0r** [comment]
this went to cables.gl with the last release, thanks for reporting
