### ISSUE TITLE
ScaleByNormal combined with Shadows = 6fps

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#228]
**Describe the bug**
When i use ScaleByNormal in combination with shadows, cables runs super slow

I invited pandur to the demo patch Walking City ScalebyNormal Bug

![image](https://user-images.githubusercontent.com/1138673/164440072-1a3ec6a5-d862-472b-a38d-a1aafd884d51.png)

**Comment by tastez** [comment]
invited you to a quick rewrite, think it was just an old old op

**Comment by wirmachenbunt** [comment]
nice one, so it was easy to fix  ? thank you very much :)

**Comment by wirmachenbunt** [comment]
is there any way to use your fixed version. i can't clone the op, copy pasting the code into a new op didn't work because the vertex shader is missing (i guess). when i inspect the vert shader attached to your op, its empty.  i guess there is still no way to share ops ?

**Comment by tastez** [comment]
its fixed on live now - i think just update your patch's op
