### ISSUE TITLE
GLTF Structure View opens when switching Normals/Vertices Format in OP settings

### ISSUE THREAD

**Issue by tastez** [cables-gl/cables_docs#23]
**Describe the bug**
After opening Structure View to see nodes of a GltfScene OP and closing it, changing the Normals/Vertices Format settings in the op will reopen it again

**To Reproduce**
1. create GltfScene OP with a gltf file
2. Click Show Structure in the GltfScene OP settings
3. Close the Structure view by pressing X in the pop over (not the minimize arrow)
4. Toggle Normals Format from/to XYZ to X-ZY or Vertices Format, some other toggle options seem to open it too 
5. Structure View opens again

**Expected behavior**
Structure View only opens via open Structure View button after it has been closed by pressing X.

**Screenshots**
![structureview](https://user-images.githubusercontent.com/78642112/119120781-fa8ffd80-ba2c-11eb-97f8-9bf0d0e03131.gif)

**Desktop (please complete the following information):**
 - OS:  Microsoft Windows 10 Pro , Version 10.0.19041 Build 19041
 - Browser:  Microsoft Edge
 - Version: Version 90.0.818.62 (Official build) (64-bit)

**Comment by pandrr** [comment]
should be fixed on dev.cables.gl
