### ISSUE TITLE
weird .glb behavior on large models in chrome.

### ISSUE THREAD

**Issue by marioepsley** [cables-gl/cables_docs#236]
I've created a model viewer app. I can't reproduce the bug myself but some people have had a problem where they upload a .glb file and it looks like this.

<img width="1221" alt="Screenshot 2022-05-11 at 13 00 27 (1)" src="https://user-images.githubusercontent.com/36418408/167850835-8febc40e-889a-4345-ade3-22accedf7ba5.png">

What's funny is it has worked fine for them for a while then one day they start uploading them and they go like this. From then on they always load like this.
It's happened for a few people now.
I've tried trouble shooting myself and have got them to clear all browser settings, tried it in cables, tried it hosted, tried it on dev, nothing changes.

Here's their browser details, everyone is using chrome on mac.
https://cables.gl/browser/r/627bab29506034b3dbbf039e
and
https://cables.gl/browser/r/627bae027d80f1b3d9439b4a

I've invited Pandur and Stephan to the patch called 'Xeros-F3'

I have just noticed when uploading a smaller .glb (under5mb) it uploads fine, but when uploading say a 70mb or 120mb .glb it goes like this.
here's an example of one of the .glbs
https://we.tl/t-nNA5N6ubVe
Just to mention bigger files were uploaded and played fine for these people, now they don't which is very bizarre. 
Never been a problem for me (https://cables.gl/browser/r/627bb1834ca97bb437e364c8)

one time someone updated their OS and it worked for a bit, then it went back to this weird behavior.
I am aware these models are large but this is what I'm working with.

Hope this is enough info
Keepitvisual

**Comment by marioepsley** [comment]
here are two of the specs of the computers it's happening too. Will post the other two tomorrow.

<img width="1106" alt="Screenshot 2022-05-11 at 20 21 39" src="https://user-images.githubusercontent.com/36418408/167929325-e69825f4-6138-4bea-848d-4a6857fe86ab.png">
<img width="1146" alt="Screenshot 2022-05-11 at 20 21 15" src="https://user-images.githubusercontent.com/36418408/167929337-6058bebf-103d-43c5-bfd9-c271cd3aa169.png">

**Comment by steam0r** [comment]
hey, you are testing all of this on cables.gl and not dev.cables.gl, right? also a common thing seems to be that these are all AMD 5300M, is there any other changes made since "the other day"? browser versions, changes in how the model got created or is there some error in the developers console once it fails? 

my firefox on m1 does not allow the upload of the given file at all, chrome works fine on my m1...

**Comment by marioepsley** [comment]
Hey Steam, I've tested both on cables and dev.cables. No browser changes, happy for everyone that wants to use it uses chrome. All the models are getting created in exactly the same way so no change there. Just heard back from the other two people that were having problems and it seems they're also both on a 2019 macbook with the AMD 5300M chip. regarding the console I'm not 100% sure I'm looking in the right place but I see no errors popping up. My thoughts are now its this AMD 5300M chip...

**Comment by tastez** [comment]
testing it here, heres my browser info
https://cables.gl/browser/r/627cd8bf4ca97bb437e369d5
<img width="514" alt="image" src="https://user-images.githubusercontent.com/78642112/168044242-297d05b4-5b15-400e-b7aa-fe007369f669.png">
also totally messed model 
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/78642112/168045068-82b1ea52-b62a-4d00-b218-605be0b5e51a.png">

**Comment by tastez** [comment]
i tried a simple setup with my own patch, just data url to glb and it worked fine.
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/78642112/168047537-0672710b-e455-4512-a251-ea978cd8b692.png">

maybe there is something corrupting the display/too heavy for the gpu in your patch @marioepsley

**Comment by pandrr** [comment]
please try again on dev.cables.gl, i reworked the handling of meshes >64k faces

**Comment by marioepsley** [comment]
> 

Sadly it's still not working. 
I exported the project from dev and uploaded it to my server. Getting similar screenshots back. Can't test within cables unfortunately as I'm not with anyone atm.

**Comment by marioepsley** [comment]
One person has now said it works for them :) tobecontinued.

**Comment by pandrr** [comment]
tell them to clear the cache :)

**Comment by marioepsley** [comment]
still not working for that person... odd
