### ISSUE TITLE
allow color coding a single op

### ISSUE THREAD

**Issue by tastez** [cables-gl/cables_docs#24]
currently you can drag select multiple ops and change their color to organize a patch, drag selecting a single op and being able to change its color code would be nice too.

**Comment by tastez** [comment]
seems to work in dev!

**Comment by tastez** [comment]
Correction - this is an issue in GL view even on dev at the moment

**Comment by pandrr** [comment]
there is now a color selection under the comment input area in the op parameter panel

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
