### ISSUE TITLE
Toggle fullscreen timeline splitter css issue

### ISSUE THREAD

**Issue by constructor** [cables-gl/cables_docs#240]
**Describe the bug**
In the Cables editor, clicking 'maximise canvas' will fill the screen with the canvas render as expected, but '#splitterTimeline' remains visible on top of the canvas.

**To Reproduce**
1. Go to Cables editor with any scene rendering
2. Click on 'maximise canvas' in the 'canvasIconBar'
3. See error

**Expected behavior**
Fullscreen rendering of canvas should not have '#splitterTimeline' overlayed, it should be clear.

**Screenshots**
![SplitterTimelineBug](https://user-images.githubusercontent.com/176053/168264816-e5f3bb00-10f2-45ea-a8da-29768ffe11f0.png)

**Desktop (please complete the following information):**
 - OS: Windows Version 10.0.19044 Build 19044
 - Browser: Chrome
 - Version 101.0.4951.64 (Official Build) (64-bit)

**Comment by steam0r** [comment]
hey, thanks for the report, i quickly fixed this on dev.cables.gl

**Comment by constructor** [comment]
Awesome response time. This is some project. Awsome.

**Comment by steam0r** [comment]
proper report combined with easy fix ;)
