### ISSUE TITLE
Preset op not saving custom port names

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#250]
When i set my own port names in the preset op inspector, on reload the names are gone.

![image](https://user-images.githubusercontent.com/1138673/170663966-03bd27ab-c5a4-4962-9cf2-43b4a798dea7.png)

not sure if this is user error or a bug.

**Comment by steam0r** [comment]
this is fixed on dev.cables.gl i think, was reported/discussed here as well: #73

**Comment by wirmachenbunt** [comment]
ooops, sorry for bringing it up again

**Comment by steam0r** [comment]
no problem :)
