### ISSUE TITLE
LottieTexturePlayer dark edges

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#258]
LottieTexturePlayer shows dark edges in some case, caused be interpreting alpha the wrong way (i guess)

![image](https://user-images.githubusercontent.com/1138673/171636980-82efce81-26f1-4a89-863a-02b4a0035176.png)

Setting the blendmode to premultiplied, fixes the problem.

Either the helppatch gets updated with the blendmode op or premultiplied is added to the LottieTexturePlayer

![image](https://user-images.githubusercontent.com/1138673/171636849-3166eef3-541a-4254-bf3e-6b9b7c92172c.png)

**Comment by pandrr** [comment]
updated the example
