### ISSUE TITLE
Broken VideoTexture op

### ISSUE THREAD

**Issue by positlabs** [cables-gl/cables_docs#267]
**Describe the bug**

Video texture is broken due to a bad ref to cgl. 

`if (flip.get()) this._cgl.gl.pixelStorei(this._cgl.gl.UNPACK_FLIP_Y_WEBGL, false);`

Ref should be updated from `this._cgl` to `cgl`

**To Reproduce**
1. Go to https://cables.gl/p/62a0b4c605a6bcf659c7ea43?s=OTAQwqlEHQVw7qCL
2. Click the file chooser, pick a file
3. Notice crash dialog, open devtools console

**Expected behavior**
Video texture should display a texture

**Screenshots**
<img width="1133" alt="Screen Shot 2022-06-08 at 9 48 39 AM" src="https://user-images.githubusercontent.com/1918844/172647045-37ba2c62-4422-4eee-b3b1-1c73b2e8e3de.png">

**Comment by steam0r** [comment]
this went to cables.gl with the last release, thanks for reporting
