### ISSUE TITLE
Values entered into a subpatch are lost on page reload

### ISSUE THREAD

**Issue by constructor** [cables-gl/cables_docs#272]
**Describe the bug**
After creating a subpatch, any values that are entered into the subpatch are lost on reload.

**To Reproduce**
1. Create a 'Number' operator
2. Highlight it and create a new subpatch
3. Enter into the subpatch context and wire up the number value to the 'PatchInput'
4. Go back to the 'Main' patch edit view and enter a value into the subpatch
5. Save the patch
6. Reload the editor (refresh page)
7. The value previously entered is no longer visible

**Expected behavior**
Values entered into the subpatch directly should persist without the need of explicitly adding another operator to push value into the subpatch.

**Desktop (please complete the following information):**
Google Chrome Version 102.0.5005.63 (Official Build) (64-bit)
Edition	Windows 10 Pro
Version	21H2
OS build	19044.1706
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by steam0r** [comment]
hey, thanks for reporint this is a very understandable manner. we will look into it, but also have to make sure to not break any patches that "rely" on this bug...

**Comment by constructor** [comment]
> hey, thanks for reporint this is a very understandable manner. we will look into it, but also have to make sure to not break any patches that "rely" on this bug...

I understand. But I do think that assigning a value to a subpatch is something fundamental that should work. It seems superfluous to require the addition of a node to simply add a static value.

**Comment by constructor** [comment]
Outstanding! Thanks for all your hard work.
