### ISSUE TITLE
Canvas Settings not accessible when using HTML elements

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#281]
![image](https://user-images.githubusercontent.com/1138673/174994415-c6dbfd47-0f5d-4b3c-8d70-c72b5878bcd7.png)

this menu is often not reachable when using divElements (ie. with Lottie) , the div elements in the patch prevent the click somehow. maybe introduce a dedicated button for this or put it underneath the canvas window ?

**Comment by steam0r** [comment]
some of these can be reached by using the "command pallette" (as a quick workaround).

![Bildschirmfoto 2022-06-22 um 11 55 01](https://user-images.githubusercontent.com/151271/175000849-e6edb245-9d7d-4e52-b758-aba19709d6c9.png)

**Comment by pandrr** [comment]
maybe `#glcanvas{overflow:hidden;}` cuts them off ?
can you try or provide an example 

then we will put it in

**Comment by wirmachenbunt** [comment]
https://cables.gl/p/6hkcb6

here we go.

**Comment by pandrr** [comment]
ah now i understand.
it currently only shows up  after clicking on the canvas.
you have to set pointer-events:none to all elements to let clicks through.

**Comment by wirmachenbunt** [comment]
ok, thanks for the hint
maybe add this to the div related help patches ? 
like the lottie div ?

**Comment by pandrr** [comment]
its not really cables related stuff, its html in general

**Comment by pandrr** [comment]
i mean, we probably can find a workaround to show the canvasinfo panel thing when you click in that area by comparing pixel coordinates, but yeah

**Comment by wirmachenbunt** [comment]
> feel free to add it to the docs :)

what do you mean? add to what docs ?
