### ISSUE TITLE
Changing Copyright before saving patch, erases unsaved description

### ISSUE THREAD

**Issue by tastez** [cables-gl/cables_docs#29]
**Describe the bug**
When saving a patch and changing the copyright option, patch will update and reset all fields that were unsaved

**To Reproduce**
1. Go to your patch
2. Click on patch settings and enter description 
3. Scroll down to copyright option selection
4. set option via radio button and watch description reset

**Expected behavior**
perhaps saving the fields along with the copyright selection is better than resetting them all - or lengthier - a warning that doesnt allow copyright selection before patch is saved (uh)

**Desktop (please complete the following information):**
 - OS: win64
 - Browser Edge
 - Version 91.0.864.41 (Official build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by steam0r** [comment]
this is fixed on dev

**Comment by steam0r** [comment]
made it's way to live
