### ISSUE TITLE
blue dot in top left corner - gizmo ?

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#291]
When starting a new patch, i often see a blue dot in the top left corner, dev tools tells me its a gizmo. where is this coming from. is this meant to be like this ?

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/1138673/178266659-fd2b1b33-6206-48c8-9b7a-2da762cdd700.png">

**Comment by steam0r** [comment]
i think this is fixed on dev, would be nice if you could doublecheck. thanks!

**Comment by steam0r** [comment]
this made it's way to cables.gl with the recent release, thanks for reporting!
