### ISSUE TITLE
Can't open OP attachments

### ISSUE THREAD

**Issue by dino5711** [cables-gl/cables_docs#3]
**Describe the bug**
Can't open OP attachments.

**To Reproduce**
1. Find an OP with Attachments
2. Click on Filename e.g. basicmaterial.frag
3. See the cables logo turn into a circle for 0.5 seconds
4. Nothing happens

**Expected behavior**
Opens the text editor and displays attached shader

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: latest Chrome

**Comment by steam0r** [comment]
have put this in the cables backlog, will keep you updated. thanks for reporting!

**Comment by steam0r** [comment]
this has been fixed on dev and will be in the next release

**Comment by steam0r** [comment]
this now is available on "live"
