### ISSUE TITLE
SamplerCube support for CustomShader OP

### ISSUE THREAD

**Issue by tastez** [cables-gl/cables_docs#30]
While experimenting with some of the cubemap based shadertoys (https://www.shadertoy.com/view/tdjBR1) I ran into a challenge where CustomShader OP doesn't generate a cubemap texture output and input when using UNI samplerCube ... .

**note: docs do mention cubemap as a shadertoy input type and only sampler2d as a cables type https://cables.gl/docs/faq/shadertoy/shadertoy

**Comment by pandrr** [comment]
added cube map support on dev

**Comment by tastez** [comment]
cubemap inputs work! Excellent
tried it with EquilateralTextureToCubemap OP and included equilateral textures from library.

Also tried it with cubemapfromtextures and found some issues for another time.

I guess for cubemap from CustomShader there would need to be a Shader2Cubemap OP.

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
