### ISSUE TITLE
LoadingStatus doesn't prevent Timeline from automatically playing anymore.

### ISSUE THREAD

**Issue by basscadet** [cables-gl/cables_docs#307]
**Describe the bug**
Ops.Patch.LoadingStatus used to be able to prevent the Timeline from automatically playing when opening the patch if you unchecked the "Play Timeline" input field and there are assets to be loaded. However, the new Ops.Patch.LoadingStatus_v2 doesn't implement the same behaviour. I assume this is not the intended behaviour. It seems to work the same way in both dev and production. The old behaviour adds essential usability for creating demos since the timeline isn't intended to run before hitting play manually because with current browsers the audio context will be suspended before hitting the play button or the unmute button in the lower right hand corner. If the user clicks the latter the audio and video will be out of sync.

**To Reproduce**
1. Upload or drag and drop a file from the files panel.
2. Create MainLoop -> LoadingStatus and uncheck "Play Timeline" from LoadingStatus.
3. Save and reload the patch.
4. The timeline starts playing with Ops.Patch.LoadingStatus_v2 but doesn't on Ops.Patch.LoadingStatus.

**Screenshots**
<img width="296" alt="loadingstatus" src="https://user-images.githubusercontent.com/16443410/181845050-817640d1-4d16-4f67-a136-e170677662bb.png">

**Desktop**
 - OS: MacOS Catalina 10.15.7, Debian GNU/Linux
 - Browser: Chrome and Safari
 - Version: Chrome 103.0.5060.134

**Smartphone**
 - Device: Iphone 13 Pro
 - OS: iOS15.5
 - Browser: safari
 - Version: 15.5

**Comment by steam0r** [comment]
you solved this with a gatetrigger, right?

**Comment by pandrr** [comment]
https://cables.gl/p/C0ZBZ9

this patch should work corrently

currently a few ops controll the timeline and overwrite each other, which is a problem and we need to rework a few ops for this, so it needs to be patched.
