### ISSUE TITLE
Experimental GL View - mouse over on a cable will not hide last observed value

### ISSUE THREAD

**Issue by tastez** [cables-gl/cables_docs#31]
**Describe the bug**
probably known - 
Mouse overing a cable will show a circle and a value number beside it, moving mouse away will make the "create op on cable" circle disappear but the number will stick at the last observed value.
Secondly, deleting connected ops that you were previously observing, will not reset selection, so mouse over on another connection will not show value until you select an op and drop the selection.

**To Reproduce**
1. Switch to GL view in editor
2. Create 2 connected OPs
3. Mouse over their cable connection to observe the passed value (easier with non triggers)
4. Move mouse away from cable and observe left over number value left on editor background.

second variation
1. while in GL view in editor, create 2 separate pairs of connected OPs.
2. Observe passed value on a cable connecting one of the pairs.
3. delete the OPs
4. observe value left over on editor background
5. mouse over the cable connecting the second pair of OPs
6. No value will be shown over the cable
7. select and deselect an OP
8. observe value.

**Expected behavior**
Moving mouse away from cable will hide observed value.

**Screenshots**
![cablemouseover](https://user-images.githubusercontent.com/78642112/121879847-969be480-cd0d-11eb-8e30-2d61798af3f8.gif)

**Desktop (please complete the following information):**
- OS: Microsoft Windows 10 Pro , Version 10.0.19041 Build 19041
- Browser: Microsoft Edge
- Version: Version 91.0.864.48 (Official build) (64-bit)

**Additional context**
second issue should not be a problem after the main is addressed.

**Comment by pandrr** [comment]
value overlay is hidden for now, was just a quick test, will make it optional and more advanced/better in the future

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
