### ISSUE TITLE
Sidebar won't accept initial value

### ISSUE THREAD

**Issue by mickeyvanolst** [cables-gl/cables_docs#317]
The sidebar doesn't seem to receive input values, even if you manually trigger the "set default" button it stays.

In this example you can see the value going into the input is False though the sidebar stays stuck on True.

https://cables.gl/edit/i1NLHa#/circle

**Comment by steam0r** [comment]
this is fixed on dev.cables.gl, please let me know if it works for you since i might not have understood what you did with the triggeronce there :)

**Comment by steam0r** [comment]
this made it's way to cables.gl with the recent release, thanks for reporting!
