### ISSUE TITLE
Experimental GL view - OP port info popover does not disappear after deleting OP

### ISSUE THREAD

**Issue by tastez** [cables-gl/cables_docs#32]
**Describe the bug**
Mouse overing an OP's port will show an info text popover, deleting the OP will leave the popover in the editor view until another OP's port is mouse overed.

**To Reproduce**
1. Create OP in GL View and make sure it is selected
2. Mouse over a port on the OP and observe info popover
3. Delete the OP
4. See popover left in the editor

**Expected behavior**
deleting OP will hide popover text

**Screenshots**
![portpopover](https://user-images.githubusercontent.com/78642112/121880696-9a7c3680-cd0e-11eb-8b2f-4c2773f56eee.gif)

**Desktop (please complete the following information):**
- OS: Microsoft Windows 10 Pro , Version 10.0.19041 Build 19041
- Browser: Microsoft Edge
- Version: Version 91.0.864.48 (Official build) (64-bit)

**Comment by pandrr** [comment]
thanks! fixed on dev

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
