### ISSUE TITLE
Cloned op within team patch not editable by other team members/collaborators

### ISSUE THREAD

**Issue by anticore** [cables-gl/cables_docs#321]
**Describe the bug**
I have cloned the GltfScene op within a team patch, and also added the other team member as a collaborator.
The other team member cannot edit the cloned op code, only I can.

**To Reproduce**
1. Create a patch
2. Assign it to the team
3. Add other person as collaborator
4. Clone an op
5. Other person cannot edit cloned op code

**Expected behavior**
Team members/patch collaborators need to be able to edit the cloned op code in order to collaborate on this part of the project

**Screen recording**
[Here's a screen recording of the issue (streamable)](https://streamable.com/oxdr9i)

**Comment by steam0r** [comment]
hm, yeah, there currently is no way around it, but we have plans to make this better somehow. you might be able to move to CustomOp instead of a user-op, that would then be editable by everyone with write-permission to the patch (collaborators).

**Comment by steam0r** [comment]
this is now possible, very finegrained with the last release, see this part of the documentation:

https://cables.gl/docs/5_1_permissions/3_ops/ops

(basically create a team op, people with full-access to the team will be able to edit it. or create a patch op and people with full access to the patch will be able to edit it)
