### ISSUE TITLE
MeshInstancerFromTexture WebGL errors

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#328]
It seems that MeshInstancerFromTexture yields many webGl warnings and errors, even in the basic example.

https://dev.cables.gl/edit/H3cEpX

<img width="491" alt="Screenshot 2022-08-27 152247" src="https://user-images.githubusercontent.com/1793640/187032155-cc0167bd-7e1b-4919-9e10-d6307ffb6fc5.png">

I could pintpoint to cgl_mesh.js  "unbind" method for the warning, but not the error.

Thanks

**Comment by pandrr** [comment]
fixed the 256 gl warnings from meshInstancerFromTexture, the others are actually from the cables patchfield ui and will be fixed in the future :>

**Comment by steam0r** [comment]
this made it's way to cables.gl with the recent release, thanks for reporting!
