### ISSUE TITLE
Change license of Cannon.js to MIT

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#335]
When exporting a patch, Cannon.js is listed as public domain whereas their Github is MIT.
https://github.com/schteppe/cannon.js/blob/master/LICENSE

**Comment by steam0r** [comment]
fixed on dev.cables.gl, thanks for the hint!

**Comment by steam0r** [comment]
this made it's way to cables.gl with the recent release, thanks for reporting!
