### ISSUE TITLE
Blueprints op.onLoaded has a different behavior than from a regular subpatch

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#336]
In an OP included in a blueprint the trigger of `op.onLoaded` is different from a regular subpatch on the same patch.

**Comment by steam0r** [comment]
can you clarify this a bit more? example patch, expected vs actual behaviour? what does "different" mean?

**Comment by steam0r** [comment]
after talking this seems to be related to copypasting blueprints that were created of subpatches that were "weirdly creaed" (adding patchinput manually after deleting the old one), keeping an eye on it...
