### ISSUE TITLE
Experimental GL view - nonnative cursor floats under the OPs

### ISSUE THREAD

**Issue by tastez** [cables-gl/cables_docs#34]
**Describe the bug**
probably known, or browser issue here
Enabling non native cursor in GL Editor view, will change mouse cursor but it floats under the ops

**To Reproduce**
1. Go to editor options and enable GL view and nonnative cursor
2. reload editor if needed
3. observe cursor floating under OPs

**Expected behavior**
Cursor is ontop of ops

**Screenshots**
![nonnativecursor](https://user-images.githubusercontent.com/78642112/121885621-a79c2400-cd14-11eb-8930-95c443e8e0d1.gif)

**Desktop (please complete the following information):**
- OS: Microsoft Windows 10 Pro , Version 10.0.19041 Build 19041
- Browser: Microsoft Edge
- Version: Version 91.0.864.48 (Official build) (64-bit)

**Comment by pandrr** [comment]
thx, fixed

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
