### ISSUE TITLE
GlRectInstancer throws warning [cgl_mesh] vertIndices float32Array: mesh rectinstancer

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#347]
Glrectinstancer.js l 75 throws a warning

```
this._geom.verticesIndices = new Float32Array([2, 1, 0, 3, 1, 2]);
```

From the warning message, vertex indices should be a `new Uint16Array`.
See cgl_mesh.js l 397.

**Comment by pandrr** [comment]
ahhh right, thx!
fixed on dev.cables.gl
