### ISSUE TITLE
Warning [cgl_mesh] vertIndices float32Array: mesh fullscreen rectangle for HelperMeshes

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#348]
Same issue as before, using a Float32Array for vertex indices instead of Uint16.

In cgl_helpermeshes.js
l 507

```
fsGeom.verticesIndices = new Float32Array([  // to change
    0, 1, 2,
    3, 1, 2,
]);
```

**Comment by pandrr** [comment]
thanks, fixed

**Comment by steam0r** [comment]
this made it's way to cables.gl with the recent release, thanks for reporting!
