### ISSUE TITLE
Editor - default size of editor view split doesn't show colors selection

### ISSUE THREAD

**Issue by tastez** [cables-gl/cables_docs#35]
**Describe the bug**
The default editor split size makes the right hand side a single column. In this sidebar size, selecting multiple ops will show the color options correctly.
(possibly browser/resolution related)

**To Reproduce**
1. Create new patch or resize current patch editor split to cause the right hand options to be displayed as a single column
2. Select multiple OPs
3. Observe absence of color selection squares

**Expected behavior**
Colors are displayed when ops are drag selected and right hand editor side is single column

**Screenshots**
![colorssinglecolumn](https://user-images.githubusercontent.com/78642112/121888495-5d1ca680-cd18-11eb-9e0c-01330d6411e2.gif)

**Desktop (please complete the following information):**
- OS: Microsoft Windows 10 Pro , Version 10.0.19041 Build 19041
- Browser: Microsoft Edge
- Version: Version 91.0.864.48 (Official build) (64-bit)

**2nd issue**
as observed in the attached gif, the drag selection options disappear once sidebar is resized and the selection has to be made again - dont know if this is worth bugging at the moment

**Comment by tastez** [comment]
this doesn't happen on DEV

**Comment by pandrr** [comment]
fixed already

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
