### ISSUE TITLE
Experimental GL View - creating multiple new ops with keyboard only will stack them on top of each other

### ISSUE THREAD

**Issue by tastez** [cables-gl/cables_docs#36]
**Describe the bug**
If you create multiple ops from the OP menu without moving the mouse or clicking on the editor screen, each new OP will be created ontop of the previous one - unlike usual behavior where they are offset below the first OP.

**To Reproduce**
1. Go to GL view editor
2. open OP create/search window by pressing escape
3. don't touch the mouse
4. Add OP by searching for it and pressing enter on the keyboard
5. open OP create/search window without moving or clicking on editor canvas
6. Add OP by searching for it and pressing enter on the keyboard
7. see OPs stacked ontop of each other

**Expected behavior**
new OPs are not stacked on previously created OPs

**Screenshots**
![keyboardonly](https://user-images.githubusercontent.com/78642112/122188990-d0492880-ce90-11eb-8bf5-adfe2198b0d2.gif)

**Desktop (please complete the following information):**
- OS: Microsoft Windows 10 Pro , Version 10.0.19041 Build 19041
- Browser: Microsoft Edge
- Version: Version 91.0.864.48 (Official build) (64-bit)

**Smartphone (please complete the following information):**

**Comment by pandrr** [comment]
fixed

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
