### ISSUE TITLE
Minify tersify export ops.js and patch

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#364]
Using [Terser](https://github.com/terser/terser) we could maybe minify, compress patch and ops library to reduce the JS size and "secure" the code.

What do you think?

**Comment by pandrr** [comment]
oh yeah interesting...
we were looking for something new anyhow because uglify is not updated anymore

**Comment by pandrr** [comment]
fyi: we do this already with uglify (on export and on live server). so it would only replace a lib that is already working. or what is the problem ?

**Comment by kikohs** [comment]
No problems.
In cables-cli maybe you want to have the option to minify individual libs so you can still use deferred-loading (instead of one big js?) and protect ops.js?

Another idea for Cables - related.
Let's say you are running a paid workshop or course and you have UsersOPs you've made.

You invite the students to the team for them to have access to the patches. But now they can clone your awesome ops and share your exclusive stuff with anyone.

Maybe if you minify and uglify ops you want to protect people could use them without stealing their content. Like TouchDesigner or Houdini do with their private blocks.

What do you think?


On 10/10/2022 11:14:14, tom ***@***.***> wrote:

fyi: we do this already with uglify (on export and on live server). so it would only replace a lib that is already working. or what is the problem ?

**Comment by steam0r** [comment]
that sounds more like a feature request for the big "let's deal with user-ops in a better way"-task that we plan to do soon :)

**Comment by pandrr** [comment]
then use cables cli and only minify the files you want to.

i would say very special interest case, so do yourself :>

**Comment by steam0r** [comment]
also: minifying and uglifying does not really "protect your code", escpecially not when "copy pasting" is your main concern

**Comment by kikohs** [comment]
Yeah, it was in the "feature request" category in github not bugs!
When you create a new issue there are 2 categories :). Maybe I should have put this in discussion!

In JS you can't protect anything anyways unless you do WASM. But minifying and tersifying makes it harder.

Cheers

On 10/10/2022 11:36:03, tom ***@***.***> wrote:

then use cables cli and only minify the files you want to.

i would say very special interest case, so do yourself :>
