### ISSUE TITLE
gltf vertex anim op example

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#366]
Hi! Could you please add an example of use of the gltf vertex anim op to the site. Thank you!

https://cables.gl/op/Ops.Gl.GLTF.GltfVertexAnim

**Comment by pandrr** [comment]
hi,

no we don't have a vertex anim file that we can share, whats the problem ?

**Comment by pandrr** [comment]
we would be very happy to receive a file that we can use as an example. i'll invite you to a working patch

**Comment by steam0r** [comment]
were you able to create an example patch or file that we could use or you could share?

**Comment by n4hui** [comment]
Hi, here is this one based on the wirmachenbunt example i'll try after with multiple animations from the blender file

https://cables.gl/edit/n-3-sg

**Comment by n4hui** [comment]
Ok it's done, with 3 different models, i hope it helps!
