### ISSUE TITLE
SaveScreenshot OP bug with high-res display

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#368]
If you save a screenshot in high-res display the canvas size goes x2 and cannot be set back to the regular size.

[Bug here](https://dev.cables.gl/edit/_9PJ2f)

Thanks

**Comment by steam0r** [comment]
not sure what you mean by "canvas size goes x2", when triggering a screenshot in that patch my canvas stays the same (on mac in both chrome and firefox) and the resolution of the image is the same, regardless of the setting of hires display in mainloop. even when opening the patch on an actual retina display behaviour seems consistent.

**Comment by kikohs** [comment]
<img width="1664" alt="Screenshot 2022-10-10 183726" src="https://user-images.githubusercontent.com/1793640/194914326-a313438a-087d-4cf0-b4e4-dcae435926c8.png">
<img width="1663" alt="Screenshot 2022-10-10 183755" src="https://user-images.githubusercontent.com/1793640/194914333-09488ed1-1382-477a-84ea-ac8ff173706c.png">

**Comment by kikohs** [comment]
Win 11 Chrome - global 125% resolution

**Comment by steam0r** [comment]
thats with hires on and off in mainloop, or whats the difference?

**Comment by steam0r** [comment]
is this on a hires display? does changing your resolution to 100% change the behaviour?

**Comment by kikohs** [comment]
It's a 4K screen - 100% is so small it's not legible but seems to remove the bug!

**Comment by steam0r** [comment]
then i guess it's not really a bug in cables :) is this only in chrome?

**Comment by kikohs** [comment]
No Firefox too.

**Comment by steam0r** [comment]
i guess it's windows reporting height/width or (most likely) pixel density wrong, this is what the op does:

`op.patch.cgl.setSize(width.get() / op.patch.cgl.pixelDensity, height.get() / op.patch.cgl.pixelDensity);`

i guess this also goes away when ticking off "use canvas size" and inputting size manually?

**Comment by kikohs** [comment]
The saveScreenshot OP doesn't have any options. Are you referring to renderAnim?
How can I get a simple screeshot with renderAnim. When I try 1 frame at 1 FPS, the code is pre-rendering 20 seconds.

**Comment by steam0r** [comment]
what is the problem you are trying to solve?

**Comment by kikohs** [comment]
Let a user take a screenshot on click in a patch.

**Comment by steam0r** [comment]
![Bildschirmfoto 2022-10-10 um 18 59 39](https://user-images.githubusercontent.com/151271/194917917-8c6c2a51-ad3a-4c9f-88a6-242f45b7c76d.png)

this downloads one png for me, when triggered once (i.e. via sidebar)

**Comment by kikohs** [comment]
Random idea, from https://github.com/pandrr/cables/blob/develop/src/core/cgl/cgl_state.js
Maybe the canvas is not set back to the state before `pw` at the end of screenshot?

```
if (pw)
        {
            this.canvas.width = pw;
            w = pw;
        }
        if (ph)
        {
            this.canvas.height = ph;
            h = ph;
        }
    ```

**Comment by steam0r** [comment]
pw, and ph are not set when being called from SaveScreenshot

**Comment by kikohs** [comment]
Ok then it's probably a Window's issue :(.
Trying renderAnim but it prerenders 20 frames which takes 40 sec on my patch. I'll see if I can tweak it maybe.
Thanks

**Comment by kikohs** [comment]
Here is my new implementation of SaveScreenshot based on RenderAnim.
It solves the canvas size issue with custom DPI scaling and high-res display and also offers more options with output format.

https://cables.gl/edit/_9PJ2f

**Comment by pandrr** [comment]
yeah the op is not great anyhow.

it makes more sense to use "downloadTexture" to download "screenshots". this way you also have guaranteed antialiasing settings, which are very important for screenshots. you never know what the default settings are on users pcs....

also its not really a "screenshot". its also only a capture of the renderbuffer

we will proabaly deprecated it and only use downloadtexture...
