### ISSUE TITLE
Flipped icons when mouse-overing cable

### ISSUE THREAD

**Issue by mgunyho** [cables-gl/cables_docs#369]
**Describe the bug**
When I mouse-over on a cable, the icons are flipped. It says right-click for "insert op" and left click for "remove cable", while the behavior is the opposite.

**To Reproduce**
1. Mouse over on a cable

**Expected behavior**
The icon for "insert op" should be left-click and the icon for "remove cable" should be right-click.

**Screenshots**
![image](https://user-images.githubusercontent.com/20118130/195157186-a8923877-ac48-43df-a84c-9c6f57807b0b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox
 - Version: Firefox 105. Or if this is asking about the version of cables.gl, I don't know where to find it.

**Comment by steam0r** [comment]
hey, thanks for the report. we fixed this and you can check it on dev.cables.gl now.

**Comment by steam0r** [comment]
pushed to cables.gl
