### ISSUE TITLE
Pixelate OP - default width of 320 causes a width glitch

### ISSUE THREAD

**Issue by tastez** [cables-gl/cables_docs#37]
**Describe the bug**
Adding a pixelate OP to an image compose will result in a blank view until you adjust the width to something not equaling "320" . After saving and reloading, pixelate effect works correctly - however if you set it to 320 exactly again, the preview is correct, but saving and reloading will cause 0 (?) width

**To Reproduce**
1. Go to editor and create an imagecompose setup and add pixelate
2. See error
3. change width setting of pixelate OP and then return it to "320"
4. save and reload patch
5. See error

**Expected behavior**
width of 320 doesn't glitch out

**Screenshots**

https://user-images.githubusercontent.com/78642112/122194174-7c8d0e00-ce95-11eb-8c91-efa2cb393472.mp4

**Desktop (please complete the following information):**
- OS: Microsoft Windows 10 Pro , Version 10.0.19041 Build 19041
- Browser: Microsoft Edge
- Version: Version 91.0.864.48 (Official build) (64-bit)

**Additional context**
also tested on Chrome.
Default height value of 180 seems to cause an issue too.

**Comment by pandrr** [comment]
thanks
fixed on dev.cables.gl

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
