### ISSUE TITLE
Ammobody (simple geometry in cables) not working with AmmoCharacter (collision)

### ISSUE THREAD

**Issue by archgary** [cables-gl/cables_docs#376]
Hi Cables.gl team,

First of all, just want to say great work for all your contribution and time. Really like this creative tool.

Currently, you release the VR feature which I've been waiting for years and it's effortless to set it up. 

Due to the idea of making people who don't have the VR headset to still enjoy the project, you've managed this issue with Ammo World, Ammo Character, and Ammo Camera. That's again super nice.  

However, when I tried to build up a simple scene with a cube as the floor (Ammo Body), it seems to have a problem working with Ammo Character. I tried to bring the AmmoBodyCollision and used it for Ammo Character, but still not working. 

Most of your examples (like https://cables.gl/p/Twky7f or https://cables.gl/op/Ops.Physics.Ammo.AmmoCharacter) you have are with the "GltfAmmoBodies" which works perfectly. Of course, I can just simply model the plan/cube and bring it in and assign it to the "GltfAmmoBodies ", but I just wonder if there is an easy way to just have the basic geometry working with AmmoCharacter (collision). 

Hope this is clear to you, not sure if it is a bug or just I didn't find the right example. If that's the case, please let me know where to get it.

Thanks for your time in advance and look forward to hearing your feedback. 

Cheers,
Jia-Rey

**Comment by archgary** [comment]
And I try to import a floor-like cube from Blender as .glb file and assign it to the "Gltfscene" with "GltfAmmoBodies" still not working. Is there any specific setting for the .glb file to have the ammo body features? (like triangular mesh? try it as well, but no luck). Thank you for your response in advance.

**Comment by archgary** [comment]
I've successfully today to import a plane and cube (with Collision as a prefix to match the "Filter meshes" in GltfAmmoBodies) from blender to "Gltfscene" with "GltfAmmoBodies" which works. For making a cube directly in Cables.gl, it works when the ammo world reset, but once I move with WSAD key, it falls. Just to let people know here. :)

**Comment by steam0r** [comment]
does this problem still exists? can you maybe provide a simple small example patch that demonstrates the issue? thanks!

**Comment by archgary** [comment]
Sure, a quick test like this. https://cables.gl/edit/4-BO9g

When it is the .glb, it works (with Collision as a prefix). But if trying to use a cube as the floor in cables.gl, it works at the beginning and stops working while you press WSAD to move. I also tried to use AmmoBodyCollision, but no luck. I hope this is clear to you. 

Thank you!

**Comment by pandrr** [comment]
![Screenshot 2022-10-24 at 15 16 20](https://user-images.githubusercontent.com/98792/197534525-dfd34f37-ff3a-44e0-ba56-2af38ab19562.png)

the cube is just very small, you can see it from below

**Comment by archgary** [comment]
AH, Great. Thanks for giving me this hint. 
I went back to tweak the sizeX sizeY and sizeZ to match the floor size and it works. 

Just a note here: 
Width = size X
Length = sizeZ
Height = sizeY

steam0r and Pandrr, thank you so much for this help!
