### ISSUE TITLE
GateString: else condition commented out

### ISSUE THREAD

**Issue by Anna-S0phia** [cables-gl/cables_docs#38]
**Describe the bug**
The GateString Op should take a string and a boolean as input. If true the output is the input string, else should be an empty string. The output is always the input string because the else condition is commented out in the code.

**To Reproduce**
1. Go to 'Ops.String.GateString'
2. Open Code
3. See error

**Expected behavior**
See describe the bug above. 

**Screenshots**
<img width="565" alt="GateString_2" src="https://user-images.githubusercontent.com/62997185/123469320-2c2f5200-d5f3-11eb-818f-89547b24c45e.png">

**Desktop (please complete the following information):**
 iOS, chrome

**Additional context**
not necessary

**Comment by steam0r** [comment]
hey,

thanks for reporting. this is intended behaviour though. all the Gate ops work like this. Think of it as an actualy gate. If you let something through a gate and close the gate, the thing you let through before is still behind the gate.

SwitchStringBoolean with an empty string for "false" will do what you want, i think.

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
