### ISSUE TITLE
Remote Viewer throws error when using a MidiNoteFilter op

### ISSUE THREAD

**Issue by kebby** [cables-gl/cables_docs#380]
**Describe the bug**
Remote Viewer throws an error when you use a MidiNoteFilter op

**To Reproduce**
1. Create new patch, start remote viewer
2. Add a MidiInput and a MidiNoteFilter op

**Expected behavior**
No errors

**Screenshots**
![cablefail](https://user-images.githubusercontent.com/1643404/197610416-0f917028-c16a-4dac-bf50-7f14c3a7c984.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 106

**Comment by pandrr** [comment]
i updated the op and fixed some obvious problems, can not test with a midi device right now, let me know if it works

thx!

**Comment by steam0r** [comment]
this is now on cables.gl with the latest release
