### ISSUE TITLE
Add < and > shortcuts instead of GreaterThan

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#381]
using + - and so on is helping a lot, adding < and > would be helpful/concise too

**Comment by pandrr** [comment]
done on dev

**Comment by wirmachenbunt** [comment]
i forgot = aka equals...anything else ?

**Comment by wirmachenbunt** [comment]
![image](https://user-images.githubusercontent.com/1138673/197832966-12ccd086-b188-48ae-bba3-6c295b98cb4f.png)
ok you already did it :) 
do you insist on "GreaterThan" instead of the symbol ?

**Comment by wirmachenbunt** [comment]
ok, one more thing, when i type = i get instantly "equals", it would be nice if this also would be the symbol rather than the word ... and doesn't create the op immediately but lets me choose the type in the op browser. i might want to compare string or a number
