### ISSUE TITLE
Blueprint: Disable "convert to subpatch" if user doesn't have access to parent blueprint patch 

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#385]
Ideas we've talked about in the 26/10 meetup.

Imagine you want to keep users playing with your blueprint but don't want to share the inside of it.
The current implementation works pretty well with 403 Forbidden if patch member doesn't have access to parent blueprint patch.

The "copy to subpatch" breaks that protection and effectively allow people to "steal" blueprints.

**Comment by steam0r** [comment]
hey,

i really don't think we will be doing anything like "in patch"-permissions or some "outside view" only permission system for cables soon, or even at all. this is super complicated to get right, gives a false idea of security and would also be a pain to define in some ui (blueprint can be read by users, written by teammembers, read by collaborators, deleted by owners...). sorry :(

what i don't get is what you mean with "403" works pretty well but copy to subpatch breaks it...are you saying you somehow have access to blueprints that refer to patches you have no right to? THAT would be a bug then...
