### ISSUE TITLE
Patch is invisible when exit fullscreen in patch-editor

### ISSUE THREAD

**Issue by nodepond** [cables-gl/cables_docs#4]
**Describe the bug**
In the editor: when leaving fullscreen with control+cmd+enter, the patch is not visible anymore.
By leaving fullscreen with esc, patch is visible again.

**To Reproduce**
1. Go to editor of some patch.
2. Go to fullscreenmode (no matter if cmd+enter or fullscreen-icon).
3. Leave Fullscreen by cmd+enter.
4. Patch is not visible anymore.

**Expected behavior**
Patch is visible. By leaving fullscreen with esc, patch is visible again.

**Screenshots**
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/1096414/108394364-eca3c400-7214-11eb-8f3c-32e4994ca979.png">

**Desktop (please complete the following information):**
 - OS: OS-X / Big Sur 11.2.1
 - Browser Google Chrome
 - Version 88.0.4324.150 (Offizieller Build) (x86_64)

**Comment by steam0r** [comment]
have put this in the cables backlog, will keep you updated. thanks for reporting!

**Comment by pandrr** [comment]
thanks is fixed on dev/next updayte

workaround: exit fullscreen using ESCAPE works fine!
