### ISSUE TITLE
Experimental GL View Editor - adding new OP by clicking OP settings name

### ISSUE THREAD

**Issue by tastez** [cables-gl/cables_docs#40]
**Describe the bug**
If you add a new OP to control a setting of a selected OP - for example an innerradius of a Torus, in GL view your mouse pointer will also hold a new cable until you click on the canvas - which also triggers a create new OP search dialog

**To Reproduce**
1. Create a basic patch and add an OP you want to control
2. Select the OP and click on one of the settings - for example size or time, etc
3. OP search will popup, find an op and press Enter or click Add, to add it to the connection
4. OP should be added but mouse pointer will also grab a new cable connection
5. Clicking on editor canvas will bring up new OP search again.

**Expected behavior**
If adding an OP by clicking on an OP setting in the OP inspector, no cable is created under the mouse pointer

**Screenshots**

https://user-images.githubusercontent.com/78642112/124943525-dbfdba00-e00c-11eb-9f58-8d9dbde73575.mp4

**Desktop (please complete the following information):**
- OS: Microsoft Windows 10 Pro , Version 10.0.19041 Build 19041
- Browser: Microsoft Edge
- Version: Version 91.0.864.64 

random:
attached a webm, renamed to mp4 (github workaround) - let me know if it doesnt work

**Comment by pandrr** [comment]
thanks fixed on dev.cables.gl

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
