### ISSUE TITLE
Shadow operator not rendering

### ISSUE THREAD

**Issue by constructor** [cables-gl/cables_docs#403]
**Describe the bug**
Shadows not working.

**To Reproduce**
1. Go to Cables shadow patch example: https://cables.gl/edit/auVl18

**UPDATE 03/11/2022:** The shadow now renders when before it did not. The shadow does seem to have a very jagged sawtooth appearance and I can not seem to fix this with the 'near', 'far' and 'bias' settings. I don't know why this happened.

**Expected behavior**
Shadows should render.

**Desktop (please complete the following information):**
 - OS: Windows 10 (22H2 with all updates applied)
 - Browser Chrome 
 - Version Version 107.0.5304.88 (Official Build) (64-bit)

**Additional context**
I had not used Cables for a while and on loading one of my patches noticed immediately that it was not rendering.
My Example: https://cables.gl/p/62b1c3683c407be049dc076a?s=xDedxFvC4SdYTYBi
The above example was rendering fine a short while ago, but no longer renders correctly.

**Comment by constructor** [comment]
So I have got a much more acceptable result by changing the shadow patch settings:
https://cables.gl/p/6364355a0d8b3c0b30e7090e?s=wASQHYpeSvNTB8sf

**Comment by constructor** [comment]
Changing the 'near', 'far' and 'bias' settings again has got a much better result.

https://cables.gl/p/62b1c3683c407be049dc076a?s=xDedxFvC4SdYTYBi

I am still unsure as to what changed from the earlier version but all seems to work, if with a little artefact.

**Comment by steam0r** [comment]
hey, we changed the example patch and didn't tell anyone :) i gather this is fine now? sorry for the confusion.

**Comment by constructor** [comment]
> 

I would say it is better, but it still looks pretty bad to me. There is very severe sawtooth jagged edges to the shadows and it causes a nasty shimmering effect. Maybe I am going something wrong but I can not seems to make these shadows smoother.

![Sawtooth Shadows](https://user-images.githubusercontent.com/176053/200320157-f94b3236-d49d-4be9-a125-f9341dbfd049.png)

**Comment by steam0r** [comment]
just to leave this added to the discussion for people to later find, there is pretty extensive (hopefully not too outdated documentation on lights and shadows in cables):

https://cables.gl/docs/7_lighting/lights/lights
https://cables.gl/docs/7_lighting/shadows/shadows
