### ISSUE TITLE
PointCloudFromArray constant error

### ISSUE THREAD

**Issue by bbbbbgdn** [cables-gl/cables_docs#411]
PointCloudFromArray Op always show the same error message
"Color array does not have the correct length! (should be 80)"

See in editor:
PointCloudFromArray Op
https://cables.gl/edit/b4HNri

<img width="631" alt="image" src="https://user-images.githubusercontent.com/12091461/203150075-ce5f9339-2985-4fdd-b018-a6a6f279a9f7.png">

**Comment by steam0r** [comment]
the patch you provided seems to be private, that being said the color-array has a stride of 4(rgba), so everything that goes in should be dividable by 4 and match up with the array of stride 3 (xyz) that you put into the first port (so 60 points xyz need a rgba color array of size 80). which the error hints you at that it's not the case.

**Comment by bbbbbgdn** [comment]
Just made patch public! 
Yeah it seems to show the same error regardless of input

**Comment by steam0r** [comment]
that patch does not show an error on the op for me:

![Bildschirmfoto 2022-11-22 um 11 14 21](https://user-images.githubusercontent.com/151271/203287988-fe0b6bd1-6b2b-436c-a875-af9ee8880bce.png)

**Comment by bbbbbgdn** [comment]
Yeah. Now it's gone. I suppose it was some kind of buffer?

I've had this problem in the previous patch, and then copied the minimal reproducible setup to new patch. And the problem node was copied along with an error somehow?
