### ISSUE TITLE
Chrome slow performance in editor.

### ISSUE THREAD

**Issue by bbbbbgdn** [cables-gl/cables_docs#412]
Just solved a problem I've struggled with cables almost two years! 
I have decent laptop MacBook pro 15" 2018, and it's always had worst performance in cables editor. On the simplest patches frame rate is unstable and could drop to 5 FPS. Even started to do cables on remote windows machine with better specs (still in Chrome). 

Asked discord people about what people use for cables, which browser and hardware. Almost decided, that my Mac needs an upgrade. Today randomly gave a try to Firefox. And WOW, it totally changed the game. It has smooth stable performance. Don't know is this unique for my machine or is this general rule?

Desktop:
 - MacBook 15-inch, 2018
 - OS: 13.0.1 (22A400)
 
Tested with:
 - Chrome Version 107.0.5304.110 (Official Build) (x86_64) (with lots of disabled extensions)
 - Chrome Version 108.0.5359.48 (Official Build) beta (x86_64) (clean)
 - Firefox 107.0 (64-bit)

<img width="392" alt="image" src="https://user-images.githubusercontent.com/12091461/203154298-e2714902-fd52-4de7-a501-211c2b129aeb.png">

**Comment by pandrr** [comment]
hard to say, maybe its the patch, maybe your computer, or chrome does not support your gpu.

look here if your browser has a major performance caveat
https://cables.gl/browser

try removing the viztextures maybe they slow it down.

we can not really do much about it
