### ISSUE TITLE
performance slow down when using dynamic environment map in phongmaterial

### ISSUE THREAD

**Issue by bod-cn112** [cables-gl/cables_docs#43]
When using a non-static input for the environment map in phongmaterial, the performance drops significantly.

1. Go to https://dev.cables.gl/p/60f169ad7efa7355b129396d?s=Ohl0ibyJZpvf4bcC
2. Disconnect the environmentmap input from copytexture to phongmaterial.
3. Framerate will go up again.

 - OS: macOS Catalina & Windows 10
 - Browser Chrome, Firefox, Edge, Vivaldi

**Comment by pandrr** [comment]
thank you for reporting, it is fixed on dev.cables.gl your patch performance is now much better there.

**Comment by steam0r** [comment]
this just went live on https://cables.gl with the last release, have fun!
