### ISSUE TITLE
DepthTexture behaviour does not match the example patch

### ISSUE THREAD

**Issue by geertdaelemans** [cables-gl/cables_docs#433]
** Description **
If you want to understand what DepthTexture does, you can indeed look at the example and then everything becomes very clear.

Nevertheless, when you recreate that same example patch, it does not work at all.

It seems that the DepthTexture function is different (older?) in the example. 

It could be that the new DepthTexture function is buggy...

**Comment by geertdaelemans** [comment]
I have used the same farplane as in the example. So the fix you proposed on Youtube does not help, sorry.

**Comment by pandrr** [comment]
ok got it, the op was still my user op and not a normal public op, your workflow is correct, try again, it should work now

**Comment by geertdaelemans** [comment]
Excellente! Thank you for fixing this so quickly. 👍
