### ISSUE TITLE
Copy Texture doesn't hold texture between frames

### ISSUE THREAD

**Issue by bhenriksson031** [cables-gl/cables_docs#434]
I expect the Copy Texture to keep its texture between frames but this seems to be lost after latest update. 

In the example file I only see an effect when pressing "Snapshot" but I expect that it would be persistent after that. https://cables.gl/edit/G2_my7

**Comment by pandrr** [comment]
thanks for reporting!

fixed it, let me know if there still is a problem

**Comment by steam0r** [comment]
this went to cables.gl with the latest release. thanks for reporting!
