### ISSUE TITLE
Sidebar Text-Input added feature request

### ISSUE THREAD

**Issue by rambodc** [cables-gl/cables_docs#435]
We built an authentication layer with page system on Cables, using sidebar for email and password. Our main issue is we can't clear the Text Input but if we have a trigger to clear the field it will be really helpful. Also is it possible to create "Is Password Field" as an option so that we can hide the entry text as a secret?

**Comment by pandrr** [comment]
this is now implemented on dev.cables.gl you can use it there.

**Comment by rambodc** [comment]
I just wanted to report a small fix on the Tex-Input "Clear" Trigger. When the trigger is clicked the "Result" on the output must also be cleared. Unfortunately right now the Result doesn't get cleared and causes issues down the pipeline. Thanks.

**Comment by pandrr** [comment]
thanks. fixed

**Comment by steam0r** [comment]
we do not have detailed plans for a release yet, might be a few weeks still

**Comment by rambodc** [comment]
Thanks for your prompt response.
