### ISSUE TITLE
Export Window closing when switching tabs

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#438]
would it be possible to leave the export dialog (github) open when switching tabs.
its slightly annoying when copy pasting infos like access token from the text editor or other tabs to the cables dialog because each time the dialog is gone when going back to the cables tab.

reopening the export dialog, all fields are empty again unless you exported once successfully. maybe make the fields persitent once something is entered

**Comment by steam0r** [comment]
this is implemented on dev.cables.gl, feel free to test and feedback!

**Comment by steam0r** [comment]
this went to cables.gl with the latest release. thanks for reporting!
