### ISSUE TITLE
Issue with normal-maps on GLB files

### ISSUE THREAD

**Issue by VoidBoid** [cables-gl/cables_docs#440]
Greetings !
i have been having some trouble with normal-maps generated in cables, i recreated the basic setup here.

https://cables.gl/p/SvNLMk

when you click through the variations (new hash button in sidebar) sometimes the texture stays black. this only happens when the 'normal map' port of the material is connected. i have been trying a lot of different things to figure out why this happens but it just seems to happen randomly. 
hope someone can help : )

**Comment by steam0r** [comment]
hey, at least for me this does not happen randomly at all but only when "antenna3" is triggered. you might want to check that glb and the normalmap seperatedly.

not sure if this helps: when i put the "normal map intensity" to 0 in the PhongMaterial it works for all the GLBs

**Comment by VoidBoid** [comment]
Hi, thanks for the quick reply, i checked again, also on some other patches. it does only happen with a couple of GLB files (not random like i thought) sorry i didn't see that yesterday. It is still a bit weird though, i checked everything, same materials on all of the GLB files, all transforms applied, all normals in the same direction, same export settings... ill check again though, must be something i missed there.

maybe i can ask another question here, the shapekey animation does not seem to work when i export a compressed GLB from blender (i think this is the reason why i could not get the shapekey animations to work a couple of weeks ago, i always used the compress export option) 
i just made a quick setup to visualize this, its in the same patch as linked above.
Cheers !
gj

**Comment by steam0r** [comment]
please keep seperate questions in seperate issues so it doesnt get confusing...maybe also try asking in "discussions" as (for example) i do not know blender but someone else might be able to help with export settings.

**Comment by VoidBoid** [comment]
ah yes, of course... sorry about that
