### ISSUE TITLE
Subpatch > ParseObject > Structure > Expose > Gets inserted in the Main Patch

### ISSUE THREAD

**Issue by rambodc** [cables-gl/cables_docs#441]
Just wanted to report a small bug that keeps happening.
Inside a Subpatch > Using a ParseObject > When clicking on any of the (Coloured Objects, Array, String etc..) . The new operator that gets created  drops into the Main Patch. So we have to go looking for it to bring it back to the subpatch.

<img width="1187" alt="CablesSubPatchParseJson" src="https://user-images.githubusercontent.com/43018374/209376220-32557d99-c583-4d61-9141-0f2b68b3ebe0.png">

**Comment by pandrr** [comment]
thanks for reporting!

this is now fixed on dev.cables.gl, it will be in the next release

**Comment by rambodc** [comment]
Oh great thank you. I tested it on dev and it works great!

**Comment by steam0r** [comment]
this went to cables.gl with the latest release. thanks for reporting!
