### ISSUE TITLE
Touchscreen Op doesn't normalize Finger 2

### ISSUE THREAD

**Issue by AdrianGreyish** [cables-gl/cables_docs#448]
**Bug in Op "Touchscreen": Normalize Coordinates just works for finger 1.
Finger 2 still uses Worldcoordinates** 

**Expected behavior**
Sidebar -> 1. Value: Finger1 x, 2. Value: Finger2 x

**Screenshots**
![nse-6495096961160832440-1000005760](https://user-images.githubusercontent.com/105173884/210673942-5450af7c-14d0-4cdf-b840-ed4fa4f857c1.jpg)

**Smartphone (please complete the following information):**
 - Device: OnePlus Nord
 - Android 12
 - Chrome
 - Version 108.0.5359.128

**Comment by steam0r** [comment]
hey,

thanks for reporting, i added/fixed this on dev.cables.gl and also added "force"-output for finger two to make them
behave the same. would be nice if you could check and report back. thanks!

best,
stephan/steam
