### ISSUE TITLE
Experimental GL View Editor - Deleting OP that has a red dot, keeps red dot on canvas

### ISSUE THREAD

**Issue by tastez** [cables-gl/cables_docs#46]
**Describe the bug**
When deleting an OP that has a red dot alert icon next to it, deleting the OP will leave the dot on the canvas.

**To Reproduce**
1. Go to new patch
2. Create new OP, for example VarTriggerString
3. See the red dot next to the OP
4. delete the OP
5. See red dot appear close to the center of the canvas.

**Expected behavior**
Red dot disappears after deleting OP.

**Screenshots**
![image](https://user-images.githubusercontent.com/78642112/128015051-a8f04c0b-cede-4525-9454-f17aa1250db7.png)

**Desktop (please complete the following information):**
Win 10
Microsoft Edge
Version 92.0.902.62 (Official build) (64-bit)

**Additional context**
reloading patch will remove the red dot.

**Comment by pandrr** [comment]
fixed

**Comment by steam0r** [comment]
also on live with bugfix release
