### ISSUE TITLE
Ammoworld Memory out of bounds

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#469]
i keep getting random crashes with Ammo, its a fairly simple setup. i use ammo just for 3D button interaction. the crash happens once every 10 minutes without interaction, just by running the patch.

the only difference i can see to another similar patch, is that i'm using the array position input of ammo body. 

<img width="973" alt="image" src="https://user-images.githubusercontent.com/1138673/214373090-8f10a409-5b5c-4e91-b6ce-3bc037122b03.png">

**Comment by pandrr** [comment]
example patch ?

**Comment by wirmachenbunt** [comment]
https://cables.gl/p/63cfee8cd08d5f9fc2931f25?s=vpPsJ74r5FC9s6LU
just testing the patch on windows right now, no crash so far, mmm weird.
