### ISSUE TITLE
chrome camera permissions being asked with an inactive webcam texture.

### ISSUE THREAD

**Issue by marioepsley** [cables-gl/cables_docs#472]
Seems chromes camera permissions don't take into account an inactive camera.

patch here where a click should activate the camera and then the google chrome camera permissions prompt.
I'm getting asked before the click.

https://cables.gl/edit/542IJn

**Comment by marioepsley** [comment]
Amazing, thanks for this!!

**Comment by marioepsley** [comment]
might be just me but not sure this has taken effect?

**Comment by pandrr** [comment]
did you try on dev ?

**Comment by marioepsley** [comment]
exported from dev, uploaded, still getting asked I'm afraid
