### ISSUE TITLE
SetLocationHash resets cables patch as private preview

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#478]
when using SetLocationHash, everytime i change the hash, the full patch reloads when sharing a private link preview, rendering the preview not usable for this project.

check out the help patch, it does the same. 
you see a short transparent patch background, when you switch scenes with the sidebar

https://cables.gl/p/63e022823c0ad1a26fda7f1a?s=D8mHHthkHpt5KnNu#/scene/2

**Comment by steam0r** [comment]
hey,

thanks for reporting. for what it's worth this seems to be related to the patch being in
an iframe. i will investigate.

best,
stephan/steam

**Comment by pandrr** [comment]
without secret url it does not do it (if you have access rights)

**Comment by pandrr** [comment]
i think its because browwers will always reload/not cache urls with a query params... and not fixable probably

**Comment by wirmachenbunt** [comment]
> hey,
> 
> thanks for reporting. for what it's worth this seems to be related to the patch being in an iframe. i will investigate.
> 
> best, stephan/steam

yeah, i guessed so. bloody iframe, i wish the cables website previews could live without it. 
i do my preview via github pages now, export works like a charm.

**Comment by pandrr** [comment]
hm wait...
setlocation hash sets the whole url, it should actually only do window.location.hash = '#food';

?

**Comment by steam0r** [comment]
we found that chrome has a somewhat weird behaviour of reloading the page when you press enter in the location-bar even though the hash doesnt change. does your behavius happen in all browsers?
