### ISSUE TITLE
auto capitalized strings are confusing

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#480]
![image](https://user-images.githubusercontent.com/1138673/217819235-6a17ed99-a5c2-4fe5-ade4-7877b0822e72.png)

some UI elements show strings different to the real thing, the first letter is always shown as capital. this is confusing when you compare strings and have to check if its not a typo. 

it never really produced an error when patching but it keeps me going after strings to double check if i not accidently typed a capital.

**Comment by pandrr** [comment]
yep annoying, fixed on dev.cables.gl

**Comment by steam0r** [comment]
this went to cables.gl with the latest release. thanks for reporting!
