### ISSUE TITLE
Not showing on smartphone

### ISSUE THREAD

**Issue by karlsworks** [cables-gl/cables_docs#483]
**Describe the bug**
Not showing on smartphone but working on desktop. 

**Expected behavior**
I should be happy to see the animation on smartphone. 

**Screenshots**

**Desktop (please complete the following information):**
Working on desktop.

**Smartphone (please complete the following information):**
 Huawei p50 Pro, p40 Pro, Samsung S22
All browser typers.

**Comment by steam0r** [comment]
which patch does this relate to? what is this about? can you provide a simple example and screenshots?

**Comment by karlsworks** [comment]
> which patch does this relate to? what is this about? can you provide a simple example and screenshots?

Humbly thanks [steam0r] for the answer. It look like this inside. Maybe I missed something? The site is https://karls.works 
<img width="1072" alt="Screen Shot 2023-02-14 at 10 51 58 AM" src="https://user-images.githubusercontent.com/124747170/218700605-ff4bdb0b-c111-41d2-82f0-f42793da3b73.png">

and the code below looks like this. Maybe I missed something? 

 <script>

       


        function patchInitialized(patch) {
            // You can now access the patch object (patch), register variable watchers and so on
        }

        function patchFinishedLoading(patch) {
            // The patch is ready now, all assets have been loaded
        }

        document.addEventListener('CABLES.jsLoaded', function (event) {
            CABLES.patch = new CABLES.Patch({
                patch: CABLES.exportedPatch,
                "prefixAssetPath": "",
                "assetPath": "assets/",
                "jsPath": "js/",
                "glCanvasId": "glcanvas",
                "glCanvasResizeToWindow": true,
                "onPatchLoaded": patchInitialized,
                "onFinishedLoading": patchFinishedLoading,
                "canvas":{"alpha":true,"premultipliedAlpha":true} // make canvas transparent
            });
        });
    </script>

**Comment by steam0r** [comment]
loads fine on my pixel 5, chrome and firefox

**Comment by karlsworks** [comment]
I installed chrome and firefox on my phone now. I had some standard browser, probably outdated. Oh my God, it´s working :-D I tried to figure it out why its was not working. It toke me 6 hours haha. Crazy. And you just save my mind with a simple answer. You set me free from the mind prison. Big thanks to you and I wish you all the best. <3

**Comment by karlsworks** [comment]
Thank you once again. You make my day :)
