### ISSUE TITLE
comma vs dots

### ISSUE THREAD

**Issue by VoidBoid** [cables-gl/cables_docs#489]
this is a question from the general channel on cables discord.
so what i initially said was:

one more thing i wanted to ask about, sometimes cables goes a little weird when i add a comma instead of a point between numbers. it happens quite often because i have a separate numpad (with a comma, no point on there) not sure if this happens to other people as well. blender just ignores this mistake and turns the comma into a point, maybe that could work in cables too ! 

i saw someone mention in the general thread that they sometimes want comma's but as far as i know comma's are never accepted in cables.gl the boxes where you enter Numbers (but maybe i am wrong here)

I mention cables acting a bit weird when entering a comma instead of a dot, by this i mean the black pop up that sometimes does not go away for a while, it blocks the view of the spot where a comma was entered by mistake and makes it hard to change the input.
Cheers 
GJ

**Comment by VoidBoid** [comment]
Hurrah !!
my right hand wrist, thanks you !!

**Comment by steam0r** [comment]
this went to cables.gl with the latest release. thanks for the suggestion!

**Comment by VoidBoid** [comment]
thanks for implementing this ! just tested it, works like a charm : )
