### ISSUE TITLE
vizObject and vizStringLong not working withoout MainLoop in patch

### ISSUE THREAD

**Issue by bbbbbgdn** [cables-gl/cables_docs#491]
![Mar-01-2023 01-13-23](https://user-images.githubusercontent.com/12091461/222012306-755a142c-aa90-405b-8fd5-a6fdf23a7b23.gif)
Expected it to work, or at least to have some visual hint or error. 

After adding Main Loop starts to work normally.

**Comment by steam0r** [comment]
thanks for reporting this. this is known and intended behaviour though

**Comment by bbbbbgdn** [comment]
But how do I suppose to know that it's normal? Looks totally misleading from my perspective 😵‍💫

**Comment by pandrr** [comment]
it's not intended, will be fixed in the future, or at least show an hint

**Comment by pandrr** [comment]
this is now fixed on dev.cables.gl

**Comment by steam0r** [comment]
this went to cables.gl with the latest release. thanks for reporting!
