### ISSUE TITLE
TextureArrayLoaderFromArray bug

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#492]
I noticed there is at least one bug with OP and several weird behaviors.

In `function realReload(nocache)`:  the `arr` is not cleared which keeps old textures on URLs changed if you have less urls than the previous value. E.g you load 4 images and then 3, the 4th image stays in the array.

The loading status true/false is changed for each image. I would expect it to be triggered only when everything has loaded. 
Same with output arr, which is triggered for each image.
```
arrOut.set(null);
arrOut.set(arr);
``` 

I've modified the code so it triggers only when everything is finished.
Let me know if better: [https://dev.cables.gl/op/Ops.User.kikohs.TextureArrayLoaderFromArray_mod](https://dev.cables.gl/op/Ops.User.kikohs.TextureArrayLoaderFromArray_mod)

**Comment by pandrr** [comment]
thanks for the feedback, 

the op was very old, i created a v2 which should work more as expected

- loading is only changed to true when everything is loaded (use triggerChangedTrue if you need a trigger)
- if array is disconnected it outputs null

**Comment by steam0r** [comment]
this went to cables.gl with the latest release. thanks for reporting!
