### ISSUE TITLE
Remove console.warn in in cgl_texture.js

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#494]
In `cgl_texture.js` l 620.
If a texture cannot be loaded, the case is treated by the user-given error function. Currently there is no way one can disable the warning if a texture cannot be loaded from the URL, which creates thousands of warning if you expect some textures to be missing.

**Comment by pandrr** [comment]
problem is people can't find out that textures are missing when they upload their files somewhere. they do not look into the network tab or anywhere.

why do you expect 404's ? then deliver a small placeholder image.
