### ISSUE TITLE
Math expression Ops with quick parameters '1+',  '/100' for UI ✨⭐️🌟✨

### ISSUE THREAD

**Issue by bbbbbgdn** [cables-gl/cables_docs#497]
This works for as a shortcut to get /100 OP
<img width="955" alt="Screenshot 2023-03-04 at 21 42 06" src="https://user-images.githubusercontent.com/12091461/222927971-4f8ffa6b-9fd2-4481-845b-2f403f8811e2.png">

**Comment by pandrr** [comment]
this is now implemented on dev.cables.gl

it now also tries to map math functions to arrays too...

**Comment by steam0r** [comment]
this is now available on cables.gl with the last update
