### ISSUE TITLE
BoolAnim invalid direction "Both"

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#503]
I think the default value set in the Input port is incorrect. It should be "Animate Both".

**Comment by pandrr** [comment]
fixed

**Comment by kikohs** [comment]
It is pushed on dev? I still have the warning/error.

**Comment by pandrr** [comment]
toggle it once to fix it, but does not happen with new ops

**Comment by kikohs** [comment]
On a brand new patch on dev with just this OP I have an error.
I don't see the code change.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/1793640/224750898-67223d38-c369-49e1-8817-711f57e18168.png">

**Comment by pandrr** [comment]
right, was not pushed, hopefully now fixed

**Comment by steam0r** [comment]
this went to cables.gl with the latest release. thanks for reporting!
