### ISSUE TITLE
Trigger only disconnect feature (and UI proposal)

### ISSUE THREAD

**Issue by bbbbbgdn** [cables-gl/cables_docs#505]
Would be really handy to have an ability to disconect an op from a middle of pipeline, like with 'x' but only releasing Trigger wires. (Maybe shift+x? or something) 

![CablesRec](https://user-images.githubusercontent.com/12091461/226757107-e004c544-8d47-40c6-bc70-0f9b839cf2a8.gif)

**Comment by pandrr** [comment]
we discussed how to do this back and forth for years.
i now added it using shift+x

it will disconnect the first in and output ports if they are both connected and of the same type and only connected once and then create alinked to the connected ports ...

**Comment by franckaubry** [comment]
Really happy this is implemented though! 🍡

**Comment by steam0r** [comment]
this went to cables.gl with the latest release. thanks for the suggestion!
