### ISSUE TITLE
MeshInstancerFromTexture instance index pick via RenderSlots

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#520]
I can only pick the material id when using MeshInstancerFromTexture. The green channel is always 0 instead of the instance number.
Not sure if it has been ported in this variation.

It is a great great feature.

Thank you!

**Comment by pandrr** [comment]
should be fixed on dev.cables.gl

**Comment by kikohs** [comment]
Works, thanks!

**Comment by steam0r** [comment]
this went to cables.gl with the latest release. thanks for reporting!
