### ISSUE TITLE
Point Material - minimal point size

### ISSUE THREAD

**Issue by KOLEKTYW-online** [cables-gl/cables_docs#522]
Using "Scale By Distance" checkbox makes points dissapear when they are far away and pointsize gets smaller than 1.
Could be useful to make a parameter with minimum pixel pointsize.

I cloned the Point Material and changed one line in Vertex Shader. I used **max(1.1, ..... )**:

    #ifdef SCALE_BY_DISTANCE
        float cameraDist = distance(model.xyz, camPos);
        ps = max(1.1, ( (pointSize+addPointSize) / cameraDist) * psMul);
    #endif

It does the job. Points are still visible regardless of viewing distance.

**Comment by pandrr** [comment]
thanks this is now available in pointmaterial on dev.cables.gl "min point size"
