### ISSUE TITLE
PointsPlane point number ordering is wrong for PointMaterial vertex colors

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#524]
Hello,
I was trying to create a simple grid point cloud from a texture but it seems the point number are not in the right order to display the image correctly. It is rotated to the right.

I made a patch to explain: https://dev.cables.gl/edit/88u3lu

Additionally, when reloading the patch, only a small square is displayed. Changing PointsPlane width and height refreshes things.

Thank you.

**Comment by pandrr** [comment]
fixed the "not updating bug". order not critical bug
