### ISSUE TITLE
Basicmaterial colorpicker creates cable on click

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#53]
![image](https://user-images.githubusercontent.com/1138673/128728942-c327d94e-a834-4663-be77-af61bdae1e86.png)

When a basicmaterial op is selected and you click the color picker option (inspektor), a cable appears as if cables wants you to connect something.

**Comment by pandrr** [comment]
fixed

**Comment by steam0r** [comment]
went live with the recent bugfix release
