### ISSUE TITLE
Bad vertex colors 

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#535]
Hi! I was importing some baked vertex colors models but it's appereance was very wrong, i figured out that the problem comes from the Blender exporter in recent versions, i tested this with the 3.1 version exporter and the problem is not.

i share with you an example, just connect the model of the version.

https://cables.gl/edit/pEfviY

I tested this only in desktop chrome.

**Comment by pandrr** [comment]
when i import your glb file into blender it looks exactly like it looks in cables. the file just contains wrong colors

**Comment by n4hui** [comment]
Hi! yes, as I said, the problem was from the blender gltf import, not cables. I guess the issue now is fixed from blender 👍

**Comment by pandrr** [comment]
then please dont create issues ?!?
