### ISSUE TITLE
I can't open some patches with the new update

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#537]
Hi! i can't open some of my patches in the editor since today with the new cables update, even i tested it in dev some days before, this is the message that appears:

![image](https://github.com/cables-gl/cables_docs/assets/65823796/ca8688ac-f22d-471a-9540-1edcf00e1090)

I tried now also in dev and the same result

![image](https://github.com/cables-gl/cables_docs/assets/65823796/4157dbb5-26aa-4c2b-8b4e-072c0d300040)

I'll check it out if this happens in one of my public patches also so i can share a patch to you to fin the problem

I tested this in Windows Desktop Chrome

help plz!!!

**Comment by steam0r** [comment]
hm, can you share one of the patches, or invite me? are you using "new experimental subpatches" in these?

**Comment by pandrr** [comment]
please try again on dev!

**Comment by n4hui** [comment]
> hm, can you share one of the patches, or invite me? are you using "new experimental subpatches" in these?

Hi! no, i haven't work on these since months

**Comment by n4hui** [comment]
> please try again on dev!

It's working again thank you very much!!! i only see this strange line i guess from the new features

![image](https://github.com/cables-gl/cables_docs/assets/65823796/52d2f175-508d-48c7-890a-d21bceb7f26d)

**Comment by steam0r** [comment]
this went to cables.gl with the latest (small fixes) release. thanks for reporting!

that red line is a warning that you somehow managed to create links between and across subpatches...you might want to check into that and clean it up. might have happened while copypasting things around.
