### ISSUE TITLE
Help: Error in op: Ops.Gl.Render2Texture

### ISSUE THREAD

**Issue by gravotto** [cables-gl/cables_docs#538]
Hello Cables Community!

I have encountered a problem with my patches failing. To be clear everything was working with cables.gl up until June 5/23 I went away for a week and started working on my projects today June 13/23.
My hardware config of many years is as follows:
macOS Monterey v12.6.6
Mac Pro (Late 2013)
Processor: 3.5 GHz 6-Core Intel Xeon E5
Memory: 128 GB 1066 MHz DDR3
graphics: AMD FirePro D700 6 GB

When I open my patch this is what I see:
cablefail :/
Error in op: Ops.Gl.Render2Texture
null is not an object (evaluating 'fb.getWidth') **<----- This line seems to be a common denominator with any cable fail.**

stacktrace:
doRender@https://cables.gl/api/ops/code?nc=555694:55705:11
@https://sandbox.cables.gl/ui/js/cables.min.js?nc=1686571821393:1:85841
@https://sandbox.cables.gl/ui/js/cables.min.js?nc=1686571821393:1:82541
triggerAll@https://cables.gl/api/ops/code?nc=555694:105258:76
@https://sandbox.cables.gl/ui/js/cables.min.js?nc=1686571821393:1:85841
@https://sandbox.cables.gl/ui/js/cables.min.js?nc=1686571821393:1:82541
@https://cables.gl/api/ops/code?nc=555694:40165:20
@https://sandbox.cables.gl/ui/js/cables.min.js?nc=1686571821393:1:85841
@https://sandbox.cables.gl/ui/js/cables.min.js?nc=1686571821393:1:82541
render@https://cables.gl/api/ops/code?nc=555694:52481:17
@https://sandbox.cables.gl/ui/js/cables.min.js?nc=1686571821393:1:85841
@https://sandbox.cables.gl/ui/js/cables.min.js?nc=1686571821393:1:82541
triggerAll@https://cables.gl/api/ops/code?nc=555694:37272:32
@https://sandbox.cables.gl/ui/js/cables.min.js?nc=1686571821393:1:85841
@https://sandbox.cables.gl/ui/js/cables.min.js?nc=1686571821393:1:82541
render@https://cables.gl/api/ops/code?nc=555694:38266:20
@https://sandbox.cables.gl/ui/js/cables.min.js?nc=1686571821393:1:239630
@https://sandbox.cables.gl/ui/js/cables.min.js?nc=1686571821393:1:239790
@https://sandbox.cables.gl/ui/js/cables.min.js?nc=1686571821393:1:240656
@https://sandbox.cables.gl/ui/js/cables.min.js?nc=1686571821393:1:233946
@https://sandbox.cables.gl/ui/js/cablesui.min.js?nc=1686571869846:1:729626

The issues with the patch are my gltf model has missing parts and I added some cool reactive spline movement that simply doesn't show up anymore. This is part of the render2texture crash.

All I can tell you is that something changed within the time I was away. All my patches did work. I am also aware that I cannot work on patches in the dev.cables because my machine can't handle those particles. I do need new hardware before I can tackle those.

For now, I need to get back to where I was so I can move forward with my client projects. If anybody has any advice or suggestions I would greatly appreciate the help. I will provide anything I can to get this back on track.

Thank you very much, Troy

![Screen Shot 2023-06-13 at 1 03 17 PM](https://github.com/cables-gl/cables_docs/assets/6984047/57c97935-0ddd-48e8-bc6d-349d31b2e36d)

**Comment by pandrr** [comment]
- try turn off 32bit render target in render2textures
- try another browser (see browser support message)

**Comment by gravotto** [comment]
Hi pandrr, Thanks for your assistance. Is this what you mean? Pixelformat Float 32bit? I tried it on and off and still no change.

Just another note for you, I can view my projects but I cannot edit them properly. Here is a link for you to try. https://cables.gl/p/_fLR-x
![Screen Shot 2023-06-13 at 1 34 51 PM](https://github.com/cables-gl/cables_docs/assets/6984047/fb09bccb-f305-429e-80da-4f6657f248bc)
![Screen Shot 2023-06-13 at 1 35 41 PM](https://github.com/cables-gl/cables_docs/assets/6984047/737e3d8d-9cbd-4d22-85ec-8d005e45f90b)
![Chrome Screen Shot 2023-06-13 at 1 44 04 PM](https://github.com/cables-gl/cables_docs/assets/6984047/ed01e958-349e-4902-a1c2-4cb2729a0e69)

**Comment by gravotto** [comment]
Hi pandrr, here is another error from a patch I presented to a client last week. Again everything was fine it is a very simple patch. 
Here is the link: https://cables.gl/edit/tYqhLx

and the warning I have never seen before today.

WARNING: 0:2: 'GL_OES_texture_float' : extension is not supported
WARNING: 0:3: 'GL_OES_texture_float_linear' : extension is not supported
WARNING: 0:4: 'GL_OES_texture_half_float' : extension is not supported
WARNING: 0:5: 'GL_OES_texture_half_float_linear' : extension is not supported
WARNING: 0:7: 'GL_OES_texture_float' : extension is not supported
WARNING: 0:8: 'GL_OES_texture_float_linear' : extension is not supported
WARNING: 0:9: 'GL_OES_texture_half_float' : extension is not supported
WARNING: 0:10: 'GL_OES_texture_half_float_linear' : extension is not supported
ERROR: 0:48: 'flat' : Illegal use of reserved word

**Comment by gravotto** [comment]
Here is another error I get for the Matcap & Cubemap Creator. I used this all of the time to create my Matcap Materials. Now it is useless to me.
I really hope we can fix this. 
Would you be able to create another instance of the previous version of Cables.gl?
Thanks, Troy
![Screen Shot 2023-06-13 at 3 34 23 PM](https://github.com/cables-gl/cables_docs/assets/6984047/1d9173d7-14d0-4c19-b46f-9842b6fa4200)

**Comment by steam0r** [comment]
the patch you posted is private, we cant access it. please make a simple public example. that being said, since it seems to be a client project. you can always book us to help with these kinds of problems and support cables development that way as well.

**Comment by steam0r** [comment]
we will not set up different versions of cables for different users/groups, that would be unmaintanable. there is something like and "offline version" on the roadmap for later this year though, which will then be able to just work with any "old" version of cables if you do not update.

**Comment by gravotto** [comment]
Thank you for the update. I appreciate the information regarding the offline version in the future. However, for my current situation, I hope we can address the following two issues, it would greatly benefit me:

Firstly, I am experiencing an issue with the Render2Texture OP. The previous version from last week worked well. Is it possible for me to obtain the previous version of that OP?
Secondly, I'm encountering problems with my GltfScenes. They either render only partially or not at all. Typically, I import an FBX file and let the Gltf file generate.
Here are a couple of private links for you to review:

In this patch, the car model only partially renders, and the Render2Texture doesn't start. It produces a cool spline texture background that I am remixing from someone else.
(https://cables.gl/p/_fLR-x?s=M3mwsQetULGNoni7)

In this patch, my eag_circle_logo fails to render. It was functioning correctly last week. (https://cables.gl/p/U2DeKx?s=JqWcTasBMAsOpHIu)

On another note, I was able to work a little in the dev.cables area, but it is quite limiting for me due to the lack of a proper graphics card. The best advice from Pandrr was the Div element OP. Simple things seem to be ok. I am considering investing in a new machine soon to access all the particle capabilities and other features.

I hope we can resolve these two issues. Once again, I appreciate your time and patience in addressing these matters.

Thanks, Troy

**Comment by steam0r** [comment]
secret links do not allow for opening the patch in the editor. did you check this setting in your editor preference?

![Bildschirmfoto 2023-06-15 um 09 25 12](https://github.com/cables-gl/cables_docs/assets/151271/63af22fb-b929-4490-a2b7-4f5afc959ba1)

**Comment by steam0r** [comment]
last changes to render2texture were made in early february, last significant changes were made in may last year...

**Comment by gravotto** [comment]
Hi steam, thanks for the suggestions. I am just making changes. I made one change and now I get this:
Shader error errorshader

WARNING: 0:2: 'GL_OES_texture_float' : extension is not supported
WARNING: 0:3: 'GL_OES_texture_float_linear' : extension is not supported
WARNING: 0:6: 'GL_OES_texture_float' : extension is not supported
WARNING: 0:7: 'GL_OES_texture_float_linear' : extension is not supported
WARNING: 0:8: 'GL_OES_texture_half_float' : extension is not supported
WARNING: 0:9: 'GL_OES_texture_half_float_linear' : extension is not supported
WARNING: 0:11: 'GL_OES_texture_float' : extension is not supported
WARNING: 0:12: 'GL_OES_texture_float_linear' : extension is not supported
WARNING: 0:13: 'GL_OES_texture_half_float' : extension is not supported
WARNING: 0:14: 'GL_OES_texture_half_float_linear' : extension is not supported
ERROR: 0:247: 'flat' : Illegal use of reserved word

**Comment by steam0r** [comment]
these extensions are only loaded if you are on webgl1, which you claim you arent...

**Comment by gravotto** [comment]
I have always had force webgl to on.
![Screen Shot 2023-06-15 at 1 41 15 AM](https://github.com/cables-gl/cables_docs/assets/6984047/a557ce0f-ef81-4ed5-bd74-490d55ba05af)

I really don't know what to think now when it comes to the render2texture. Something really got messed up somewhere. That and shader errors. idk
I haven't done anything to my system. I am starting to wonder if macOS security updates could affect things.

**Comment by gravotto** [comment]
i sent you an invite to my roadster patch.
maybe you can see something i don't.

**Comment by gravotto** [comment]
![Screen Shot 2023-06-15 at 1 50 10 AM](https://github.com/cables-gl/cables_docs/assets/6984047/175c7bee-d3ab-43b9-8b5a-c5a74703ca2c)
this is what i see in chrome editor as well as firefox
![Screen Shot 2023-06-15 at 1 51 47 AM](https://github.com/cables-gl/cables_docs/assets/6984047/ddfad354-90e2-412e-b0ff-09f827869ca6)
this is just viewing only

**Comment by gravotto** [comment]
this is safari
![Screen Shot 2023-06-15 at 1 55 55 AM](https://github.com/cables-gl/cables_docs/assets/6984047/101ead4a-3821-46da-9f3b-cb5d6191631e)
![Screen Shot 2023-06-15 at 1 56 22 AM](https://github.com/cables-gl/cables_docs/assets/6984047/76fcbc9f-f324-4321-8e31-0a04ebaa6a10)

**Comment by steam0r** [comment]
![](https://cdn.discordapp.com/attachments/698533231233990667/1118811884062253056/Bildschirmfoto_2023-06-15_um_09.58.52.png)

thats your issue right there, you are forcing webgl1 and your graphicscard does not support the extensions. turn this off...

this whole "issue" would have taken away lot less of our time if you told us you are forcing an old version of webgl intentionally...if you fiddle with "advanced settings" please know what you are doing...

there is no need to make your patches webgl1 compatible anymore since a few years unless you are in very esotheric setups...and then you should know what you are doing anyhow.

**Comment by gravotto** [comment]
wow, you are a lifesaver. I did just turn it off and it worked! thank you
I do wonder why it did work for a period of time as I probably had it on for quite some time

**Comment by steam0r** [comment]
we are not testing things in setups where basically the user said "i know what i am doing" so there might have been some changes that affect that specific setup. again: next time try to get a clear and decent default state before stirring up a fuss about things being broken. glad everything works now...

**Comment by gravotto** [comment]
as I am going through patches I am noticing that a few examples were set to on. I am not sure but I assume when I clone the patch the editor prefs are also cloned. I will have to watch out for this unless is there a global setting I can change?

**Comment by steam0r** [comment]
editor preferences are not connected to the patch and are not cloned or anything its a global setting for your editor. you turned and left that on.
