### ISSUE TITLE
cable mouseover not working when op is selected

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#54]
before the UI update we had to select an op in order to manipulate in and out going cables. 
the new behaviour is: you can't click an incoming cable once an op is selected. 

![image](https://user-images.githubusercontent.com/1138673/128748443-7f2d15d4-ff57-46b6-858d-772fae08ed93.png)

**Comment by pandrr** [comment]
thanks, fixed on dev

**Comment by steam0r** [comment]
also on live now
