### ISSUE TITLE
Switch Array doesn't trigger Changed Array

### ISSUE THREAD

**Issue by bbbbbgdn** [cables-gl/cables_docs#542]
I used before **Switch Array** + **Mesh instancer** (points positions) in one of my patches, it stopped to work.
Apparently it works if I remove **Switch**. 

Here's sample with reproduced behaviour
https://cables.gl/edit/lm8vDz

What to reproduce:
<img width="529" alt="Screenshot 2023-06-23 at 11 08 38" src="https://github.com/cables-gl/cables_docs/assets/12091461/63d11f54-5ee0-461a-bcc5-c3b55e0e8edd">

**Comment by bbbbbgdn** [comment]
Expected behavior, that Mesh Instancer is updated when Array Updater in any of the ways.

**Comment by pandrr** [comment]
thanks, fixed!

**Comment by steam0r** [comment]
this is now available on cables.gl with the last update
