### ISSUE TITLE
Node graph fails when made into a subpatch

### ISSUE THREAD

**Issue by constructor** [cables-gl/cables_docs#544]
**Describe the bug**
Node graph stops working when made into a subpatch.

**To Reproduce**
1. Go to https://cables.gl/p/j6CCPz?s=DfDEHNpXIpm59wKC
2. Click the on screen 'play' button 
3. There should be an audio visualizer reacting to the audio generated. This functionality is generated by the nodes inside the 'Before Subpatch' area. 
4. Beneath the working audio visualizer, there should be a white line, this is the output from the Subpatch. It is not working even though it contains the exact same nodes as the working visualizer.
5. Click inside the subpatch to see that the 'MapRangeArray' fails to function inside the subpatch. 

**Expected behavior**
The node graph should work in the same way both inside and outside of a subpatch.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro - 22H2 - 22621.1848
 - Browser: Chrome
 - Version: 114.0.5735.134 (Official Build) (64-bit)

**Additional context**
I found this issue because I am forced to recreate subpatches because they will corrupt after being cut and pasted, and therefore can not be used to create modular and reusable functionality. See here: https://github.com/cables-gl/cables_docs/issues/274

**Comment by constructor** [comment]
Here is another example that shows subpatch not working:
https://cables.gl/p/MzE-Tz?s=OEocjVUk8lXh5Kqb
Am I doing something wrong here?

**Comment by constructor** [comment]
Here us a third example that shows that using VarGetArray works, but linking the array with a cable fails.
https://cables.gl/p/tvJaYz?s=pzS1iGciAaFlIxwo
This breaks so many things and I can't really use Cables at the moment because of it.

**Comment by pandrr** [comment]
thanks, we are currently reworking subpatches completly!
