### ISSUE TITLE
Op is crashing if url entered incorrectly

### ISSUE THREAD

**Issue by k0mrad** [cables-gl/cables_docs#545]
Accidentally adding a ; within a URL input crashes an op. This can be reproduced even while typing. Removing the URL and refreshing does not fix the situation. The only way to fix this, is to delete the op from the canvas and add it again. 
https://www.dropbox.com/s/c6e9h9d7ighesxp/Screenshot%202023-07-01%20at%205.25.24%20PM.png?dl=0

OS: 
Mac OS Ventura 13.4.1 (22F82)
Brave [Version 1.52.126 Chromium: 114.0.5735.133 (Official Build) (arm64)]

**Comment by steam0r** [comment]
thanks for reporting, this is fixed on dev.cables.gl and will be in the next release

**Comment by steam0r** [comment]
this is now available on cables.gl with the last update

**Comment by k0mrad** [comment]
hey this is still an active issue, I just tested this with a texture op @steam0r

**Comment by k0mrad** [comment]
https://cables.gl/edit/enPK23  and here's a video of the issue https://www.dropbox.com/s/hwzcwt1ozoovun9/cables-error.mov?dl=0

**Comment by k0mrad** [comment]
sorry! I just realised that I confused this issue with something else @pandrr @steam0r
