### ISSUE TITLE
Repeat index order is off

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#55]
Demo
https://cables.gl/p/lBAqLI

the order of repeat indices seems to be wrong in some cases
this is one, the text width does not match the selected string

**Comment by pandrr** [comment]
![Screenshot 2021-08-11 at 15 33 22](https://user-images.githubusercontent.com/98792/129038311-31979a10-cbaa-49a1-b08c-3ac96efceacf.png)

you need to do things in the correct oder:
1. set string
2. draw string, so you get the width
3. draw box in correct size

[rendering artefacts are then a different problem]

**Comment by wirmachenbunt** [comment]
thanks for the thinking, so it is order of execution. number crunching mixed with layering of graphics. either the layering is right or the number crunching.

in vvvv there are "Group" aka "Layer" nodes to define the order of drawing independent from calculating numbers. its one of the cases where the simplicity of cables is a problem, since there is no distinction between the tasks.

it could be worked around like this, although its not very efficient to render the texts twice (offscreen and for real)
![image](https://user-images.githubusercontent.com/1138673/129093967-50ae1d14-6249-4cf6-94d6-867891be958c.png)

what would be really cool to create "graphics objects", like a text with a rectangle as one unit and then creating instances of this object, to preserve the order of drawing. but thats a complex language feature i guess.

**Comment by steam0r** [comment]
original issue is fixed, the "instancing" thing is on our backlog and wishlist
