### ISSUE TITLE
MpHandTracking reload bug

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#550]
On reload, I have an alert popup saying it can't find the camera and then the OP doesn't work at all.
The only way I made it work was to manually reconnect the input webcam texture out port to the OP.

I propose to change the OP so that is has a start trigger. It needs to be delayed to make sure the webcam is setup correctly.

This setup works:
https://cables.gl/edit/IA6pkB

**Comment by steam0r** [comment]
cant you just use GateObject connected to the "available" boolean on the WebcamTexture op?

**Comment by kikohs** [comment]
No, I tried, the available is "too fast". I need to delay a bit for MP to pick the right camera. Delay a gate object could also work but seems more cumbersome.

**Comment by steam0r** [comment]
modifying your path to do the rendering only when a hand is found and the webcam is available seems to be just fine, or am i not getting it? the problem with "delaying things" is that you never kno whow long you want to delay things, so the "available" on the webcam is wine, and maybe mphands should have a "library loaded" boolean out, but i guess that hand detected bool works fine and you can move that one down to MpHand and work with more or less confidence.

<img width="445" alt="Bildschirmfoto 2023-08-18 um 12 03 28" src="https://github.com/cables-gl/cables_docs/assets/151271/bef45e9b-f5af-4b65-9eb5-e6e6a82270bb">
