### ISSUE TITLE
Ops.Gl.Meshes.Torus_v2 has broken UV mapping

### ISSUE THREAD

**Issue by VentuzTammoHinrichs** [cables-gl/cables_docs#555]
**Describe the bug**
A torus, as it's just a 2d plane folded onto itself twice, should have perfectly tiling uv mapping (if the texture is tiling). Ops.Gl.Meshes.Torus_v2 doesn't do that but instead you get artifacts along the two axes.

**To Reproduce**
Here's the good news: I already took the liberty of fixing it (because a certain D. wanted a tunnel effect :D ). Repro case and custom op that has the issue fixed is at https://cables.gl/p/WSzNZB?s=NE3yfyIiLGthOnTk

The new code, if you have a torus with m rings and n sides, actually generates a mesh with m+1 and n+1 vertices, with the first vertices of every ring/side doubled but with u or v = 1 instead of 0. This fixes the mapping. 

This also means technically the mesh isn't a perfect manifold anymore, so any possible geometry manipulation that requires this might break. Use at your own risk.

**Comment by VentuzTammoHinrichs** [comment]
oops, should have probably logged out of my work account. Er, well. :)

**Comment by pandrr** [comment]
thanks! makes sense. moved your op to a new version of the torus op

**Comment by steam0r** [comment]
this is now available on cables.gl with the last update
