### ISSUE TITLE
The patch can't interact on Wordpress

### ISSUE THREAD

**Issue by pondpdd** [cables-gl/cables_docs#556]
To begin with, I am new to this particular field of study.

I intend to test my patch in the background of my WordPress site. Nevertheless, even though I have successfully integrated the patch, it is visible but lacks interactivity. I am currently seeking a solution to fix this issue.

My patch - https://cables.gl/p/vPPAcC

It appears to be solid in the background.
<img width="1422" alt="Screen Shot 2566-07-26 at 00 28 19" src="https://github.com/cables-gl/cables_docs/assets/140542513/5977490d-7322-4316-bd5e-5767bd48ca6a">

I really appreciate any help you can provide.

**Comment by steam0r** [comment]
hard to tell without a link to the actual site, i think this is not an issue with the patch but something in wordpress is overlaying it and grabbing pointer-events or something
