### ISSUE TITLE
dragging cable to parameter panel errors

### ISSUE THREAD

**Issue by matti** [cables-gl/cables_docs#557]
**Describe the bug**

Tried to do this:

<img width="783" alt="image" src="https://github.com/cables-gl/cables_docs/assets/3893/bc6f883f-b2bc-4138-8f4f-d083849daf56">

**To Reproduce**

Do it and:

<img width="1547" alt="image" src="https://github.com/cables-gl/cables_docs/assets/3893/a1fd2f80-d03b-4aca-8c5c-c021ef4e4c16">

**Expected behavior**

Not fails

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome
 - Version latest stable

**Comment by steam0r** [comment]
this is fixed on dev.cables.gl, thanks for the report!

**Comment by steam0r** [comment]
this is now available on cables.gl with the last update
