### ISSUE TITLE
outdated tip on dragging

### ISSUE THREAD

**Issue by matti** [cables-gl/cables_docs#558]
**Describe the bug**

<img width="777" alt="image" src="https://github.com/cables-gl/cables_docs/assets/3893/e03a7dd2-cd8d-4ae9-8c8b-f1996453a090">

This is no longer true? Or just right click works?

<img width="448" alt="image" src="https://github.com/cables-gl/cables_docs/assets/3893/1bfa303c-0e38-4343-9de3-cc001013a5cf">

**Comment by steam0r** [comment]
removed the "shift" on dev, tip is still valid
