### ISSUE TITLE
Electron export doesn't work when selecting "multiple files" instead of patch.js

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#559]
The electron builds expects a patch.js which is not included if you select "multiple files".
It errors to 404 when running the app.

Thanks

**Comment by steam0r** [comment]
this is fixed on dev.cables.gl (and a tiny bit faster as well), feel free to check this out and give feedback. thanks for the report!

**Comment by steam0r** [comment]
this is now available on cables.gl with the last update
