### ISSUE TITLE
Comments do not update in patch correctly

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#56]
when deleting an op comment, the comment is not updated in the patch accordingly.
when you delete letter by letter, its only the last letter which fails. seems like it can't handle empty comments

![image](https://user-images.githubusercontent.com/1138673/129205770-4963dd4a-92f6-41e5-9735-690c0ade350f.png)

**Comment by pandrr** [comment]
thanks, fixed on dev.cables.gl

**Comment by steam0r** [comment]
made it's way to live
