### ISSUE TITLE
Quick way to get secret links

### ISSUE THREAD

**Issue by bbbbbgdn** [cables-gl/cables_docs#560]
I would love to get a way to copy (possibly to create) secret links easily from the gallery view. 
<img width="251" alt="258646301-ce2302d7-313c-46e1-8f9c-f60b9dbbbc80" src="https://github.com/cables-gl/cables_docs/assets/12091461/c1442973-e9c1-40f6-8cd1-a28a187a9c39">

**Comment by steam0r** [comment]
hm, the create and the link itself is actually one click away behind settings. isnt it?

**Comment by bbbbbgdn** [comment]
Kind of, but I use this heavily this feature for preview, and while having lots of patches, some of them already have links, some not, and you can’t tell.

Overall navigation and patch management feels quite limited. Would be really helpful to me to have this link (or just the secret URL param) at the fingertips.
