### ISSUE TITLE
New OP: RouteTriggerSequenced code included

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#562]
Made a new OP with documentation to sequence a route trigger by duration.

https://cables.gl/edit/FilU4D

Community seems to like it, we could include it in code maybe?

**Comment by steam0r** [comment]
hey, thanks for the code. trying to understand the "problem" i created this patch, trying to use existing ops:

https://cables.gl/p/HdkpqD

am i missing something or is your op basically a more convenient version of what i am doing? i guess the "loop" and "active/inactive" features can also be patches by triggering reset of the timer and working on the array...right=

**Comment by kikohs** [comment]
Pure convenience, you're right.

**Comment by steam0r** [comment]
i'd skipp adding this to core then, we have something up our sleeves in one of the next releases for exactly these situations :)
