### ISSUE TITLE
ArrayToTexture doesn't update by default - with fix

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#565]
ArrayToTexture doesn't create a texture by default even if an array is connected.

Because the texture is not null on initialization, the update method doesn't create the first texture.
Change to line 20 and set to null seems to fix the issue.

Attached patch: https://dev.cables.gl/edit/ZcZAQD

**Comment by pandrr** [comment]
thanks fixed on dev.cables.gl

**Comment by steam0r** [comment]
this is now available on cables.gl with the last update
