### ISSUE TITLE
Cube op has broken tangents (and other weirdness)

### ISSUE THREAD

**Issue by kebby** [cables-gl/cables_docs#569]
**Describe the bug**
- For some reason the tangents and bitangents of the top and bottom face are zero
- Bias has weird behavior when Flip X is on

**To Reproduce**
- Use the cube with a Phong/PBR material with a normal map, look at the top
- Turn Flip X on and off and observe how the texture changes when you change Bias

**Fix**
As both issues weren't hard to fix, here's an updated version in a test patch:

https://cables.gl/p/F_-puE

As a bonus, there's a third mapping mode now: "SideWrap". This is like Side but it includes the size in the texture coordinates to the texture doesn't stretch but wrap. Perfect for cubes with generic materials. :)

**Comment by pandrr** [comment]
fix applied on dev.cables.gl!

**Comment by pandrr** [comment]
btw  anti stretch  could also probably be done using basicmaterial texcoord params or the transformtexturecoords op

**Comment by steam0r** [comment]
this is now available on cables.gl with the last update
