### ISSUE TITLE
Websocket op example not found

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#57]
![image](https://user-images.githubusercontent.com/1138673/129212183-ed34f417-3447-4544-af1b-a1ae4311879d.png)

the link is wrong, probably due to v2

https://cables.gl/op/example/Ops.Net.WebSocket.WebSocket_v2
but 
https://cables.gl/op/example/Ops.Net.WebSocket.WebSocket
works

**Comment by steam0r** [comment]
works now, thanks!
