### ISSUE TITLE
Latest Brave Browser (Chrome based browser) makes cables crash permanently

### ISSUE THREAD

**Issue by tob-har** [cables-gl/cables_docs#576]
Updated BRAVE browser to the latest version:
[Version 1.57.62 Chromium: 116.0.5845.180 (Offizieller Build) (arm64)](https://brave.com/latest/)

now cables is not working anymore, always crashing after a couple of seconds, resulting in the errors below.
Think this is important issue, as BRAVE is a Chrome based browser and cables.gl was running completely fine before.

**cables error:**
Context lost
something went wrong. webgl context was lost. reload page or try restarting your browser

**console:**

[cgl_context] canvas lost...
cables.min.js?nc=1689757241670:1

WebGLContextEvent
isTrusted
: 
true
bubbles
: 
false
cancelBubble
: 
false
cancelable
: 
true
composed
: 
false
currentTarget
: 
null
defaultPrevented
: 
false
eventPhase
: 
0
returnValue
: 
true
srcElement
: 
canvas#glGuiCanvas-4ecfb8f3-29f3-4313-be15-710ffb947726
statusMessage
: 
""
target
: 
canvas#glGuiCanvas-4ecfb8f3-29f3-4313-be15-710ffb947726
timeStamp
: 
321195
type
: 
"webglcontextlost"
[[Prototype]]
: 
WebGLContextEvent

**Comment by pandrr** [comment]
so how is this cables fault then ? did you write them an error report ? :)

**Comment by pandrr** [comment]
![Uploading Screenshot 2023-09-12 at 09.42.36.png…]()

works for me

**Comment by tob-har** [comment]
> so how is this cables fault then ? did you write them an error report ? :)

Hehe... sure. Yelled at there support line. 
Thanks for checking on your side, will investigate what is the issue on my/browser side.

**Comment by Dyya** [comment]
I have the same issue but only on Windows.
