### ISSUE TITLE
GltfMeshSequence Node Name woes

### ISSUE THREAD

**Issue by kusma** [cables-gl/cables_docs#579]
The GltfMeshSequence node has a problem in its logic when matching a NodeName; It uses `if (cgl.frameStore.currentScene.nodes[i].name.indexOf(name))` to decide if a node matches.

However, this gives very unexpected results:
- If a node starts with the "Node Name", indexOf returns zero, and it doesn't get included
- If a node completely mismatches (eg "Node Name" isn't in the name at all), indexOf return -1, and it gets included.
- If a node matches at a positive index, it gets included.

I suspect that the logic was *intended* to search for all nodes with names that *contains* the "Node Name". If so, the appropriate logic would probably be to switch the condition to `if (cgl.frameStore.currentScene.nodes[i].name.indexOf(name) >= 0)`.

The documentation doesn't describe at all how the "Node Name" affects the search.

But, please don't change this without bumping the node version (or notifying us properly - you know how to reach us); we're currently in crunch-mode and depending on this behavior, because we need something we can use *now* :laughing:

**Comment by pandrr** [comment]
thanks! ...finally fixed this. in the new op version only meshes that starts with the string will be chosen
