### ISSUE TITLE
Intersect Body not rendering wireframe

### ISSUE THREAD

**Issue by k0mrad** [cables-gl/cables_docs#581]
Not seeing the Intersect Body wireframe anywhere. Tested on Prod and Dev. 
![image](https://github.com/cables-gl/cables_docs/assets/12103441/8bd7e9d6-1d34-4b73-a1c6-e24d25b8d354)

**Comment by pandrr** [comment]
<img width="380" alt="Screenshot 2024-03-21 at 11 15 17" src="https://github.com/cables-gl/cables_docs/assets/98792/39899f46-3074-4230-962c-c312a7b06b69">

you have to enable the option "show all helpers"
