### ISSUE TITLE
Use patches independently of the Internet

### ISSUE THREAD

**Issue by Nuuk23** [cables-gl/cables_docs#585]
Dear Community, 
I have the following question: I work in the performing arts and am currently developing several patches that will be used in a theater performance in different locations. I was wondering if it is possible to use ready-made patches independently of the Internet? There could be internet disruptions during a performance, which would be very disadvantageous at this moment. 
Could someone help me with this question? I would be very happy to solve this problem. Thanks!

**Comment by pandrr** [comment]
yes, you can export the patch and run it offline.
use export exe executable / electron packaging if you dont want to mess with a local webserver etc.
