### ISSUE TITLE
Using HTML heading tags will cause serious editor problems

### ISSUE THREAD

**Issue by multivitamin23** [cables-gl/cables_docs#588]
Hey cables friends, 
this may be a logical consequence, but changing the heading styles (h1-h6) with css op will cause stange behaviour with the cables interface. As you can see, it will lead to hidden textfields, ultralarge buttons and missing panels.

Is there another way to use and style headings?
Cheers, Multi.

![Screenshot 2023-10-13 000031](https://github.com/cables-gl/cables_docs/assets/117826951/d9901e22-7bee-4be4-aab2-f8b6552db766)

![Screenshot 2023-10-13 003216](https://github.com/cables-gl/cables_docs/assets/117826951/4e0ed765-ae90-411d-b3f6-3a864e59fdee)

**Comment by steam0r** [comment]
use something like `.cablesEle h1` to not interfere with "outside" html, also recommended for export

**Comment by pandrr** [comment]
updated the docs https://cables.gl/op/Ops.Html.CSS_v2

on dev.cables.gl the interference is way less now, but using cablesEle scope is much saver
