### ISSUE TITLE
Sidebar Group "show title" messes the first child element

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#59]
In the sidebar, if you add a group and toggle "Show title", the CSS is messed out for the first child element of the group.

The up arrow to collapse the group is not visible as well.
![Screenshot 2021-08-17 140917](https://user-images.githubusercontent.com/1793640/129723154-795a468e-dae3-4fdc-b44d-a32a3c72908b.png)

Easiest quick fix I found was to change the style to display: inline-block for the sidebar title.

```html
<div class="sidebar__group-header" style="display: inline-block;">...</div>
```

**Comment by steam0r** [comment]
fixed on dev

**Comment by steam0r** [comment]
made it's way to live
