### ISSUE TITLE
ImageCompose breaks AspectRatio Op

### ISSUE THREAD

**Issue by steam0r** [cables-gl/cables_docs#590]
### Discussed in https://github.com/cables-gl/cables_docs/discussions/580

<div type='discussions-op-text'>

<sup>Originally posted by **LJ1102** September 30, 2023</sup>
Having a sequence like MainLoop->AspectRatio->Sequence and then an image compose on the first port and some screen rendering on the second port of the sequence the aspect ratio op becomes ineffective, disconnecting the image compose has the aspect ratio work again.</div>

**Comment by pandrr** [comment]
aspect ratio will be deprecated in the next release, is confusing and is incompativle, force canvas size is a better way to do this
