### ISSUE TITLE
In the Explore page, searching requires log-in

### ISSUE THREAD

**Issue by anticore** [cables-gl/cables_docs#592]
**Describe the bug**
In the Explore page, if you're not logged in and attempt to use the search bar to search for a keyword, you are redirected to a login page.

**To Reproduce**
1. Log out
2. Go to 'https://cables.gl/patches'
3. Search for any keyword
4. See login page

**Expected behavior**
Since the whole of the Explore page is public if navigated through the pagination, there is no reason why searching should require a login. Searching while logged out should work normally.

**Screenshots**
<img width="1209" alt="image" src="https://github.com/cables-gl/cables_docs/assets/3611993/e992553d-0131-4d05-a397-6b1d1b83f88e">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 117.0.5938.149

**Comment by steam0r** [comment]
thanks for the report, this is already fixed on dev.cables.gl and the url moved to /patches to unify urls (just added a redirect to make sure these links work on dev)
