### ISSUE TITLE
Function_v2 Op: Wrong output value

### ISSUE THREAD

**Issue by timpulver** [cables-gl/cables_docs#594]
**Describe the bug**
The Functions_v2 op wrongfully sets the `Parameter 1` Port to `null`, although `Default Parameter 1` has a defined value.
This happens when triggering the op (via button in the sidebar). 

**How To Reproduce**
1. Open Editor
2. Add Functions_v2 op
3. Set Parameter 1–3 in the sidebar
4. Press `Trigger` in the sidebar
5. Compare output parameters to input parameters

I guess a `null` parameter is passed to the op somehow, causing the first parameter to be set.

**Platfowm**
 - Latest Arc on macOS 14

<img width="415" alt="Screenshot 2023-10-20 at 13 04 51" src="https://github.com/cables-gl/cables_docs/assets/1055819/ed5fba5a-cd43-4901-8e46-22db1f877f40">

**Comment by steam0r** [comment]
hey tim!

thanks for the report. op is fixed on dev.cables.gl.

best,
stephan

**Comment by timpulver** [comment]
Hi Stephan,
Great, thanks for the quick fix!
You keep the issue `open` until you publish a new changelog entry, right?
Best, 
Tim

**Comment by timpulver** [comment]
Ah, good to know 👍
