### ISSUE TITLE
CustomShader Op - Cursor not in Code after Shader Error

### ISSUE THREAD

**Issue by strangerattractor** [cables-gl/cables_docs#597]
Plead for a small quality of life improvement that would go a long way for me: 

To reproduce problem: 
1. write shader code 
2. make an error
3. press escape to get rid of the error message
4. Problem: The cursor is no longer in the code -> I can't continue writing immediately.
I have to click into the code to continue.

This adds up quickly when writing shader stuff...

Please Fix:
After Error message disappears, have the cursor active/write-ready at the previous position.

Thank you! 
Big love

**Comment by steam0r** [comment]
is this for the customshader op?

**Comment by strangerattractor** [comment]
Yes exactly!

**Comment by pandrr** [comment]
works again on dev.cables.gl

**Comment by strangerattractor** [comment]
yeaahh thx
