### ISSUE TITLE
Adding OP: CompObjectSetBoolean

### ISSUE THREAD

**Issue by tob-har** [cables-gl/cables_docs#599]
Suggestion: Adding a CompObjectSetBoolean to the CompObjectSet Family OPs.
The OP uses cables bool standards, but sets `true` and `false` instead of `true` and `0` 

Found this to be necessary in several situations, eg for composing API calls.

Find the OP here:

https://cables.gl/edit/wPLGEK

**Comment by pandrr** [comment]
what sets "true and 0" ?

**Comment by tob-har** [comment]
i updated the patch and added another op that uses `op.inBool` and later just `inBool.get()`.
it sets to `0` after switching input from true to false, not `false`.

**Comment by pandrr** [comment]
ah... fixed that, internally cables booleans should always be 0 or 1 

thank you for your ops. will rename them into the compops namespace

**Comment by pandrr** [comment]
renamed the op to a official one: https://dev.cables.gl/op/Ops.Data.Compose.CompObjectSetBool

**Comment by steam0r** [comment]
this went to cables.gl with the latest release
