### ISSUE TITLE
Issue with showing/hiding the sidebar from a trigger.

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#6]
Showing and hiding the sidebar using `default minimized` toggle doesn't really work when triggered by an external event.
It gets stuck on a position irrelevant of the bool op value connected to it.

The closing button icon is also hidden in the CSS and placed too low (should be top: -10px). However it also changes the default sidebar icon position when changing it.

It would be great if the sidebar would behave like the ModalOverlay with actual triggers to show/hide it.

**Comment by steam0r** [comment]
could you provide a simple example patch or video showing the behaviour? also browserinfo would be nice. thanks!

**Comment by steam0r** [comment]
are you using the wrong port? sidebar has a "visible" boolean that can be used for your purposes, i think, the "default minimized" is just setting the state of it when loading the patch initially.

**Comment by steam0r** [comment]
this works as expected, imho:

![Bildschirmfoto 2021-03-11 um 14 59 34](https://user-images.githubusercontent.com/151271/110798416-71b15480-827a-11eb-95df-e5e42c84814d.png)

**Comment by kikohs** [comment]
I meant to open or close the sidebar not to hide it completely. This is why I used the default minimized. 

I used an extra custom op to make sure it was close setting the right css class when wanted. Maybe we could add a open/close trigger?

**Comment by pandrr** [comment]
![screenshot_1617170466](https://user-images.githubusercontent.com/98792/113097490-41b0fd80-91f7-11eb-8de3-5f85b52b8883.png)

works for me

**Comment by steam0r** [comment]
this is now possible using the state of the out-port that indicates that is available on dev
