### ISSUE TITLE
FloorGrid produces invalid colors

### ISSUE THREAD

**Issue by pixtur** [cables-gl/cables_docs#609]
**Describe the bug**
![image](https://github.com/cables-gl/cables_docs/assets/1732545/faa883fa-211a-4241-b632-251a08fef165)

not related, but what's the purpose of Blur's Clamp parameter?
![image](https://github.com/cables-gl/cables_docs/assets/1732545/63369618-25f5-4f1e-87eb-4c08efc3e1b6)
![image](https://github.com/cables-gl/cables_docs/assets/1732545/a19d9ad6-2215-4669-a977-8d1979aa01b0)

This will lead to bad artifacts in combination with Additive Blur (glow)

**How To Reproduce**
1. [Open Editor](https://dev.cables.gl/p/on5GJL)

**Platfowm**
- Win10, Firefox218

**Comment by pandrr** [comment]
please set visibility to unlisted but with editor

**Comment by pandrr** [comment]
fixed on dev.cables.gl, thanks for the issue!

**Comment by pixtur** [comment]
Thanks!
