### ISSUE TITLE
"Save Image" Popup Menu on Chrome/iOS on /view/

### ISSUE THREAD

**Issue by strangerattractor** [cables-gl/cables_docs#610]
**Describe the bug**
A description of what the bug is. Screenshots also help a lot!

**How To Reproduce**
1. Open any patch in /view/ mode on iOS in Chrome Mobile 
2. Tap and hold somewhere
4. A Pop-up will appear: Result: ![image](https://github.com/cables-gl/cables_docs/assets/52496070/8595ebf7-0e67-4279-b5b6-8789256bd6b2)
5. Image to be saved is the cables background: 
![image](https://github.com/cables-gl/cables_docs/assets/52496070/c5eb0ae2-ab91-462b-b779-a89bf84b25ba)

**Platfowm**
iOS, Chrome Mobile

**Comment by steam0r** [comment]
this seems to be only on chrome iOS, chrome on android works fine, also seems to be fine in exported patches
