### ISSUE TITLE
PixelProjection example patch broken with pixel ratio >1

### ISSUE THREAD

**Issue by TobyKLight** [cables-gl/cables_docs#613]
**Describe the bug**
In the example patch for PixelProjection op the mouse cursor position is not accurately mapped to pixel space. 
https://cables.gl/op/Ops.Gl.PixelProjection_v2

**How To Reproduce**
For me if windows display scaling is set other than 100% this will create pixel ratio set to this display scaling.
However this is not always exact behaviour, seems to depend on some other browser magic. 

**Platform**
-Found this bug on windows 10 + Chrome 119
-Reproduced on android + chrome 119 

**Proposed Solution** 
Put Mouse op in 'pixel display' mode
Then multiply X and Y by the PixelRatio output from CanvasInfo 

Or perhaps Mouse op should have a built in compensation for this? Another Pixel mode? 

https://cables.gl/p/iLPqhM

**Comment by pandrr** [comment]
thx for reporting.

fixed on dev.cables.gl

**Comment by steam0r** [comment]
this went to cables.gl with the latest release
