### ISSUE TITLE
Patch ids should not containt special characters like -

### ISSUE THREAD

**Issue by pixtur** [cables-gl/cables_docs#621]
**Describe the bug**
Sometimes the patch ids like `zWjcaG` contain special characters like `zWj-caG`. This will prevent the CLI import flow to work correctly without escaping. It would be great if the id would only contain alphanumeric characters.

**Comment by steam0r** [comment]
this is now the case on dev.cables.gl (and id's created there are also valid on cables.gl)

**Comment by pixtur** [comment]
Thanks!
