### ISSUE TITLE
PointsPlane crash

### ISSUE THREAD

**Issue by TobyKLight** [cables-gl/cables_docs#629]
## Bug 
PointsPlane op will crash cables.gl if the rows input is set to infinity. 
Obviously this is not a valid input, but a crash is still undesirable. 

## Reproduce
Open this 
https://cables.gl/p/SPhuLM
Change the second input of the divide operation to zero, this will produce infinity as an input to PointsPlane

## Platform
Tested on windows with Chrome 119

**Comment by pandrr** [comment]
fixed on dev.cables.gl 

fyi. stuff like this will happen with lots of ops, division by zero is a bad thing anyway, many ops will have those problems and we will probably not fix everyone of them. 

we dont want to go the route to check every value every time and then have performance issues. this is basically programming with javascript and then you can get exceptions (what you call "crash")

**Comment by TobyKLight** [comment]
Thanks for quick fix

I only call it a "crash" because that's literally the text in the cables.gl UI. If its more accurately called an exception maybe it should be updated?

![image](https://github.com/cables-gl/cables_docs/assets/4467208/01e823ae-86b0-406b-bbbb-e175d642ecd6)

**Comment by steam0r** [comment]
this went to cables.gl with the latest release
