### ISSUE TITLE
Export to Github doesnt work

### ISSUE THREAD

**Issue by AdrianGreyish** [cables-gl/cables_docs#635]
**Describe the bug**
The user interface for Export to GitHub has changed, and I am no longer able to export the patch. I wanted to update an existing project, but got the **ERROR: exporting to github: could not find heads/main on github (500 - REF_NOT_FOUND).**
The Access Token is okay, but perhaps I am entering the information incorrectly in the UI?

![image](https://github.com/cables-gl/cables_docs/assets/105173884/5133ebf1-fb1e-4809-ba56-f56767b3f255)

**Comment by steam0r** [comment]
i will check if they changed anything in the api, could you check if that branch exists? you need to have:

`any repository, create one [here](https://github.com/new) if needed (add at least one file, otherwise the repo doesnt exists for github)`

usually github asks you if you want to create a README.md on creation, that should be sufficient

**Comment by steam0r** [comment]
we just fixed the inputs of that form on cables.gl and successfully exported a patch to a new repo that was created by github with just an README.md. 

the only new thing is that github now has a beta-test for "fine grained permissions". if you use this, make sure your token has "read and write" access to the "contents" of your repo:

![Bildschirmfoto 2023-12-12 um 11 00 26](https://github.com/cables-gl/cables_docs/assets/151271/9942fe01-dea4-49d7-b4ae-a79468a03e52)



i updated the docs accordingly: https://cables.gl/docs/4_export_embed/dev_embed/export_github/export_github

let me know if this worked for you. thanks!

**Comment by steam0r** [comment]
thanks for pointing out, sorry, i just fixed that. please try exporting again.
