### ISSUE TITLE
Extend LFO parameters

### ISSUE THREAD

**Issue by pixtur** [cables-gl/cables_docs#636]
In 90% of all my uses for LFO, I have to adjust its output range. 

I think it would be great add two parameters: 
- `RangeMin` (default -1)
- `RangeMax` (default 1)

This would also clarify the frequent misunderstanding, that most users will expect `Square` (yes, `Block` should be renamed), `Triangle` and `Ramp` to be in the range between 0 .. 1.

Alternatively a combined op that comes with its own timer (similar to [AnimLfo](https://github.com/tooll3/t3/wiki/lib.anim.AnimValue) ) would be great.

**Comment by pandrr** [comment]
thanks, good input, implemented in lfo_v2

**Comment by steam0r** [comment]
this is now on cables.gl!
