### ISSUE TITLE
Adjust default parameters values

### ISSUE THREAD

**Issue by pixtur** [cables-gl/cables_docs#637]
Some default parameters seem to be arbitrary and error prone.

I believe the following parameter defaults should be adjusted:

- MapRange.NewMin -> 0
- Sum.Number1 -> 0
- Sum.Number2 -> 0
- Multiply.Number2 -> 1
- ~~Color.RGB -> 1.0~~

**Comment by pixtur** [comment]
After using it for a while, I think that the random color in actually a nice touch.

**Comment by pandrr** [comment]
thanks, those values makes sense!

adding the op should by default not change the value that goes in.
same as, for example, scale operator should have the scale of 1 

adjusted default values on dev.cables.gl

**Comment by pixtur** [comment]
Thanks!
