### ISSUE TITLE
Easy access to native op code

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#638]
is it possible to have the easy access to op code to native ops like user ops. user ops have this pen button but native ops do not. i learned a lot from the native ops which is now little more tricky to do. at least not as easy as the user ops. 

having easy access to cables op code was/is one of the great things about cables. perfect learning resource.

<img width="286" alt="image" src="https://github.com/cables-gl/cables_docs/assets/1138673/a28fae85-d899-4c25-bf18-347bec583a55">

<img width="160" alt="image" src="https://github.com/cables-gl/cables_docs/assets/1138673/8d0a814a-4aac-4c3d-8556-9f31c5509cdb">

**Comment by pandrr** [comment]
hm yes. its kinda hidden in the ui.

for ALL ops you can press E for edit and you will see the source code

**Comment by wirmachenbunt** [comment]
E - thats awesome, i like it
