### ISSUE TITLE
VarTriggerObject / Array port ordering not consistent

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#641]
For string and number, we have trigger and port but not for VarTriggerObject / Array which is reversed.

<img width="232" alt="image" src="https://github.com/cables-gl/cables_docs/assets/1793640/ef987f55-0806-46b1-a710-8cad879cb411">

**Comment by pandrr** [comment]
done on dev.cables.gl

**Comment by steam0r** [comment]
this went to cables.gl with the latest release
