### ISSUE TITLE
Textures out of Subpatches

### ISSUE THREAD

**Issue by AdrianGreyish** [cables-gl/cables_docs#643]
**Describe the bug**
Textures out of Subpatches are bugged.
For example, the texture is not updated when it is connected to the Texture2ColorArray Op. Also the texture preview says that it is not an object type texture.

**How To Reproduce**
![image](https://github.com/cables-gl/cables_docs/assets/105173884/75362e4f-ab47-48f5-bc63-bcfa41533090)
I recreated the bug here.
https://cables.gl/p/TcUleO

Sending texture trough variables is functioning, even from subpatch to main.

**Platform**
Chrome, Win10, dev.cables

**Comment by steam0r** [comment]
we are reworking subpatches and focus on that, so this will not be fixed, sorry

**Comment by steam0r** [comment]
try new subpatchops on cables.gl with the new release!
