### ISSUE TITLE
mobile ops dont work

### ISSUE THREAD

**Issue by AdrianGreyish** [cables-gl/cables_docs#644]
**Describe the bug**
Ops _DeviceVibrate, ScreenOrientation and LockOrientation_ do not seem to work. I exported a test patch for mobile view on Chrome IOS. The bugged ops a on the bottom.

**How To Reproduce**
![image](https://github.com/cables-gl/cables_docs/assets/105173884/c447cc99-d81e-4eff-b76e-727a2c12bba6)
![image](https://github.com/cables-gl/cables_docs/assets/105173884/25bf5fd9-36b2-49a1-ac7a-9c3d00636919)

https://cables.gl/p/4IHdyO

Patch-Export without iFrame:
https://tattoo-flashes2.vercel.app/

**Platfowm**
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Sa"

**Comment by pandrr** [comment]
- op page for vibrate links to caniuse page, which tells you it does not work on ios
- lockorientation op page says "Note: This method only works for installed Web apps or for Web pages in full-screen mode"
- screen orientation gives you angle 0. looks correct.

those ops just use some web standards. we can not guarantee for them to work, they just output what they get from the browser, there is no way of circumnavigate this.
