### ISSUE TITLE
The "finished" trigger in Op.InOutInAnim is never triggered

### ISSUE THREAD

**Issue by esperanc** [cables-gl/cables_docs#645]
**Describe the bug**
Although the "started" and "middle" triggers work as expected, the "finished" trigger is never triggered, i.e., it is not triggered at the end of the animation

**How To Reproduce**
[Demo](https://cables.gl/edit/MQ3PHO)

**Platform**
 - Chrome on MacOS.

**Comment by pandrr** [comment]
thanks for reporting, fixed on dev.cables.gl will be fixed in the upcoming release

**Comment by steam0r** [comment]
this went to cables.gl with the latest release
