### ISSUE TITLE
Can't open Patch after deleting OP from the website

### ISSUE THREAD

**Issue by tiagomelobr** [cables-gl/cables_docs#648]
**Describe the bug**
I'm not able to open my patch after deleting an OP it used.

**How To Reproduce**
1. Open any Patch
2. Duplicate it using the global namespace
3. Go to [My Data, Ops](https://cables.gl/mydata#ops), click manage on the specific OP, and delete it
4. Try to open the Patch again

**Platfowm**
 - Desktop, Windows 11, Firefox 121.0
 - 
![image](https://github.com/cables-gl/cables_docs/assets/50590049/d066420d-9683-436f-8620-453f59af1aa9)

**Comment by steam0r** [comment]
hey,

how did you manage to delete the op? did you not see this warning?

![Bildschirmfoto 2024-01-02 um 11 54 32](https://github.com/cables-gl/cables_docs/assets/151271/055c4c04-5926-40bb-9e5c-4033f216e90b)

thanks!

**Comment by tiagomelobr** [comment]
Hey @steam0r,

hm, that's strange. I'm not sure, I believe the delete button was also in there. The warning is buggy with a white background, I might have missed the warning.

![image](https://github.com/cables-gl/cables_docs/assets/50590049/03e30ce4-7bf9-4644-9503-f9fa0d6a5fde)

It would be nice just to have a try/catch when loading the OPs, this way people wouldn't lose access to the Patch if something like this happens.

> hey,
> 
> how did you manage to delete the op? did you not see this warning?
> 
> ![Bildschirmfoto 2024-01-02 um 11 54 32](https://private-user-images.githubusercontent.com/151271/293677018-055c4c04-5926-40bb-9e5c-4033f216e90b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzOTI5NzUsIm5iZiI6MTcwNDM5MjY3NSwicGF0aCI6Ii8xNTEyNzEvMjkzNjc3MDE4LTA1NWM0YzA0LTU5MjYtNDBiYi05ZTVjLTQwMzNmMjE2ZTkwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxODI0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGU5N2ZjMWU5ZjdjZTAzM2I0MzQwNjNmZDM4Njg2NzViYjU2MzljNDJlZDM0Y2MwOTU3MjQxZGY1NzY3OGJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r7ewM_NKNBFOZB5ru_f5nvcf6Q924C4zSweFmSDZOOg)
> 
> thanks!

**Comment by steam0r** [comment]
yeah, we are thinking about showing the warning/error but loading the patch anyhow so you can still recover and fix whatever is broken. the only way i could reproduce your behaviour was by copypasting a deleted op to an already open patch though...not sure if that is how you got into this mess...would be interesting to know how to reproduce.

am i getting you right in that you are using "light theme" for the website and the errors/warnings look like in your screenshot? if thats the case, we will definitely look into this.

**Comment by pandrr** [comment]
bright theme is repaired and it should look fine.
