### ISSUE TITLE
TextTexture inconsistent behaviour

### ISSUE THREAD

**Issue by esperanc** [cables-gl/cables_docs#652]
**Describe the bug**
I detected two inconsistencies in the way TextTexture behaves. 

 1. The computed line height varies unpredictably. By looking at the op code, I noticed that the height of every line is computed as the maximum over the heights of all lines in the text, as estimated by fields actualBoundingBoxAscent and actualBoundingBoxDescent of the font metrics object. This gives widely varying results even with text containing the same mixture of characters. 
 2. The font and background colors are not checked for change, which makes color animation unfeasible. 
 
I prepared a demo for the problem, together with a fixed custom TextTexture op in https://cables.gl/edit/vr_wmP

Here's a screenshot:
![cables_202415_144652](https://github.com/cables-gl/cables_docs/assets/1062177/77b65c61-fd1a-4198-90f5-744e99ea0492)

**How To Reproduce**
1. Use the TextTexture op with fixed width and height, disable "auto line breaks", use a fixed width font like Courier or Monospace with a small size such as 10 or 20. Also, use a fairly big text with many lines. Line heights should be equal. The demo showcases this by creating random texts with uppercase and lowercase letters.
2. Try to animate either the font color or background color.

**Platform**
 - Version 120.0.6099.129 (Official Build) (arm64) on a MacBook Pro 14in 2021

**Comment by marioepsley** [comment]
Noticed the same, I guess I should be writing bugs here as opposed to discussions. My bad
https://github.com/cables-gl/cables_docs/discussions/593

**Comment by esperanc** [comment]
The fix I proposed to the line height issue is to use fontBoundingBoxAscent and fontBoundingBoxDescent rather than actualXXX. Also, I found that computing this on all lines is overkill, i.e., a single line is enough, or even better, a fixed string. Take a look at the modified op in the included demo.

**Comment by pandrr** [comment]
i did not use that, because firefox did not support it, looks like it does since august 23: https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics/fontBoundingBoxAscent

**Comment by pandrr** [comment]
- font and backgroundcolor are animatable for me, but should be used for animations because there are faster ways.
- changed the the actual* font metrics to fontBounding*, seems to work fine, can be testesd in op version 6 on dev.cables.gl

**Comment by steam0r** [comment]
this went to cables.gl with the latest release
