### ISSUE TITLE
gui.StartModalLoading is not a function

### ISSUE THREAD

**Issue by jens-a-e** [cables-gl/cables_docs#654]
**Describe the bug**
When creating a new port on a sub patch op after clicking "save" in the dialogue, this error occurs and the port is not created.

**How To Reproduce**
1. Select an existing SubPatchOp
2. Mange Op
3. Click the plus icon in the ports section
4. Fill out the form for a new port
5. Click save

**Platform**
 - Chrome macOs

**Comment by pandrr** [comment]
thanks for reporting.
this feature was 3 days old and very much work in progress.

please dont use dev features in production.

https://cables.gl/docs/faq/general/dev/dev

**Comment by jens-a-e** [comment]
no worries :)

the subpatch ops are great, though.

thx!
