### ISSUE TITLE
Op description page fields do not escape HTML

### ISSUE THREAD

**Issue by chrsmlls333** [cables-gl/cables_docs#655]
**Describe the bug**
I included the text <script> in my op description and now that page is broken as it created an unclosed script element for the rest of the page.

This shows that the entry field is not escaping HTML tags

![image](https://github.com/cables-gl/cables_docs/assets/7692426/2c02b765-5fba-4152-aa10-162aee1aa841)

**How To Reproduce**
1. See here https://cables.gl/op/Ops.Patch.PikgdeK.FxHash_v3
2. To reproduce, add a `<script>` word to any description.

**Platfowm**
Chrome 120 on Windows

Sorry~!

**Comment by pandrr** [comment]
thank you for reporting. i deployed a quickfix. that should not happen. will to do some more checks...

**Comment by chrsmlls333** [comment]
Thank you for the quick fix!
