### ISSUE TITLE
Patch Background Mode Doesn't Show Ops

### ISSUE THREAD

**Issue by andrejhronco** [cables-gl/cables_docs#658]
**Describe the bug**
When clicking on the `Patch Background` button below the canvas only the render shows. Previously, the patch Ops would show over the render.

**How To Reproduce**
1. Open Editor
2. Click on "Patch Background" button
3. observe that no Ops are shown

**Platfowm**
 - macOS 14.3, Chrome 120
 
 
<img width="1135" alt="image" src="https://github.com/cables-gl/cables_docs/assets/1925905/1907948f-1b3e-4ec7-9d8d-2373d6157689">

**Comment by pandrr** [comment]
thanks, fixed on dev.cables.gl

**Comment by steam0r** [comment]
this went to cables.gl with the latest release
