### ISSUE TITLE
Op Docs Squished Op Image

### ISSUE THREAD

**Issue by andrejhronco** [cables-gl/cables_docs#659]
**Describe the bug**
In the doc for an Op the Op Image is squished if it's a long Op like PhongMaterial. There is a fixed size on this image and it should be allowed to fill it's container

**How To Reproduce**
1. Open [PhongMaterial Op](https://cables.gl/op/Ops.Gl.Phong.PhongMaterial_v6)
2. Observe the squished Op image

**Platfowm**
 - macOS 14.3, Chrome 120

<img width="711" alt="image" src="https://github.com/cables-gl/cables_docs/assets/1925905/51ddde84-6706-4bb6-b32d-b0350806eccf">

**Comment by steam0r** [comment]
this went to cables.gl with the latest release
