### ISSUE TITLE
Support pointer events in Ops.Html.EventListener

### ISSUE THREAD

**Issue by jens-a-e** [cables-gl/cables_docs#660]
Hi

Would it be possible to support `PointerEvent` such as `pointerdown`, `pointerup`, etc in [Ops.Html.EventListener](https://dev.cables.gl/op/Ops.Html.EventListener)?

This is useful when working on patches which are running on touch screens and other screens. While the `click` event fires, it would be great to have access to the `up` and `down` events without connecting two cables every time.

The `PointerEvent` types fire on mouse and touch.

A separate Op such as PointerEventListener also do the trick. We currently use a CustomEventListener.

Thanks in advance :)

**Comment by pandrr** [comment]
fyi: mousebuttons op listens to both types of events!

**Comment by jens-a-e** [comment]
Thx. I saw that, but I need to attach to HTML Elements. The global MouseButtons Op doesn't help here.

**Comment by pandrr** [comment]
hi, 

thanks, decided to clean this all up...

on dev there is now Ops.Html.Event.ElementPointerEvents_v2 , the old op will be deprecated/renamed.

there is also ElementEventListener, which can be used to capture one event by name
