### ISSUE TITLE
Constant closing of the input when entering  a dropbox url for an asset 

### ISSUE THREAD

**Issue by k0mrad** [cables-gl/cables_docs#668]
Sometimes urls need to be adjusted after pasted (in the case of dropbox, we need to always change www to dl in order to get direct access to a file). This is made difficult by the input closing right away. https://www.dropbox.com/s/hwzcwt1ozoovun9/cables-error.mov?dl=0

**Comment by pandrr** [comment]
thx, this is annoying, will look into it
