### ISSUE TITLE
Op Settings close  immediately

### ISSUE THREAD

**Issue by AdrianGreyish** [cables-gl/cables_docs#670]
**Describe the bug**
1. Forcing the Cables-Selection Button to the foreground in front of the ops disrupts the workflow in certain large patch setups.

2. In subpatches, the settings menu of ops cannot be accessed. It briefly opens but immediately closes, particularly when multiple cables are positioned behind it. (See video for reference.

**How To Reproduce**

**Platfowm**
Win10, Chrome

https://github.com/cables-gl/cables_docs/assets/105173884/56ccc650-f8e6-4fd0-b14f-486e8d9dce4f

**Comment by pandrr** [comment]
can you invite me into the patch or copy it into an example ?

**Comment by pandrr** [comment]
should be fixed on dev.cables.gl, will be on cables.gl later. 

let me know if this happens again.

great patch :)

**Comment by steam0r** [comment]
made it's way to cables.gl!
