### ISSUE TITLE
"Marked is not defined" error

### ISSUE THREAD

**Issue by mediajolt001** [cables-gl/cables_docs#677]
Trying to load a patch that was working fine a couple of days ago. Now loading is halted with a "marked is not defined" error
<img width="1440" alt="Screenshot 2024-02-05 at 10 43 11 AM" src="https://github.com/cables-gl/cables_docs/assets/11758783/5412175d-9d3c-4533-955c-c77cd08887f9">

Reproduce by trying to load this URL: https://cables.gl/edit/jvrL33

Running on Arc (uses the Chrome renderer on MacOS 14.2.1 on a 13" MacBook Pro 13"

**Comment by constructor** [comment]
I have multiple of these on many of my saved patches.
I have clicked the "Send Error Report" button to inform the guys.
Can't seem to do anything at the moment, so will have to wait.
I understand there was a big update recently, but have not had much success so far, but I am certain these wrinkles will be ironed out soon enough.

**Comment by pandrr** [comment]
please try to clear your cache or shift-reload the page. is it gone then ?

**Comment by constructor** [comment]
> please try to clear your cache or shift-reload the page. is it gone then ?

Yes, that seems to have resolved the issue.
