### ISSUE TITLE
Cable behind subpatch creates in and outs by accident

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#68]
![image](https://user-images.githubusercontent.com/1138673/134044142-30793b5b-6524-4d19-b3bb-6fab8245a8e1.png)

if a cable is behind a subpatch and you double click the subpatch to edit it, it generates inputs and output pins instead of navigating into the subpatch. 

the subpatch hittest should have priority to avoid this.

**Comment by pandrr** [comment]
should be fixed on dev
