### ISSUE TITLE
PointCloudFromArray no longer updates

### ISSUE THREAD

**Issue by constructor** [cables-gl/cables_docs#680]
**Describe the bug**
In the following example the PointCloudFromArray no longer updates from Texture2ColorArray.

Example: https://cables.gl/edit/CakTw3

**How To Reproduce**
1. Open the example
2. Use the OrbitControls to move the head around
3. The PointCloud no longer updates as it once did (this is from a previously working patch)

**Platfowm**
 - Windows 11 with all updates applied
 - Chrome Version 121.0.6167.140 (Official Build) (64-bit)

**Comment by pandrr** [comment]
please change your patch to unlisted with editor to see it.

**Comment by constructor** [comment]
> please change your patch to unlisted with editor to see it.

Done.

**Comment by pandrr** [comment]
thanks for reporting.

renderToTextures was not outputting an updated texture every frame.

it now works correctly on dev.cables.gl and will be updated on cables.gl with the next release
