### ISSUE TITLE
Subpatch ops not executing in remote viewer windows

### ISSUE THREAD

**Issue by TobyKLight** [cables-gl/cables_docs#686]
**Describe the bug**
The new subpatch ops do not seem to be executing in remote viewer windows.

**How To Reproduce**
1. Open this test patch 
https://cables.gl/p/WL0cU3
Notice the two pink rectangles are drawn by subpatch ops. 

2. Open a remote viewer window from the menu and for me at least the pink rectangles are not visible.

Note the pink rectangles do appear using the 'view patch page' option

**Platform**
- Tested on Windows Chrome Version 121.0.6167.161 (Editor + Remote Viewer) 
- Tested on Android Chrome 121.0.6167.164 (Remote viewer only)

**Comment by TobyKLight** [comment]
Same thing if you join multiplayer on an editor window

**Comment by TobyKLight** [comment]
As of 11.02.24 looks like this is already fixed on dev.cables.gl...

**Comment by TobyKLight** [comment]
oops didn't mean to hit completed button

**Comment by pandrr** [comment]
yeah i applied a quickfix, needs some more testing, let me know if there are more problems
