### ISSUE TITLE
SubPatch output type not recognised

### ISSUE THREAD

**Issue by constructor** [cables-gl/cables_docs#691]
**Describe the bug**
SubPatchOutput causes "Error: Object in port Texture 2 is not of type texture"

**How To Reproduce**
1. Open example: https://cables.gl/edit/MLi1g4
2. Connect the 'BeatFlash' SubPatch output tot the MultiDrawImage's second texture
3. Error appears

**Platform**
- Windows 11 with all updates applied
- Chrome Version 121.0.6167.140 (Official Build) (64-bit)

**Comment by pandrr** [comment]
yes, i fixed this on dev.cables.gl today, will be updated very soon on cablesa.gl

**Comment by constructor** [comment]
OK! Great news. You guys are fast!
