### ISSUE TITLE
op.CallBack() does not work unless some parameters are included

### ISSUE THREAD

**Issue by cristianvogel** [cables-gl/cables_docs#694]
**Describe the bug**
op.CallBack() does not work unless some parameters are included. 
There are some parameter fields, string type, and if nothing is added there, the callback doesn't get sent 

this works
<img width="297" alt="Screenshot 2024-02-15 at 12 34 13" src="https://github.com/cables-gl/cables_docs/assets/12829050/1146d5f4-8635-425b-b4c1-1e57c12cb95f">

this doesn't
<img width="297" alt="Screenshot 2024-02-15 at 12 34 34" src="https://github.com/cables-gl/cables_docs/assets/12829050/cf0b2451-0207-4ee1-a24f-b898cc161e83">

**How To Reproduce**
try to trigger a function in an embedded context using op.CallBack() with no params

**Platform**
 Chrome, Mac

**Comment by steam0r** [comment]
hey, i tried to reproduce this, using this op and do not encounter the problem when exporting from live or dev

https://cables.gl/op/Ops.Cables.CallBack_v2

is this what you use? are you sure you are registering your function correctly?

https://cables.gl/docs/4_export_embed/dev_embed_functions/dev_embed_functions

`CABLES.patch.config.randomiseAllNodes = function() { console.log("HELLO"); }`

or do you mean something else by `op.CallBack()`?

**Comment by cristianvogel** [comment]
Yeah, I was using that. But ok, maybe if you can't recreate, maybe something else.
