### ISSUE TITLE
VizTexture Preview Weird Colors

### ISSUE THREAD

**Issue by dudumaluf** [cables-gl/cables_docs#699]
When using viztexture, now its preview seems to be somehow always with over saturated colors.
The small image preview on top of the op was me hovering the cable which was showing what the texture should look like, but as you see the viztexture shows something else.

![image](https://github.com/cables-gl/cables_docs/assets/16579360/95a35908-8583-45dd-abdf-ccaa8e70b269)

**Comment by pandrr** [comment]
please make an example patch i can't reproduce it

**Comment by dudumaluf** [comment]
![image](https://github.com/cables-gl/cables_docs/assets/16579360/de5f9243-eb3c-4438-a12f-047972deb221)
https://dev.cables.gl/p/v7lBS5

**Comment by pandrr** [comment]
strange, only happening on windows.....
