### ISSUE TITLE
WebcamTexture OP generates warnings and error by default

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#7]
Putting a WebcamTexture op in a patch results in errors in the console even though it works.
The default example patch has the same issue.

![Screenshot 2021-02-25 150607](https://user-images.githubusercontent.com/1793640/109165353-bd90d380-777b-11eb-8900-83835a60733c.png)

**Comment by kikohs** [comment]
On the same topic, I've updated my WebcamTextureTrigger OP, it should be more robust. I have tested with several cameras at the same time.

https://cables.gl/edit/x8Rkiy

**Comment by steam0r** [comment]
working on a new version that will fix these issues
