### ISSUE TITLE
ThinkSpeak Op Issues

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#70]
**Describe the bug**
Hi! I'm trying the ThinkSpeak Ops (Write, Read and LastEntry) first of all, it's string inputs are outdated so i can't add the api key because only gets values and not strings.

I used the StringNew2Old Op to fix this successfully, but i can see that the entries are registered in the ThinkSpeak site channels  but with no values and of course i added numeric values on that section in cables, i hope to it will be posible to put strings... 

![ts](https://user-images.githubusercontent.com/65823796/137343569-586afea3-5eaf-4d94-8cf4-e01838069544.jpg)

Windows10
Chrome

**Comment by n4hui** [comment]
Thank you very much, the Op Works in Dev, but the problem remains, it enters an entry but with no values, i guess it is only numerical but the fields are still empty 
![Captura de pantalla 2021-10-20 110344](https://user-images.githubusercontent.com/65823796/138129607-312c941a-85b6-4384-996f-0fef2ddcf410.jpg)
![Captura de pantalla 2021-10-20 110410](https://user-images.githubusercontent.com/65823796/138129609-1f6071a7-2d86-42fc-91d0-768366c7ae67.jpg)

**Comment by steam0r** [comment]
hey,

sadly cant really test this sind thingspeak appears to need a matlab licence off of me. i took the freedom of using your apikey for writing, which seems fine. reading needs a channel-id. maybe you can provide these to me for testing in private on discord? thanks!

**Comment by n4hui** [comment]
Ok i sent it to you in discord

**Comment by steam0r** [comment]
thanks for that, bug in ReadEntries is fixed on dev

**Comment by steam0r** [comment]
because in your screenshot you write to the field "cod": that doesnt exist in your channel, writing to "field1" works. it seems thingspeak ignores your mappings somehow...this should be easier to find out now with actually getting entries:
![Bildschirmfoto_2021-12-08_um_17 46 37](https://user-images.githubusercontent.com/151271/145250195-5fb3088c-1bf1-44c9-9a5b-4bed108cee67.png)

**Comment by n4hui** [comment]
Now it works, thank you!
