### ISSUE TITLE
Timeline only works with inspector displaying value

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#71]
Description
The timeline only plays (animates values) when the value is displayed in the inspector. You need to select the op to make it work.
When the animation is happening, it looks very rough, jittery. Is this a user error or a bug ?

Here is a demo.
https://cables.gl/p/616d636bb8a9a95ab2d05ab9?s=Stezo5NQj1o9wbHy

**Comment by tastez** [comment]
@wirmachenbunt please try https://cables.gl/op/Ops.TimeLine.TimelineValue for animating values

**Comment by pandrr** [comment]
right now animations need a trigger op, e.g. `setNumberOnTrigger`
we will fix this problem soon

**Comment by wirmachenbunt** [comment]
> right now animations need a trigger op, e.g. `setNumberOnTrigger` we will fix this problem soon

cheers, this works for now

**Comment by steam0r** [comment]
now also fixed on live
