### ISSUE TITLE
ForceCanvasSize causes mobile viewer (remote and patch view) to not work

### ISSUE THREAD

**Issue by tob-har** [cables-gl/cables_docs#719]
When usign ForceCanvasSize under mainloop, a patch can not be opend in remote viewer/patch viewer on mobile 
any more. (checked, brave, chrome and FF on iOS):
Mobile Website keeps reloading permanently.

Fixed, as soon as ForceCanvasSize is removed.

**Comment by pandrr** [comment]
works fine for me, example ?

**Comment by tob-har** [comment]
checked it again in a blank patch, no problem there. Seemed to be a temporary issue on my side.
