### ISSUE TITLE
Preset Op - Enter a custom title for this port does not update

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#73]
**Describe the bug**
when changing a port name, it does not update after pressing ok, you need to reselect the Preset op

![image](https://user-images.githubusercontent.com/1138673/137918042-839ab15a-1d4d-42be-98a5-0c56c757e0de.png)

**Comment by pandrr** [comment]
fixed on dev

**Comment by steam0r** [comment]
fixed on live ;)
