### ISSUE TITLE
MeshInstancer / ArraySpray : get Index

### ISSUE THREAD

**Issue by 60-hz** [cables-gl/cables_docs#737]
Would be super handy to get instance Index number as output for MeshInstancer, ArraySpray, and AmmoEmitter like repeat do, for all iterations processes.

**Comment by pandrr** [comment]
they are not iterated they are all drawn with one drawcall.

**Comment by 60-hz** [comment]
Oh yeah thanks, it makes sense for MeshInstancer.
But ArraySpray could allows indexes at least?
I didn't find an easy way to make different text name for every particles with current implementation without writing a special Op yet.

**Comment by pandrr** [comment]
arrayspray always outputs the same number of particles

**Comment by 60-hz** [comment]
Ok, using it with the fixed version of ArrayTranslate is very easy now.
