### ISSUE TITLE
Patch Bricked Overnight

### ISSUE THREAD

**Issue by sebastianpetrovski** [cables-gl/cables_docs#738]
A patch I've been working on seems to have bricked itself over night.

Among other things, it seems like any bools lost their state.

Here's a list of things I found so far:

-Mainloop was set to inactive and all bool options also set to 0
-any DivElements have had all the boolean options set to 0
-Mesh Renderers set to inactive
-any loose BoolOps were set to 0
-AudioBuffers had their create loading status set to 0 and play set to 0
-CSS ops all turned off
-CSS3D elements seem to have their scaling completely out of wack
-plus I guess much more because I haven't figure out how to get the patch working again (its big and messy)

this div was not a tiny dot last time i checked 😂 all the other divs are behaving strangely also
![image](https://github.com/cables-gl/cables_docs/assets/74696962/181ba978-f812-47a0-8b78-eb012c38f76e)

The backup from yesterday is bricked too.

I was able to restore a back-up from 2 days ago and saved it with a new patch name for safety.

The version on dev seems to be working, however it's throwing an error that wasn't there before and I haven't fully tested it yet.
![image](https://github.com/cables-gl/cables_docs/assets/74696962/a7e3bbf8-2ff2-49ab-9381-4eeef9b2f08f)

I've got backup json files from my embed exports yesterday, but I don't know how to get them back into cables. The documentation says something about re-importing but I can't find that option - is it possible?

**Dev Tools**
screengrab of the inspector viewing the bricked patch in the editor on main site
![image](https://github.com/cables-gl/cables_docs/assets/74696962/54e85b76-212b-4eb0-a5a8-ef888f096de4)

**extra note**
I just saw this on main cables - I guess I bricked it by testing something on dev, saving and then re-opening on main?
![image](https://github.com/cables-gl/cables_docs/assets/74696962/4340e5eb-901e-4a9a-9936-d83ce22d4241)

**Comment by pandrr** [comment]
it is not bricked, it will continue to work on dev.cables.gl, but you can't open it on regular cables.gl until the next update. 

i hope that helps. otherwise you could load an old backup

**Comment by sebastianpetrovski** [comment]
Ok, cool - easy - thanks for the quick reply Pandrr!

**Comment by pandrr** [comment]
deployed a hotfix. patches saved on dev should now load on normal cables.gl without problems

**Comment by sebastianpetrovski** [comment]
Thanks Pandrr! Just checked and the patch works on normal cables.
