### ISSUE TITLE
GetValuesFromArrayOfObjects doesn't look up the prototype chain

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#74]
The current implementation uses

``` if (obj && obj.hasOwnProperty(key) ) ... ``` to check whether the key exists.

But the API should be able to check the prototype chain for the key if it is defined in parent classes.
Example, I'm parsing the DOM and need to access the `innerText` property. It fails with the current implementation.

Here the fix line 27.

```
  if (obj) {
      if (!(key in obj))
          return;      
...
```

**Comment by steam0r** [comment]
made it's way to live today
