### ISSUE TITLE
Unpublished patches are not visible as user "Featured Patch"

### ISSUE THREAD

**Issue by dino5711** [cables-gl/cables_docs#75]
**Describe the bug**
When you go on a users page it displays a 403 Error in the "Featured Patch" section when the patch is not published.

**To Reproduce**
1. Go to for example https://cables.gl/user/ratsnake
2. See error (Screenshot)

**Expected behavior**
See the patch the user has selected as "Featured Patch".

**Screenshots**
![image](https://user-images.githubusercontent.com/51714036/139143429-44530f09-addd-4458-afa1-1752e43e52f9.png)

**Additional context**
To solve the problem either allow unpublished patches to be visible or make only published patches available to select.

**Comment by steam0r** [comment]
users are no longer allowed to select private patches as featured patches

**Comment by steam0r** [comment]
also not possible on live anymore, now
