### ISSUE TITLE
WebcamTexture don't update on external canvas

### ISSUE THREAD

**Issue by 60-hz** [cables-gl/cables_docs#751]
When using "Popout Canvas", the camera stop udpating in the patch.
Tried with the example of WebcamTexture...

Works with ExternalCanvas Op

**Comment by pandrr** [comment]
the browser needs a new user interaction. e.g. toggle the active input with your mouse.

it is not really detectable when this changes etc.

**Comment by 60-hz** [comment]
Ok, that makes sense, thanks.
