### ISSUE TITLE
Presets Op : add Op's "text" fields

### ISSUE THREAD

**Issue by 60-hz** [cables-gl/cables_docs#756]
Would be very handy to include the Op "text" entries when creating a preset and not only "id" &  "objName" which are less meaningful when we want to edit json external.

**Comment by steam0r** [comment]
hm, what do you mean by "text" and how are you generating the json externally? in general objName is not a good thing to rely on, since we sometimes rename or deprecate ops. which then would break your preset.

**Comment by pandrr** [comment]
click the three dots menu next to the port, click "remove custom title" and then click again "edit title"

this op is not used a lot and probably should be deprecated because strange behaviour

**Comment by 60-hz** [comment]
When working on complex projects, it's nice to store variables in human like format like json.
Preset op in sidebar is handy because it create a string that can be parsed with all the program variables.
But if I want to edit manually this file, the names of the variables ("text") are not present so it's difficult to edit it.

Here is a sample of my preset formated with Pretty JSON addon in Sublime:

    "ops":
    [
        {
            "id": "id861618897",
            "objName": "Ops.Sidebar.SideBarSwitch",
            "ports":
            {
                "Index": 0
            }
        },
        {
            "id": "id58824562",
            "objName": "Ops.Sidebar.Slider_v3",
            "ports":
            {
                "Result": 1
            }
        },
        {
            "id": "id-1146164907",
            "objName": "Ops.Sidebar.Toggle_v3",
            "ports":
            {
                "Value": 0
            }
        },
        {
            "id": "id1664347139",
            "objName": "Ops.Sidebar.DropDown_v2",
            "ports":
            {
                "Index": 2
            }
        },

**Comment by steam0r** [comment]
i pushed a small change on dev.cables.gl that will add text/title/label to the json in the preset. this is ONLY added for orientation purposes and not used in deserialize, changing the title externally does nothing.

this is the least-breaking change i can make, i hope this helps a bit to give more orientation when manually working with this data

**Comment by steam0r** [comment]
we changed this to contain the title of the op, not the textfield, this is a more stable solution. if you need to distinguish the ops in the preset json, change the title of the op.

![Bildschirmfoto 2024-06-03 um 10 30 04](https://github.com/cables-gl/cables_docs/assets/151271/df7f2654-73ef-4d23-a375-4a366483193e)
