### ISSUE TITLE
TriggerBetween extends range by +1

### ISSUE THREAD

**Issue by dino5711** [cables-gl/cables_docs#76]
**Describe the bug**
The TriggerBetween Op is triggering values up to +1 higher than set.

**To Reproduce**
1. Set Number2 10  .
2. Extend Index to 11.
3. Observe Trigger route.

**Expected behavior**
Trigger should stop at Index > Number2.
Code says:

```    
if(
    inIndex.get()>=Math.floor(inNumber1.get()) &&
    inIndex.get()<=inNumber2.get()+1
    )
    {
    ...
    }
```
There is a "+1" added to inNumber2.get that most likely causes the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/51714036/139477190-390bacc0-671b-4339-b14a-cc208a7e921a.png)

![image](https://user-images.githubusercontent.com/51714036/139477041-3ba2b2f3-45b0-4abb-ae3b-ef7456a386cb.png)

**Comment by dino5711** [comment]
I see why the +1 is there. If you use the same index in TriggerBetween and for e.g.  ArrayGet... the last index isn't loaded correctly as it isn't updated within the same Trigger.

I added "oneMoreTrigger" to the Op and it looks like it is working.

Code:

```
var exe=op.inTrigger("Exe");

var inIndex=op.inValueInt("Index");
var inNumber1=op.inValueInt("Number 1");
var inNumber2=op.inValueInt("Number 2");

var next=op.outTrigger("next");
var outFract=op.outValue("Fract");

var oneMoreTrigger=false;

exe.onTriggered=function()
{
    if(
        inIndex.get()>=Math.floor(inNumber1.get()) &&
        inIndex.get()<=inNumber2.get()
        )
        {
            var diff=inNumber2.get() - inIndex.get();
            oneMoreTrigger=true;


            if(inIndex.get()>Math.floor(inNumber2.get()))
            {
                outFract.set( 1.0+(inNumber2.get()-inIndex.get() ));
            }
            else
            if(inIndex.get()<inNumber1.get())
            {
                outFract.set( 1.0-(inNumber1.get()-inIndex.get() ));
            }
            else outFract.set(1);

            next.trigger();

        }
    else if(oneMore === true)
        {
            next.trigger();
            oneMoreTrigger=false;
        }

};
```

**Comment by steam0r** [comment]
try using the IfTrueThen Op with a Between Op, that should work better

**Comment by steam0r** [comment]
fixed on live since todays release
