### ISSUE TITLE
MultiDrawImages crashes when connecting more than 15 textures

### ISSUE THREAD

**Issue by dino5711** [cables-gl/cables_docs#77]
**Describe the bug**
MultiDrawImages crashes when connecting more than 15 total textures.
8 Textures + 7 Masks works, 7 Textures + 8 Masks also. 8 Textures + 8 Masks crashes.

**To Reproduce**
1. Put 8 Textures on the MultiDrawImage Op
2. Add Masks.
3. When adding the 8th Mask the Op crashes

**Expected behavior**
Op Should work with all Texture ports connected

**Additional context**
Copied the code to extend the MultiDrawImage Op to 10 sets.
Works with 10 Textures and crashes when adding the 6th Mask.
I guess 15 is the magic number.

**Desktop:**
 - OS: Windows 10 20H2
 - Browser: Chrome
 - Version: 96.0.4664.27

**Comment by pandrr** [comment]
its a limitation of your webgl implementation:

https://cables.gl/browser

max vertex texture image units: 16

but it should display an error, yes

**Comment by steam0r** [comment]
this went live today. thanks for the report!
