### ISSUE TITLE
GltfNodeTransform op example is broken and only displays 0.

### ISSUE THREAD

**Issue by basscadet** [cables-gl/cables_docs#78]
**Describe the bug**
Example scene of the GltfNodeTransform operator is broken. X Position is always 0. Connection between 2 operators (GltfNodeTransform and Round) seems to be cut.

**To Reproduce**
1. Go to https://cables.gl/op/Ops.Gl.GLTF.GltfNode_v2 or https://cables.gl/edit/5f22be3fd96c161e381171a2
2. See error

**Expected behavior**
X position value should increment when the cube moves.

**Screenshots**
<img width="701" alt="Screenshot 2021-11-02 at 15 23 23" src="https://user-images.githubusercontent.com/16443410/139855318-5284f041-e689-4228-aec7-5b0dbb61f5cd.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur (11.5.2)
 - Browser Chrome 95.0.4638.69

**Comment by tastez** [comment]
thanks fixed -
GltfNodeTransform outputs an array of positions, so the example needed to be updated and connected to the right number in the output array.
