### ISSUE TITLE
No basic video file in library example

### ISSUE THREAD

**Issue by 60-hz** [cables-gl/cables_docs#782]
I foticed recently that the "cloud.mp4" file is not accessible anymore from the "Library files" in cables.gl and dev. 
It was handy to have a small example video file for  example testing and during workshops.

**Comment by pandrr** [comment]
yes, it was confusing because it is a stop motion movie and stutters.
i wanted to include an snippet from the open source blender movie. 
do you have any public domain files that would make sense ?

**Comment by 60-hz** [comment]
During workshops, I like to use slow motion video because it's fun to play with.
I found out that recompressing using ffmpeg with one key frame for each frame allows for smoother frame by frale decoding:
`ffmpeg -i input.mp4 -preset slow -crf 18 -vcodec libx264 -x264-params keyint=1 output.mp4`
Also, I think the final size should be light, maybe no more than 5mo...

Here is an example encoded with ffmpeg with the previous settings:
https://github.com/cables-gl/cables_docs/assets/5449719/09214246-6c3e-419b-8cfd-460bc50d80d8

Maybe a short texture-like slow motion file and another one with a little animation with sound could be nice for different purposes ? 

This website have a lot of "free to use" and easy downloadable videos without accounts :
https://www.pexels.com/search/videos/cloud/

**Comment by pandrr** [comment]
thanks, very nice website. i added this video to the default library:
 https://www.pexels.com/video/ocean-waves-on-los-angeles-beach-20325563
