### ISSUE TITLE
VideoTexture : error message with "speed"

### ISSUE THREAD

**Issue by 60-hz** [cables-gl/cables_docs#783]
Ops.Gl.Textures.VideoTexture_v3 

- Create VideoTexture
- Set speed to "-1" or "20" : error message popup:
<img width="846" alt="Capture d’écran 2024-06-05 à 23 48 16" src="https://github.com/cables-gl/cables_docs/assets/5449719/78c6df45-9b4f-40df-8698-28e45197e478">
- Cannot continue to work in the patch, the value of speed always come back to the error value

Test Patch:
https://dev.cables.gl/edit/kwyMNe

**Comment by steam0r** [comment]
thanks for reporting! this will now lead to a warning on dev.cables.gl and let you change your speed to working values.
some browsers support negative playback-rates:

https://github.com/whatwg/html/issues/3754
