### ISSUE TITLE
 OrbitControl wrong value initialisation

### ISSUE THREAD

**Issue by 60-hz** [cables-gl/cables_docs#787]
**Link to simple, reproducible example patch**
(https://cables.gl/edit/uDPSmf)

**Describe the bug**
Recently OrbitControl "initial Axis X"  has error: it display 0.25 but  is 0, so meshes aren't facing the camera anymore.

**How To Reproduce**
1. Open Editor
2. Need to move the camera to see correct mesh orientation

**Platform**
 - MacOS 14.13.1, Chrome Version 125.0.6422.142 (Build officiel) (arm64)

**Comment by 60-hz** [comment]
Would this be back to normal soon?
I am doing a small workshop and it is a bit weird behavior for a very useful operator.

**Comment by pandrr** [comment]
thanks for reporting. is fixed in orbitcontrols v3  on dev.cables.gl
