### ISSUE TITLE
Edit index.html within patch

### ISSUE THREAD

**Issue by mrgingey** [cables-gl/cables_docs#79]
Allow the ability to edit index.html from within the patch and interact with custom html variables.

For instance have a listener in the patch for specific index.html variables to interact with the patch. e.g. index.html variables under <script> which generates hashes or values that can affect values of patch nodes.

**Comment by steam0r** [comment]
add "skip index.html" to export where possible

**Comment by mrgingey** [comment]
> add "skip index.html" to export where possible

Ok so what I may be needing is to be able to edit the index.html to input data under <script><script\> under <head>, this is so I can inject the index.html with a hash. From there to use that hash to interact with the js code by writing it to DOM (I think I can do this with Ops.Html.QuerySelector_v2 to query some custom varibales and code in index.js?)

**Comment by pandrr** [comment]
you could then edit the index.html on github and not overwrite it when exporting

**Comment by mrgingey** [comment]
> you could then edit the index.html on github and not overwrite it when exporting

is it possible for an op that shows what the index.html would be on export? and allow editing it before exporting? 
Just might make things a little quicker for testing instead of having to export to test, if that makes sense?

**Comment by pandrr** [comment]
the index.html will always be the same, it will never be possible to edit it on cables.gl, because this will have tons of implications on how cables.gl works, e.g. the patch view page.

if you need a custom html you need to do it on your side.

**Comment by mrgingey** [comment]
> the index.html will always be the same, it will never be possible to edit it on cables.gl, because this will have tons of implications on how cables.gl works, e.g. the patch view page.
> 
> if you need a custom html you need to do it on your side.

Ah ok fair enough :) thanks for that!!
I presume for me to add custom js, I can just use the CustomOp op, then if I have the custom js writing to DOM I can then use Ops.Html.QuerySelector_v2 to query that data?

And similarly, If I create a custom script in index.html with variables that for instance link to console.log(rand()) in the js custom op, is there a way to grab that data?

sorry for all the questions!

**Comment by pandrr** [comment]
can you explain what you are trying to do ?

why do you want to change the dom just to read it back ?

**Comment by steam0r** [comment]
hm, couldnt all of this be solved with not overwriting index.html and using these ops?

https://cables.gl/op/Ops.Patch.CallBack_v2
https://cables.gl/op/Ops.Patch.Function_v2

following this documentation:

https://cables.gl/docs/4_export_embed/dev_embed_functions/dev_embed_functions

and then maybe using cables-cli for the export (which has an option to "skip index.html")??

https://github.com/cables-gl/cables-cli

i mean, it sounds as if you trying to do "all" of you webdev-tasks in cables...don't...

**Comment by mrgingey** [comment]
> hm, couldnt all of this be solved with not overwriting index.html and using these ops?
> 
> https://cables.gl/op/Ops.Patch.CallBack_v2 https://cables.gl/op/Ops.Patch.Function_v2
> 
> following this documentation:
> 
> https://cables.gl/docs/4_export_embed/dev_embed_functions/dev_embed_functions

Thanks for this, I will take a look at those and see if it will work for what I need :) thanks a lot for all this help!!

**Comment by steam0r** [comment]
we decided to not put this option into the exports, its easy enough to replace the index.html in a zip file on your local machine, with github you can publish to a subdirectory and use another index.html
