### ISSUE TITLE
Cannot create new or edit existing patches

### ISSUE THREAD

**Issue by fariskas** [cables-gl/cables_docs#795]
**Link to simple, reproducible example patch**
Any patch

**Describe the bug**
I havent used cables.gl in a while. But i logged in today and when i try to create any new patch or edit old patches. I get this error:
"GL Error
Could not initialize webgl, or it crashed. Try to restart your browser, or try another one..."

<img width="1009" alt="Screen Shot 2024-06-26 at 15 49 27" src="https://github.com/cables-gl/cables_docs/assets/24261675/e72d54aa-2ff8-4150-9088-12f6773ddf55">

And after a few seconds the error changes to this:

"Cannot read properties of null (reading 'isFocussed') 
Uncaught TypeError: Cannot read properties of null (reading 'isFocussed')"

<img width="884" alt="Screen Shot 2024-06-26 at 15 57 19" src="https://github.com/cables-gl/cables_docs/assets/24261675/e7d97706-0fe4-4505-9214-859de6f328e0">

**How To Reproduce**
1. Open Editor
2. Click on "crash" button

**Platform**
Mac OS Monterey 12.6.2
Chrome Version 126.0.6478.116 (Official Build) (x86_64)

**Dev Tools**
In console i get these errors:

```
cables.js:14899 made with https://cables.gl
cablesui.js:19475 waiting for gui
cablesui.js:43685 webgl not available! :/
scripts.editor.js?nc=1717602538814:2035 Fetch finished loading: GET "https://cables.gl/api/doc/ops/project/667bc7fa267d33832941f451/?nc=1719388457355".
```

---

error is odd as i do have webgl enabled on my browser, and i have no issues with other sites running webgl or when im coding my projects with threejs now

**Comment by pandrr** [comment]
can you post a result url from this page ?
https://cables.gl/browser

thanks

**Comment by fariskas** [comment]
Sure here you go.
https://cables.gl/browser/r/6682823adbcd60832342c9b9

Btw also just tested on safari [Version 15.6.1 (17613.3.9.1.16)] on same device. Same issue

**Comment by fariskas** [comment]
Hi! was wondering if there was any updates regarding this issue? As im not able to access my patches or create new ones. 😢

**Comment by pandrr** [comment]
please try again on dev.cables.gl. it seemed you switched to webgl1 in the user preferences, which is not supported anymore, i turned it off

**Comment by fariskas** [comment]
Yes it works! Thank you~
