### ISSUE TITLE
PointsMaterial doesn't take into account opacity set in vertex colors

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#8]
**Describe the bug**
The current PointsMaterial checkbox doesn't take into account the opacity from the vec4 in PointCloud from Array.
I had to change the vertex shader to take a vec4 as input and change the order of the frag shader from the material.

[Link to the fix](https://cables.gl/edit/JouYVv)

Pandur and Steam are invited.

**Comment by steam0r** [comment]
have put this in the cables backlog, will keep you updated. thanks for reporting!

**Comment by steam0r** [comment]
this has been fixed on dev and will be in the next release
