### ISSUE TITLE
Mobile WASD Camera support and terrain interactivity

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#80]
Hi! As we talk in the meetup, this WASD Camera is great in combination with Cast Ray 3D Selection, but to make it more cool for the masses, the mobile version is needed, sort of inputs for the x, y and z camera and orientation to be controlled with css buttons.

Also you commented that the js library that make this magic have an option to interact with terrain without pixel displacement tricks, so it could be also implemented in the Op.

Thank in advance for this feature, is very cool to make this kind of stuff in cables, speedy and  lightly in the browser.

**Comment by pandrr** [comment]
i implemented wasd cam stuff and invited you to the patch.

please create two issues for two topics next time! thanks!

note for me:
physics op should use cannonjs heightfield
https://schteppe.github.io/cannon.js/docs/classes/Heightfield.html

**Comment by n4hui** [comment]
Thank you very much, i am modifying the patch with the new options :)

**Comment by n4hui** [comment]
Thank you very much! I modified the patch and tested in my Android phone and works very well. The function that is needed too is the orientation to the left and right as it works with the mouse in desktop, i mean to rotate the view in your own axis (i tested it using transform view but it don't works). i added two buttons for this, in my case, orientation only for left and right is enuff, up and down orientation could be more for flying stuff.

**Comment by steam0r** [comment]
please create seperate issues if there multiple issues with different topics

**Comment by n4hui** [comment]
ok

**Comment by steam0r** [comment]
this went live with todays release, have fun!

**Comment by n4hui** [comment]
thank you a lot!
