### ISSUE TITLE
FullscreenRectangle should have  color rgba attributes

### ISSUE THREAD

**Issue by pixtur** [cables-gl/cables_docs#809]
Reasoning:

- Adjusting the brightness or opacity is a common use case.
- FullscreenRectangle ignores BasicMaterial
- Alternative setups with QuadMesh are not obvious and cumbersome to setup
- Performance overhead is negligible

**Comment by pixtur** [comment]
Oh wait. FullScreenRectangle only ignores .BasicMaterial if a texture connected. 
Good to know.

**Comment by pandrr** [comment]
no, op should be kept as minimal as possible. can be used with other materials, or image composes..

**Comment by pixtur** [comment]
okay
