### ISSUE TITLE
TriggerOnChangeNumber does not work as expected

### ISSUE THREAD

**Issue by pixtur** [cables-gl/cables_docs#814]
**Link to simple, reproducible example patch**

Uploading DEV Car With Navigation - Google Chrome 2024-07-25 15-08-14.mp4…

**Describe the bug**
The name of the operator implies that it triggers (once) when the number changes. In fact it triggers (always) if the number port get invalidated (executed after being dirty) even if the number in fact does NOT change. I assume that other people will also fall into that trap. 

I recommend to rename this one to  [TriggerIfNumberIsDirty]  and create a new [TriggerOnNumberChanged]. This new operator should also have an epsilon or threshold parameter. 

**Platform**
dev.cables / Win10 / Chrome

**Comment by pandrr** [comment]
no this is not true, it only triggered when changed
