### ISSUE TITLE
Crash in VizBool

### ISSUE THREAD

**Issue by 60-hz** [cables-gl/cables_docs#832]
**Link to simple, reproducible example patch**

https://cables.gl/edit/UMvK1m

**Describe the bug**
Crash when changing boolean on a very small VizBool op
Crash also in standalone and dev

**How To Reproduce**
1. create a small vizbool op
2. change its boolean input

**Platform**
 - Chrome Version 127.0.6533.120 (Build officiel) (arm64)

Looks like a negative value issue:

<img width="1151" alt="Capture d’écran 2024-08-20 à 23 14 15" src="https://github.com/user-attachments/assets/0c5e3fd3-54e0-499d-a92a-8131ba785990">

**Comment by pandrr** [comment]
fixed on dev.cables.gl
