### ISSUE TITLE
InputElement bug: no text input on MacOS

### ISSUE THREAD

**Issue by 873hz** [cables-gl/cables_docs#833]
There is a bug in InputElement on macOS. I used this patch as a test:
https://cables.gl/p/8Crpnm

No keyboard text is entered after switching an element to Focus mode with a left click. I tried to switch between Input and TextArea modes in the Sidebar, but it didn't help.

I asked people to try this patch on different versions of MacOS and in different browsers, text input didn't work anywhere.
Here are their characteristics:
1) Sonoma 14.2 + Safari 17.1 + Chrome Version 126.0.6478.182
2) Sonoma 14.4 + Safari 17.4

**Comment by pandrr** [comment]
you have to click the canvas again after focussing the sidebar elements


<img width="762" alt="Screenshot 2024-08-26 at 12 14 22" src="https://github.com/user-attachments/assets/7396ba21-af5b-4e13-895a-451fd51e9590">

if you do this it also works after using the sidebar

**Comment by 873hz** [comment]
Thanks. It worked.
