### ISSUE TITLE
Soundcloud link problem

### ISSUE THREAD

**Issue by lukas303** [cables-gl/cables_docs#84]
I seem to be having problems with the Soundcloud link generator or more specifically playing the links generated. The soundcloud link generator seems to be fine when connected directly to an Audio Buffer, but works pretty sporadically,  I reckon it might have a limited number of requests it can send, so is prone to not generating links? but when it is working and I don't directly connect the output of the link generator and instead just copy the string into an audio buffer it doesn't seem to work. I always get the  "Error: The audio file could not be loaded. Make sure the right file URL is used.". Which is a shame as the idea would be just to save the links generated and switch them with a SwitchString operator.

**Comment by steam0r** [comment]
hey,

for the rate-limiting please try to use your own api-key and account in the soundcloud op, and then there is still some ratelimit being applied, soundcloud sadly is really intransparent on what exactly that means.

putting the string into an audiobuffer will also not really work as soundcloud imposes some additional headers on the request to play back that specific url...again, that is on them. switching the string of the soundcloud op itself might work though and give you a changing audiobuffer, right?

best,
steam
