### ISSUE TITLE
MidiInputDevice_v2 receive Program Change error

### ISSUE THREAD

**Issue by lofiddler** [cables-gl/cables_docs#86]
**Describe the bug**
When MidiInputDevice_v2 receives a MIDI Program Change message a  cablefail :/ error is displayed. 
The reason for the error seems to be the missing key `Program Change` in  `OUTPUT_KEYS`.

**To Reproduce**
1. Create a new patch
2. Add MidiInputDevice_v2 and connect your MIDI-device
3. Trigger a Program Change message from your MIDI-device
4. The cablefail :/ error appears. See the screenshots for error details

**Expected behavior**
Program Change messages should be received just like other MIDI-messages.

**Screenshots**
Error details
![image](https://user-images.githubusercontent.com/95292455/144096345-d147571c-725d-41ee-a923-9eacefb685cd.png)

**Desktop (please complete the following information):**
 - OS: [macOS Monterey]
 - Browser [chrome]

**Additional context**
I don't know which is the best way to contribute to bug fixes. I just created private ops and fixed the problem for me. 
To share my fix I uploaded a [zip-file of my private ops](https://github.com/cables-gl/cables_docs/files/7628696/cables_ops_lofiddler.zip) with the modifications and added links to example patches for [Send MIDI Program Change messages](https://cables.gl/p/61a65394ee02f7283a69b423?s=34S2YEgdqErIp7tG) and [MIDI Receive Program Change messages](https://cables.gl/p/61a62ada5192d82850867789?s=ZGrAQRdVCJvtAFkV).

***Fix MidiInputDevice_v2***:
```
const OUTPUT_KEYS = [
    "Event",
    "Note",
    "CC",

    // "Channel Pressure",
    // "Poly Key Pressure",
    "NRPN",
    // 'SysEx',
    // "Pitchbend",
    "Program Change",
    "Clock",
];
```

The result is an extended MidiInputDevice_v2 which now also supports Program Change messages:
![image](https://user-images.githubusercontent.com/95292455/144098823-5547009c-ff8c-43eb-b63d-a13edb24988f.png)

***Extend MidiMonitor and create new op MidiProgramChange***
To make things complete I extended MidiMonitor to support Program Change and created a new op MidiProgramChange (similar to MidiNote or MidiCC):
![image](https://user-images.githubusercontent.com/95292455/144099805-50a5fe3f-27eb-47ba-a42d-1403e3dea76e.png)

***Extend MidiOutputDevice and create new op MidiProgramChangeOut***
In addition I also extended MidiOutputDevice and created a new op MidiProgramChangeOut (similar to MidiNoteOut or MidiCCOut):
![image](https://user-images.githubusercontent.com/95292455/144100750-3c993bd8-4878-4e7c-babc-317b2c305f34.png)

**Comment by tastez** [comment]
hi, zip seems empty here

**Comment by lofiddler** [comment]
Hello
Strange, I just downloaded it here, and it contains 5 ops folders as expected.
Is this zip working?
[cables_ops_lofiddler.zip](https://github.com/cables-gl/cables_docs/files/7634007/cables_ops_lofiddler.zip)

**Comment by tastez** [comment]
guess it was a windows issue - it didn't like the folder "." 

7zip opens it fine! 
![image](https://user-images.githubusercontent.com/78642112/144240310-b4d3f640-ecc8-4dd5-8f9d-f977bdbbcc5c.png)

**Comment by pandrr** [comment]
hi, thank you, they are now available on dev.cables.gl
@tastez tested them using ableton, they seem to work fine

let me know if there are other problems!

**Comment by pandrr** [comment]
https://dev.cables.gl/op/Ops.Dev.MidiProgramChange
https://dev.cables.gl/op/Ops.Dev.MidiProgramChangeOut

**Comment by lofiddler** [comment]
Hi, tested both ops today and the expanded MidiInputDevice_v2, MidiOutputDevice and MidiMonitor. All seems to work as expected. 
I created two patches to demonstrate the usage:
https://dev.cables.gl/p/61a62ada5192d82850867789?s=ZGrAQRdVCJvtAFkV
https://dev.cables.gl/p/61a65394ee02f7283a69b423?s=34S2YEgdqErIp7tG
