### ISSUE TITLE
Include files refrenced in TextureArrayLoader in patch files mainfest

### ISSUE THREAD

**Issue by TobyKLight** [cables-gl/cables_docs#861]
## Feature request 
Any local URLS referenced in the TextureArrayLoader op are included in the files manifest.

Then these are automatically packaged and downloaded with exports.

**Comment by TobyKLight** [comment]
More info:
Files become untracked and linked to old patches when you are in a workflow where you are cloning your patch.

Regularly making a new clone of a patch to update release versions is very useful for showing a client "here's this weeks version".

**Comment by steam0r** [comment]
i am closing this as a duplicate of cables-gl/cables_docs/issues/860
