### ISSUE TITLE
iOS Interaction in Preview not usable (i.e. Orbitcontrols)

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#87]
**Describe the bug**
On iOS Devices the touch input of the canvas interfers with the HTML page, rendering the control of things like Orbitcontrols unusable.

**To Reproduce**
open any patch preview with orbitcontrols on a iphone, ipad

**Expected behavior**
should work like seen on sketchfab, if user touches the canvas, only the canvas is controlled and not the page moved up or down

https://user-images.githubusercontent.com/1138673/144433804-4e9d506f-53da-4127-81a5-c9bf7edc03a0.mp4

**Comment by wirmachenbunt** [comment]
![image](https://user-images.githubusercontent.com/1138673/144435428-fa6ab392-fcf9-4a18-bd76-9799ee76c4a9.png)
sketchfab has this style in mobile view, -webkit-user-drag none ...maybe its this

**Comment by wirmachenbunt** [comment]
don't know how to inject this on my iphone browser

**Comment by steam0r** [comment]
i added this on dev, seems to be fine on my ipad pro, please test again. thanks!

**Comment by wirmachenbunt** [comment]
looking good. seems fixed ! thank you
