### ISSUE TITLE
Upload Assets or Cloning Ops does not work in standalone Windows

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#875]
![image](https://github.com/user-attachments/assets/9b9971ad-3c35-4363-af6e-12df5ac7ec08)
neither cloning nor uploading assets works
both actions result in the console message in the screenshot

**Comment by steam0r** [comment]
is this a saved patch or a fresh one? which op are you trying to clone? how? where to? via manage op? which version of the standalone. which operating system. how do you upload assets? drag and drop? with that button?

sorry... :)

**Comment by wirmachenbunt** [comment]
https://github.com/user-attachments/assets/1143e990-bf6a-4ec6-aefa-1366d9f40a1e

latest standalone, just pressing the upload button results in bug. same error message when trying to clone any op. empty patch. i never worked with cables standalone before.

**Comment by steam0r** [comment]
that button will open a filepicker in the next release. can you create another isse with a video for the clone op problem? thanks!
