### ISSUE TITLE
WASD Op Update Bug

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#88]
Hi! This bug appeared since the november update. This happens when you work in the Op Editor. Before when you clicked the screen the wasd navigation started, so the mouse rotated the orientation, then if you pressed Esc Key, this was disabled, and the preview window was fixed, but now it stills activated, so if you want to make changes, you can't because the mouse stills moves the orientation.

you can test it here editing the patch:

https://cables.gl/p/61b0e5e369154b5a9a1d6c51?s=K7eMQrWu0qjr0w6e

Windows, Desktop, Latest Chrome...

**Comment by steam0r** [comment]
fixed on dev during meetup
