### ISSUE TITLE
Standalone: Cloning op does not work

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#881]
see the video :)

https://github.com/user-attachments/assets/b7ff63c4-85cb-430f-9125-98cd7141aa1d

**Comment by wirmachenbunt** [comment]
![image](https://github.com/user-attachments/assets/3fec9455-7569-4469-a27c-b6110a737c0e)
nightly clones :)

**Comment by steam0r** [comment]
awesome, thank you!
