### ISSUE TITLE
Standalone OSC Extension

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#882]
not working here, or is this still not ready to test ?

![image](https://github.com/user-attachments/assets/f42c10c6-1b46-4828-a18a-275122780c32)

**Comment by steam0r** [comment]
can you try this in nightly build? https://github.com/cables-gl/cables_electron/releases 

thanks!

**Comment by wirmachenbunt** [comment]
yes, the ops show up in nightly but i can not receive nor send data from and to cables in combination with vvvv. i tried different ways. 
there seems to be a connection and the cables in cables show activity but the messages can not be interpreted

![image](https://github.com/user-attachments/assets/5ac6d66c-e460-459b-9604-4394ec2b420e)

**Comment by wirmachenbunt** [comment]
![image](https://github.com/user-attachments/assets/4aee350d-4b31-429f-bc76-1c82ffd00683)
there is some data when i inspect to osc op message

**Comment by steam0r** [comment]
OscNumer is the webosc extension, Osc is the standalone native thingie...it's confusing but the standalone extension only uses osc and oscsend...maybe the other osc ops should be compatible at least in working with "messages"

**Comment by steam0r** [comment]
this looks "workable", doesnt it?

![Bildschirmfoto 2024-10-24 um 15 11 18](https://github.com/user-attachments/assets/b84dcc70-48a3-4f54-9731-6cdadd2f2097)

**Comment by wirmachenbunt** [comment]
true, it might be confusing because there are two OSC solutions in cables standalone ?
the one in the screenshot at least shows one osc channel, but if there are more than one (which is the point of OSC), only one is showing up.

![image](https://github.com/user-attachments/assets/f26b2025-240f-49dd-a307-714bde8845c2)

i tested this with old and new vvvv,  old vvvv correctly sees all the OSC channels while cables just shows the last channel.

again, how do you test this implementation in cables, i ask because maybe vvvv is doing something funky and cables has problems understanding it

**Comment by steam0r** [comment]
channel is "per message", so you definitely only ever see the last one and have to handle receiving these in arbitrary order. try vizlogger so see all of these messages.

i agree that its confusing these other osc ops do not reall work well with these

**Comment by wirmachenbunt** [comment]
![image](https://github.com/user-attachments/assets/fadc5b74-1a7c-4462-b552-13587c7459c5)
yes, there are things in the vizloggger, thanks for this hint.
but why is message not working.

re-reading you comment above, yes, we need ops to understand OSC messages or the whole OSC stuff in cables makes no sense

**Comment by steam0r** [comment]
OscMessage thinks the message hast the address in "a", your messages have the address in "address":

    outAdd.set(msg.a);
    outNum.set(msg.a.length);
    outArr.set(msg.v);

i know basically nothing about the OSC protocol so i do not know which is "right"
