### ISSUE TITLE
[Fixed] VideoTexture play/pause restarts the media at the beginning, rewind is broken

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#9]
VideoTexture play/pause restart the media at the beginning, the rewind doesn't take the set time into account.
The texture is not generated until you play the video.

I tried to fix these issues [here](https://cables.gl/edit/9MPiVv) as we discussed in the meetup.

Please also take a look at the RouteNumber OP included in the patch. It seems to fix another issue as numbers would not be reset to the default value changing the input port number value.
The old and new "correct" version are included in the op.

Both Pandur and Steam are collaborators to the patch.

**Comment by steam0r** [comment]
have put this in the cables backlog, will keep you updated. thanks for reporting!

**Comment by steam0r** [comment]
this has been fixed on dev and will be in the next release
