### ISSUE TITLE
Ops behind title of area are trapped

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#90]
as the title says, if an op is within the titlle area, it seems impossible to move the op without the area

![image](https://user-images.githubusercontent.com/1138673/146036889-3952f6e8-6d5d-4451-aea4-18eb779c447e.png)

**Comment by pandrr** [comment]
you can move the area with cmd/alt without draghing other ops

**Comment by wirmachenbunt** [comment]
ok :) didn't read the manual

**Comment by wirmachenbunt** [comment]
mm, thinking about it, you could give ops a hittest priority, keep them in front of the area title
