### ISSUE TITLE
Mouse clic report inconsistencies

### ISSUE THREAD

**Issue by 60-hz** [cables-gl/cables_docs#905]
**Describe the bug**

Mouse Op:
-Under MacOS,  is reporting "Click Left" only on release, and "Click Right" only on mousedown.
-Under Windows, both are reported on release.

MouseButtons Op:
-Same inconsistency for MouseButtons Op and "Click Left" / "Click Right".
-The remaining "Mouse Down" / "Mouse Up"  buttons ports are all correct here.

**Comment by pandrr** [comment]
it is a common practise to use browser "click" and "contextmenu" events for clicks, this is what those triggers are. their behaviour is defined by browser/OS usw up/down events (touch is also different probably )

it does not work for you, use pointer up/down events

**Comment by 60-hz** [comment]
Ok, thanks!
