### ISSUE TITLE
RectangleTexture - prevent rounded corners from skewing with aspect ratio

### ISSUE THREAD

**Issue by pandrr** [cables-gl/cables_docs#909]
### Discussed in https://github.com/cables-gl/cables_docs/discussions/908

<div type='discussions-op-text'>

<sup>Originally posted by **mariomatasystems** November 12, 2024</sup>
I notice if the RectangleTexture is not 1:1 the rounded corners skew,

<img width="507" alt="Screenshot 2024-11-12 at 21 55 28" src="https://github.com/user-attachments/assets/0b12581f-3a92-4554-ba85-f2a6cf8fe97b">

It would be more useful to keep the rounded corners consistent

Might be wrong (chatgpt) but i think we can tweak the frag code to account for the aspect.

changing this

    float roundn=roundness*min(size.x,size.y);

to this

    vec2 aspectScale = vec2(1.0, size.y / size.x);
    float roundn = roundness * length(size * aspectScale);

</div>

**Comment by marioepsley** [comment]
I see this is closed, just checked on dev (using  Ops.Gl.ImageCompose.RectangleTexture_v5 -) and I think it's still feeding off the dimensions of the image compose. In dev I took these photos;  fine when the image compose width and height are equal, if not equal you get skewed corners still. that said there seems to be some consistency compared to before. 


<img width="887" alt="Screenshot 2024-11-21 at 10 15 08" src="https://github.com/user-attachments/assets/01981970-4af2-4e6c-b01f-084eb5021643">

<img width="889" alt="Screenshot 2024-11-21 at 10 15 00" src="https://github.com/user-attachments/assets/0d064faa-c36e-438b-b16f-900b33ac94eb">

**Comment by pandrr** [comment]
i closed the issue, the discussion is still there.
did you test this code you pasted ? it does not work, or am i not understanding?
sorry, we have no interest in fixing/debugging ai generated code
