### ISSUE TITLE
Allow WebBluetooth on web editor

### ISSUE THREAD

**Issue by kikohs** [cables-gl/cables_docs#913]
I'm trying to make an op for Puck.js: https://www.espruino.com/Web%20Bluetooth in cables web.

But it needs this permission
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy/bluetooth

Do you think it is something that can work through the iframe?

Thank you

**Comment by pandrr** [comment]
i added it to the allow list for the iframe, i hope we dont have to do it via http header. let me know if this works! thx

**Comment by kikohs** [comment]
Unfortunately it needs the header I think

![image](https://github.com/user-attachments/assets/352993cc-4d70-49ff-94b3-bf74ab4fdfac)

**Comment by pandrr** [comment]
<img width="1885" alt="Screenshot 2024-11-18 at 18 44 56" src="https://github.com/user-attachments/assets/ae567b69-5e50-43c6-a6e8-889def084629">

looks like this for me

**Comment by kikohs** [comment]
sorry my bad, i was on live..

**Comment by steam0r** [comment]
this made it to cables.gl with the latest release, just now!

**Comment by kikohs** [comment]
great!!
