### ISSUE TITLE
Upload Logo to Team is broken

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#925]
i can not upload an logo to my team page
using win 11 and latest chrome
nothing fishy in the console

https://github.com/user-attachments/assets/ad366b03-59eb-40b3-b497-0501421b3240

**Comment by steam0r** [comment]
this might be a caching issue, are you sure the logo is not changed (try reloading the page while holding shift)

**Comment by wirmachenbunt** [comment]
![image](https://github.com/user-attachments/assets/3dee5a8f-d3c6-4014-abf4-7954f4d0da90)
yes, it was the cache. crazy, i tried this weeks ago and thought this is temporarily broken. it was the cache on all my machines.
