### ISSUE TITLE
Import patch from standalone export fails

### ISSUE THREAD

**Issue by Joscha95** [cables-gl/cables_docs#927]
**How To Reproduce**
1. Follow the steps for exporting/importing described here: https://cables.gl/docs/6_2_standalone/4_exporting/exporting

**Platform**
 - Standalone Cables-0.4.4
 - upload on the standard cables server (not dev.)

**Dev Tools**
nothing there, except the error as html string seen in the screenshot.

<img width="1422" alt="Screenshot_2024-11-25_at_12 30 16" src="https://github.com/user-attachments/assets/c26b6dec-508d-4547-a1c9-d24dd5d5da09">

**Comment by steam0r** [comment]
this is fixed on cables.gl and dev.cables.gl, can you try again using the same export file? thanks!

**Comment by Joscha95** [comment]
yes works perfectly now, thanks!
