### ISSUE TITLE
Add Texture Map Port to SpotLight Op

### ISSUE THREAD

**Issue by andrejhronco** [cables-gl/cables_docs#939]
I was looking at the SpotLight Op and was wondering if we could add a texture map port so that we can project an image from the spotlight.

TextureProjection Op kind of does this but having it work more like a projection / light would be really nice

pretty cool effect that I would love to be able to use in cables!

<img width="475" alt="image" src="https://github.com/user-attachments/assets/fbbc8e6d-9c8c-470c-a53a-493ff21c0cc5">

**Comment by pandrr** [comment]
#657
