### ISSUE TITLE
WASD BoundingBoxVisible Bug

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#94]
**Describe the bug**
Using the WASD Camera and the BoundingBoxVisible Op to avoid to much geometries processing, there is a bug in a certain point or angle changing the orientation with mouse, i share to you the example:

https://cables.gl/p/61b7ecb362c0d0738ceb70ac?s=x1oR3ERcWxQvWZxn

As you can when navigate, the geometry dissapears in a certain point, even the bounding box is visible...

![Captura de pantalla 2021-12-15 111315](https://user-images.githubusercontent.com/65823796/146233084-3c66dfa9-2f8a-4aa2-a422-3bc8f944d388.jpg)

Thank you in advance fixing this, it is very useful to manage a lot of geometries saving processing, I use the last version of Chrome.

**Comment by pandrr** [comment]
fixed. let me know if it happens again

**Comment by n4hui** [comment]
thank you very much!!! I hope we can see how was the fix in the next meetup
