### ISSUE TITLE
Export on dev.cables.gl is broken

### ISSUE THREAD

**Issue by jachwe** [cables-gl/cables_docs#940]
**Link to simple, reproducible example patch**
https://dev.cables.gl/edit/uyZqEv

**Describe the bug**
The patch cannot be exported. CLI fails with `Error: end of central directory record signature not found` and Browser UI shows 404 error page when clicking on the `Download` Button of the created Zip file.

**How To Reproduce**
1. Open Editor
2. Click `Export` button
3. Choose `Download HTML` Tab
4. Leave Settings unchanged or change if you wish
5. Click `Download`

Alternatively:
- use cables CLI with `cables -e uyZqEv -a all -bmcD -d ./patch`

**Platform**
 - MacOS 14.4.1 
 - Chrome Version 131.0.6778.86 (Offizieller Build) (arm64)

**Dev Tools**
404 on the [download link](https://dev.cables.gl/assets/674b8d7fd83f6213aae0c696//_exports/cables_3d_template_-_Export_Issue_report_html_2.zip)

**Comment by steam0r** [comment]
thanks for reporting! fixed on dev.cables.gl and cables-cli.

**Comment by jachwe** [comment]
thanks for the swift action. i can confirm that it works again through the Browser UI. However the CLI export still seems to be broken. The downloaded .zip file is corrupted.

**Comment by steam0r** [comment]
hm, you are right. i just published a new version of cables-cli (0.22.0) that should now work with and without the `-D` switch
