### ISSUE TITLE
gltf missing file undefined error

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#95]
![Captura de pantalla 2021-12-15 111945](https://user-images.githubusercontent.com/65823796/146234345-d175d25a-e74c-4f59-967d-d9db27942712.jpg)

**Describe the bug**
As you can see in the image there is this this undefined error when for accident you delete an gltf, but the error don't tells you where is the op trouble to fix it, and all the project stops to work, here is the patch example:

https://cables.gl/p/61b97a7382d0e52623bceed6?s=5BpngifAda4ldAjP

Thank you in advance fixing this, i have a project with a lot of gltfs and constantly i need to change versions of thouse, and applying draco compression, so an accidental delete use to happen and i need to check each one of the GLTFScene Ops to find the failed one.

I use the latest version of Chrome in PC

**Comment by pandrr** [comment]
fixed

**Comment by n4hui** [comment]
thank you very much!!!
