### ISSUE TITLE
PhysicsCube OP render On/off doesnt work

### ISSUE THREAD

**Issue by ani67** [cables-gl/cables_docs#97]
**Describe the bug**
PhysicsCube OP render On/off doesnt work - the helper mesh can be controlled by an option in the world op - might be useful to have the functionality in the individual op as well?

**To Reproduce**
1. Create a patch with mainloop+ world + physics cube
2. Turn off render for physicscube

**Expected behavior**
Should ideally hide the rendered outline for physics cube

**Screenshots**

![image](https://user-images.githubusercontent.com/5382030/147075210-a0380641-df09-4bda-a6d7-dafa2f67e807.png)

**Comment by pandrr** [comment]
hi, thanks

the body is drawn by the world op right now, try that option!



notes for me:
- render does not do anything right now, it should also draw the bouynding box, independently from the world op
- there should be an active toggle
