### ISSUE TITLE
Wacom digital pen fails after last update

### ISSUE THREAD

**Issue by n4hui** [cables-gl/cables_docs#98]
Hi! In the last update was lost the support for wacom pen tablets. 

I can't drag ops with the wacom pen as in the past update was posible...

I use the last version of chrome 
wacom stylus

**Comment by pandrr** [comment]
https://dev.cables.gl/browserevents

when you move your pen over the yellow field, do you get eventnames that start with "pointer" on the right side, or only "mouse" ?

**Comment by n4hui** [comment]
Yep mousemove and pointermove and touchstart and touchclick when i click

**Comment by pandrr** [comment]
wacom does not support pointerEvents which are exactly made for hardware like pens... 

https://www.reddit.com/r/wacom/comments/d1vxyu/unable_to_use_wacom_tablet_in_firefox/

can you try this?

ignore firefox, should also work with chrome

**Comment by n4hui** [comment]
Hi! I don't use firefox for cables anymore, anyway i was playing in dev with the wacom and the support is back, thank you!
