### ISSUE TITLE
Stretchable Ops for better looking patches 

### ISSUE THREAD

**Issue by wirmachenbunt** [cables-gl/cables_docs#99]
would be nice to be able to stretch ops, especially sequence. Allows patches to look a little bit cleaner down the line rather than having cables crowded in one place. Yes yes, used to from another node based tool ;)

![stretchable01](https://user-images.githubusercontent.com/1138673/147553889-15848668-f5ae-49bb-af26-1e820b7e989d.jpg)

lame demo
https://cables.gl/p/61cad84678d2167657789282?s=s7FuXmxpr4d2e0r4

**Comment by wirmachenbunt** [comment]
mmm, and then we are almost in the realm of dynamic pin counts...if you run out of ideas for UI improvements

**Comment by pandrr** [comment]
hmhmhmhmhm
i dont like moving ports around like that, it feels like scaling text only on one axis

but yeah resizing will come
